### ISSUE TITLE
ThaumCraft support is not working

### ISSUE THREAD

**Issue by BlueWither** [BobMowzie/MowziesMobs#101]

**Comment by BlueWither** [comment]
Items don't have Thaumcraft aspects but they once had.

**Comment by mser7** [comment]
Thaumcraft is dead, close this

**Comment by mser7** [comment]
Thaumcraft is a famous magic mod that have an aspect system that add in aspects to items and mobs, and he was wondering if you can add in Thaumcraft aspects to this mod as well. But, the author of it just announced that he has abandoned it, and it is now dead, so no need to have compat with it anymore

**Comment by BlueWither** [comment]
In the previous version of TC and this mod, the aspect was set.
https://github.com/BobMowzie/MowziesMobs/issues/41
If there is no more update, I think that it is better to correspond to the last version of TC.

**Comment by BobMowzie** [comment]
@mser7 I know what Thaumcraft is. Mowzie's Mobs 1.4.X had aspect compatibility. Apparently it no longer works.
I know for a fact that people still use Thaumcraft and, seeing as I already implemented it, fixing it shouldn't take to much effort. I'm going to resolve this issue.

**Comment by BobMowzie** [comment]
Testing has shown that Thaumcraft support is working with no issues in the latest version.
