### ISSUE TITLE
[1.12.2] Mod Causes server crash due to Client side class loading server side

### ISSUE THREAD

**Issue by Morpheus1101** [BobMowzie/MowziesMobs#106]
https://puu.sh/CwbYE/c6c47d3f03.txt is crash report

Running Forge *.5.2807
Mod vers: 1.5.1

**Comment by BobMowzie** [comment]
Does the issue persist if you remove all the other mods?

**Comment by Morpheus1101** [comment]
Testing now running mowsies mobs with JEI and journeymap an so far no crash...but i'll leave it running whilst at work an see how things have gone when i get back an update then.

**Comment by BobMowzie** [comment]
Okay. I suspect its a compatibility issue, which means I can't reproduce it unless I know what mod it disagrees with. Thanks.

**Comment by Morpheus1101** [comment]
Make that it just crashed on me.

**Comment by BobMowzie** [comment]
Damn. Okay.

**Comment by Dororl** [comment]
This is happening to me on a server too, it's apparently the new Larntern Mob, running 1.5.1 version of the mod, will post Crash Report whenever i can.

**Comment by Dororl** [comment]
https://mclo.gs/8UxBqc6 Read line from line **379** to below, that's the crash.

**Comment by BobMowzie** [comment]
Will fix soon. In the meantime, please disable Lanterns in the configuration file.

**Comment by VillainousScum** [comment]
This is the same as #103

**Comment by Morpheus1101** [comment]
Disabled Lanterns in config file and server still crashes instantly

**Comment by dewobedil** [comment]
same as me xD
