### ISSUE TITLE
Crashes when fighting with naga

### ISSUE THREAD

**Issue by BlueWither** [BobMowzie/MowziesMobs#107]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2019-01-14 16:26:53 JST
Description: Unexpected error

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at net.minecraft.client.audio.SoundManager.updateAllSounds(SoundManager.java:233)
    at net.minecraft.client.audio.SoundHandler.update(SoundHandler.java:293)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1858)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4442)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Nonname114'/0, l='MpServer', x=-1336.57, y=88.12, z=-670.25]]
  Chunk stats: MultiplayerChunkCache: 81, 81
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (-264,64,223), Chunk: (at 8,4,15 in -17,13; contains blocks -272,0,208 to -257,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 34094 game time, 8412 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 60 total; [EntityTippedArrow['矢'/14082, l='MpServer', x=-1376.27, y=104.44, z=-718.20], EntityDart['entity.dart.name'/14595, l='MpServer', x=-1295.84, y=53.27, z=-667.92], EntityPlayerSP['Nonname114'/0, l='MpServer', x=-1336.57, y=88.12, z=-670.25], EntityDart['entity.dart.name'/14597, l='MpServer', x=-1295.59, y=39.22, z=-663.44], EntityDart['entity.dart.name'/14601, l='MpServer', x=-1295.88, y=-26.75, z=-683.13], EntityItem['item.item.egg'/14352, l='MpServer', x=-1355.88, y=68.00, z=-685.88], EntityDart['entity.dart.name'/14620, l='MpServer', x=-1295.76, y=21.16, z=-691.67], EntityBat['コウモリ'/13601, l='MpServer', x=-1290.53, y=45.05, z=-639.49], EntityTippedArrow['矢'/14122, l='MpServer', x=-1378.21, y=80.76, z=-681.51], EntityItem['item.item.egg'/14391, l='MpServer', x=-1359.07, y=84.00, z=-717.18], EntityItem['item.item.egg'/14392, l='MpServer', x=-1372.47, y=78.00, z=-674.08], EntityChicken['ニワトリ'/13630, l='MpServer', x=-1356.42, y=64.00, z=-680.48], EntityPig['ブタ'/13631, l='MpServer', x=-1373.28, y=80.00, z=-684.48], EntityChicken['ニワトリ'/13633, l='MpServer', x=-1356.39, y=64.00, z=-677.84], EntityChicken['ニワトリ'/13634, l='MpServer', x=-1362.21, y=79.00, z=-693.50], EntityItem['item.item.feather'/14402, l='MpServer', x=-1364.08, y=79.00, z=-687.23], EntityDart['entity.dart.name'/14659, l='MpServer', x=-1295.39, y=29.00, z=-674.67], EntityItem['item.item.feather'/14404, l='MpServer', x=-1372.04, y=78.00, z=-674.46], EntitySkeleton['スケルトン'/14158, l='MpServer', x=-1379.50, y=27.00, z=-700.50], EntityTippedArrow['矢'/13907, l='MpServer', x=-1326.60, y=113.63, z=-623.16], EntityCreeper['クリーパー'/14165, l='MpServer', x=-1377.50, y=27.00, z=-698.50], EntityTippedArrow['矢'/13924, l='MpServer', x=-1346.56, y=58.26, z=-623.26], EntityTippedArrow['矢'/14189, l='MpServer', x=-1366.58, y=95.45, z=-639.47], EntityXPOrb['経験値オーブ'/14449, l='MpServer', x=-1321.75, y=73.00, z=-651.95], EntityXPOrb['経験値オーブ'/14450, l='MpServer', x=-1319.44, y=70.00, z=-652.51], EntityItem['item.item.nagaFang'/14451, l='MpServer', x=-1320.04, y=73.00, z=-654.63], EntityChicken['ニワトリ'/13685, l='MpServer', x=-1368.03, y=73.00, z=-671.50], EntityPig['ブタ'/13693, l='MpServer', x=-1375.25, y=73.00, z=-672.45], EntityPig['ブタ'/13694, l='MpServer', x=-1364.25, y=79.00, z=-693.41], EntityChicken['ニワトリ'/13695, l='MpServer', x=-1373.67, y=78.00, z=-675.21], EntityXPOrb['経験値オーブ'/14207, l='MpServer', x=-1335.03, y=78.00, z=-660.84], EntityChicken['ニワトリ'/13696, l='MpServer', x=-1371.99, y=78.00, z=-674.50], EntityMinecartChest['チェスト付きトロッコ'/13697, l='MpServer', x=-1371.50, y=26.06, z=-695.50], EntityChicken['ニワトリ'/13702, l='MpServer', x=-1371.56, y=80.00, z=-690.53], EntityDart['entity.dart.name'/14476, l='MpServer', x=-1295.70, y=53.43, z=-680.62], EntityItem['item.tile.torch'/13710, l='MpServer', x=-1374.69, y=20.00, z=-630.63], EntityTippedArrow['矢'/14223, l='MpServer', x=-1368.79, y=63.76, z=-639.96], EntityTippedArrow['矢'/14241, l='MpServer', x=-1376.56, y=84.32, z=-640.56], EntityMinecartChest['チェスト付きトロッコ'/13732, l='MpServer', x=-1376.50, y=25.06, z=-649.50], EntityDart['entity.dart.name'/14501, l='MpServer', x=-1295.81, y=14.32, z=-704.47], EntityZombieVillager['村人ゾンビ'/13734, l='MpServer', x=-1376.51, y=70.00, z=-668.19], EntityDart['entity.dart.name'/14505, l='MpServer', x=-1376.05, y=50.82, z=-672.34], EntityCreeper['クリーパー'/13737, l='MpServer', x=-1378.70, y=31.00, z=-698.70], EntityDart['entity.dart.name'/14507, l='MpServer', x=-1376.25, y=-22.90, z=-677.84], EntityDart['entity.dart.name'/14511, l='MpServer', x=-1376.50, y=51.93, z=-671.95], EntityItem['item.tile.torch'/13749, l='MpServer', x=-1377.96, y=24.00, z=-639.09], EntityZombie['ゾンビ'/13500, l='MpServer', x=-1290.52, y=50.00, z=-653.45], EntityCreeper['クリーパー'/13501, l='MpServer', x=-1290.57, y=50.00, z=-654.20], EntityChicken['ニワトリ'/13770, l='MpServer', x=-1359.12, y=84.00, z=-716.45], EntityMinecartChest['チェスト付きトロッコ'/13771, l='MpServer', x=-1377.50, y=31.06, z=-706.50], EntityChicken['ニワトリ'/13774, l='MpServer', x=-1290.26, y=90.00, z=-716.67], EntityItem['item.item.egg'/14294, l='MpServer', x=-1363.26, y=78.00, z=-686.13], EntityDart['entity.dart.name'/14550, l='MpServer', x=-1372.51, y=-42.47, z=-640.00], EntityDart['entity.dart.name'/14552, l='MpServer', x=-1376.44, y=51.24, z=-679.53], EntitySkeleton['スケルトン'/14043, l='MpServer', x=-1307.50, y=46.00, z=-634.50], EntityItem['item.item.egg'/14302, l='MpServer', x=-1355.59, y=63.00, z=-681.77], EntityDart['entity.dart.name'/14565, l='MpServer', x=-1376.26, y=21.82, z=-702.58], EntitySquid['イカ'/13544, l='MpServer', x=-1341.39, y=56.02, z=-623.98], EntityNaga['ナーガ'/14583, l='MpServer', x=-1347.52, y=105.60, z=-664.41], EntityDart['entity.dart.name'/14590, l='MpServer', x=-1295.82, y=38.77, z=-688.48]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_151, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2859121224 bytes (2726 MB) / 4277534720 bytes (4079 MB) up to 4277534720 bytes (4079 MB)
  JVM Flags: 8 total; -Xms4G -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=256M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 5, tcache: 1, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2796 Optifine OptiFine_1.12.2_HD_U_E3 20 mods loaded, 20 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                       | Version         | Source                                  | Signature                                |
       |:------ |:------------------------ |:--------------- |:--------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                | 1.12.2          | minecraft.jar                           | None                                     |
       | LCHIJA | mcp                      | 9.42            | minecraft.jar                           | None                                     |
       | LCHIJA | FML                      | 8.0.99.99       | forge-1.12.2-14.23.5.2796.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                    | 14.23.5.2796    | forge-1.12.2-14.23.5.2796.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | unicodefontextensioncore | 1.12.2-2.6      | minecraft.jar                           | None                                     |
       | LCHIJA | foamfixcore              | 7.7.4           | minecraft.jar                           | None                                     |
       | LCHIJA | dsurroundcore            |                 | minecraft.jar                           | None                                     |
       | LCHIJA | unicodefontextension     | 1.12.2-2.7      | UnicodeFontExtension-1.12.2-2.7.jar     | None                                     |
       | LCHIJA | rpghud                   | 3.6.6.2         | [1.12] RPG-HUD-3.6.6.2.jar              | None                                     |
       | LCHIJA | jei                      | 4.8.0.108       | jei_1.12.2-4.8.0.108.jar                | None                                     |
       | LCHIJA | quark                    | r1.5-144        | Quark-r1.5-144.jar                      | None                                     |
       | LCHIJA | autoreglib               | 1.3-24          | AutoRegLib-1.3-24.jar                   | None                                     |
       | LCHIJA | foamfix                  | 0.10.3-1.12.2   | foamfix-0.10.3-1.12.2.jar               | None                                     |
       | LCHIJA | moreplayermodels         | 1.12.2          | MorePlayerModels_1.12.2(18jan18).zip    | None                                     |
       | LCHIJA | llibrary                 | 1.7.17          | llibrary-1.7.17-1.12.2.jar              | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | mowziesmobs              | 1.5.1           | mowziesmobs-1.5.1.jar                   | None                                     |
       | LCHIJA | naturescompass           | 1.5.0           | NaturesCompass-1.12.2-1.5.0.jar         | None                                     |
       | LCHIJA | vanillafix               | 1.0.10-SNAPSHOT | VanillaFix-1.0.10-98.jar                | None                                     |
       | LCHIJA | dsurround                | 3.4.10.5        | DynamicSurroundings-1.12.2-3.4.10.5.jar | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | presets                  | 3.4.10.5        | DynamicSurroundings-1.12.2-3.4.10.5.jar | None                                     |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.10-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-98.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      LoadingPlugin (Quark-r1.5-144.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      CorePlugin (UnicodeFontExtension-1.12.2-2.7.jar)
                                        bre.ufex.asm.Transformer
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.5.jar)
                                        org.blockartistry.DynSurround.asm.Transformer
  GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.14.4264' Renderer: 'Intel(R) HD Graphics'
  Suspected Mods: Unknown
  Launched Version: 1.12.2
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics GL version 4.3.0 - Build 10.18.14.4264, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: No
  Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
  Type: Client (map_client.txt)
  Resource Packs: SE-Soundfix-v0.1.zip, Grimoire-of-Gaia-3-Soundpack-1.0-1.12.zip, MaidIcon_forVoxelMap.zip, DragononMap.zip, Wild+Dragons+V3.zip
  Current Language: 日本語 (日本)
  Profiler Position: N/A (disabled)
  CPU: 2x Intel(R) Celeron(R) 3205U @ 1.50GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by BobMowzie** [comment]
I see no mention of the naga or anything related to Mowzie's Mobs in the error. It's possible that this is an MM error, but it is equally likely to be caused by one of the other mods you have installed. I have not experienced such a crash, and must conclude for now that this is not an MM issue.

If it occurs again when fighting a naga, please let me know.
