### ISSUE TITLE
Error or not ? (version 1.5.2)

### ISSUE THREAD

**Issue by LDsanya** [BobMowzie/MowziesMobs#115]
maybe not an error, but in line 76 in the file /src/main/java/com/bobmowzie/mowziesmobs/server/biome/BiomeDictionaryHandler.java
 instead of nagabiomes, lanternBiomes.add (b);

Sorry, if not right, very cool mod, though sometimes Crashes because of Lantern, so I'm looking for solutions

**Comment by BobMowzie** [comment]
Good catch, but not going to cause crashes or lag.

The crash should be fixed now. Is it not?

**Comment by LDsanya** [comment]
I'll post crash logs a bit later, crashes are still on version 1.5.2

**Comment by LDsanya** [comment]
the server itself hangs, the client continues to work, but everything in the world freezes, in crash report
> [23:02:52] [Server thread / WARN] [FML]: LLibrary loaded a new chunk [1, 1] in dimension 0 (overworld ) while populating chunk [3, 2], causing cascading worldgen lag.
> [23:02:52] [Server thread / WARN] [FML]: Please report this tracker to the mod's issue tracker. This log can be disabled in the Forge config.
> [23:02:52] [Server thread / WARN] [FML]: LLibrary loaded a new chunk [2, 1] in dimension 0 (overworld) while populating chunk [3, 2], causing cascading worldgen lag.
> [23:02:52] [Server thread / WARN] [FML]: Please report this tracker to the mod's issue tracker. This log can be disabled in the Forge config.
