### ISSUE TITLE
Naga behaves strangely when frozen with an Ice Crystal

### ISSUE THREAD

**Issue by PCAwesomeness** [BobMowzie/MowziesMobs#117]
![2019-01-18_22 03 34](https://user-images.githubusercontent.com/8507148/51421977-f3126e00-1b6c-11e9-8094-4d2ed5b5ee66.png)

Upon thawing, it also teleports to a random location (only when it's idle, but still).

**Comment by BobMowzie** [comment]
I think its working now.
