### ISSUE TITLE
Foliaath not spawning

### ISSUE THREAD

**Issue by BlueWither** [BobMowzie/MowziesMobs#118]
From curseforge, and I tried to find but not spawned

**Comment by LDsanya** [comment]
They spawn only at night, and by default have a low spawn rate.
For my world in the mod settings, I changed to I: "Foliaath Spawn Rate" = 400 ,try this

**Comment by BlueWither** [comment]
But they should also spawn at day...

**Comment by BobMowzie** [comment]
Foliaaths now spawn according to light level to prevent them from spawning in player livestock pens. This is intentional.
