### ISSUE TITLE
(1.11.2) (1.4.0) Crash With Ticking Entity

### ISSUE THREAD

**Issue by SgtRalphie** [BobMowzie/MowziesMobs#12]
[crash-2017-08-03_19.59.11-client.txt](https://github.com/BobMowzie/MowziesMobs/files/1198888/crash-2017-08-03_19.59.11-client.txt)
[crash-2017-08-03_16.01.25-client.txt](https://github.com/BobMowzie/MowziesMobs/files/1198890/crash-2017-08-03_16.01.25-client.txt)

Crash with these two mods on a ticking entity. Says something about server event handler. Only crashes with the newest version of the mod. Crashing happens randomly.

**Comment by BobMowzie** [comment]
Should be fixed in the next patch.
