### ISSUE TITLE
The "Naga" Mob causes an NoSuchFieldError

### ISSUE THREAD

**Issue by 0xEviqnn** [BobMowzie/MowziesMobs#130]
Hey there, @BobMowzie !

Upon a few users reporting a bug with Naga's Spawning; I have looked into this issue further.

### Basic Details:

- **Using Minecraft Version:** 1.12.2
- **Using Forge Version:** 14.23.5.2814 (as of 03/03/19 latest)
- **Using Java:** Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
- **Using OS:** Windows 10 - Build 17134

- **Using Mowzies Mobs Version:** 1.5.3 (mowziesmobs-1.5.3.jar)

**If you feel this could be a mod conflict you can see the modpack I am testing this on below.**
https://www.technicpack.net/modpack/one-life-popular-smp.1297373

*I know that SpongeForge creates a few errors at times; but for this error. SpongeForge is not installed or required- this error occurs with or without it.*

### Now, the reproduce:

- Whats expected to happen:
I place down a "Spawn Naga" egg.
I see a Naga.

- What actually happens:
I place down a "Spawn Naga" egg.
Nothing happens besides the server terminal creating an error.

### Obvious/Quick examination of the Server-Error created:

Upon reading into the log (where the error is stored)
The exact message is:
[00:38:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchFieldError: dc

Now this could be quite obvious; but it seems as though that there is no form of variable for the call `dc`

This causes the mob to not spawn but produce an error as the game does not understand what `dc` is or what is defines.

### Server-Log or Error Message:

You can view the server log here, the pastebin link is set to not expire.
https://pastebin.com/pk6VS9KE

**Comment by BobMowzie** [comment]
Hm. Does this happen on singleplayer as well?
It’s just an error message? The server doesn’t crash, yes?

I think I see the issue...

**Comment by 0xEviqnn** [comment]
I will attempt later on for single player~

The server doesn’t crash or close. Nothing happens besides an error message within he terminal.

**Comment by 0xEviqnn** [comment]
This could also be an issue for #126.

**Comment by 0xEviqnn** [comment]
@BobMowzie Nagas do spawn in singleplayer. This would normally mean that this is a server-sided issue, but following that every other mob besides the Naga works as expected; I would think that this is indeed an Mowzies Mob related issue. As referenced previously issue #126 also mentions Naga Spawning but crashing the server instead- this could be related to this issue as well as when tested with the server, it causes an error- but not a crash.

I appreciate your efforts and swift response man, I love the mod you have created as well as the betweenlands i'm pretty sure you've collaborated on too.

Keep up the awesome job and I hope that this information helps you out!
