### ISSUE TITLE
Minecraft crashes when loading a FoliaathBabyModel (1.7.10)

### ISSUE THREAD

**Issue by yourizuring** [BobMowzie/MowziesMobs#131]
Just encountered an error while loading the model of the baby Faliaath in Minecraft while starting up.
[crash-2019-03-03_09.24.02-client.txt](https://github.com/BobMowzie/MowziesMobs/files/2922899/crash-2019-03-03_09.24.02-client.txt)

**Comment by BobMowzie** [comment]
You need to install LLibrary to run Mowzie's Mobs.

**Comment by yourizuring** [comment]
I did install LLibrary, because it was required, but it still crashed on me

Op vr 8 mrt. 2019 om 00:49 schreef BobMowzie <notifications@github.com>:

**Comment by BobMowzie** [comment]
Try installing an earlier version of LLibrary. Maybe 1.7.6?
