### ISSUE TITLE
a bug to copy an item

### ISSUE THREAD

**Issue by heiseshuishan** [BobMowzie/MowziesMobs#132]
![1](https://user-images.githubusercontent.com/33478233/53819195-6698ff00-3fa4-11e9-8cee-dd5f299bad73.gif)

**Comment by BobMowzie** [comment]
This is an issue with Futurepack, not Mowzie's Mobs. Futurepack's blocks should drop on being destroyed, not moved.

**Comment by mcenderdragon** [comment]
not it is not. because of tileEntity fuckery I use the on breakBlock method to drop an Item, as to other times the TileEntity is no longer present and thus the machien would be lost. I have no posibility in changing that, so please fix this on your side by removing dropped items afterwards.

**Comment by BobMowzie** [comment]
What happens when you push the machine with a piston?

**Comment by mcenderdragon** [comment]
Nothing as vanilla can not push blocks with TileEntitys. What haeppns when this axe hits a filled vanilla chest?

**Comment by BobMowzie** [comment]
Nothing, it's set to ignore non-cube blocks. Furnaces, however, will drop their items. No duplication, though.

I'll see if I can set it to ignore blocks with tile entities too.

**Comment by heiseshuishan** [comment]
please
