### ISSUE TITLE
[1.12.2]Fighting Barakoa with Heavy Plate Shield(from Immersive Engineering) crashed server

### ISSUE THREAD

**Issue by lordfriend** [BobMowzie/MowziesMobs#133]
Report from my friend: they were fighting the barakoa (wielding shield) using their Heavy Plate Shield equipped with flash bulb then the server crashed.

Here is the crash-report
[crash-2019-03-06_03.41.19-server.txt](https://github.com/BobMowzie/MowziesMobs/files/2934456/crash-2019-03-06_03.41.19-server.txt)

**Comment by lordfriend** [comment]
I tried in singleplayer and successfully reproduced this bug

**Comment by BobMowzie** [comment]
This is caused by a strange interaction with the vanilla EntityAIAttackMelee task. While a mob is attacking using this AI, they are set to look at their attack target. This crash happened because a Barakoa was instructed to look at their attack target while that attack target didn't exist. However, the vanilla task is set to abort if the attack target doesn't exist. Somehow, the task was not aborted and the Barakoana was instructed to look at a nonexistent attack target.

I don't see what the Heavy Plate Shield would have to do with this. Can you try reproducing this crash without using the shield? Could you try to produce it while fighting other mobs and not just the Barakoana?

**Comment by lordfriend** [comment]
Well, I haven't experienced a similar bug when using vanilla shield or Heavy Plate Shield without Flashbulb. I tried with some other component like shock shield to fight Baraokoana they are all Ok.

I tried this shield (with flash bulb) to fight against Wroughtnaut Knight, Foliaath, Frostmaw, Sun's Chief they are all good and didn't crash.

Wroughtnaut: after attacking the shield. will turn to another direction.
Foliaah: totally not affected by this shield, will attach player anyway.
Frostmaw: not affected.
Sun's Chief: I think this mob doesn't use a melee attach only use magic. so it will not trigger the blinding flash.

I also tried some other mobs from vanilla and The Grimoire of Gaia they all have similar behavior that is stunning for a while after attacking the shield.

**Comment by BobMowzie** [comment]
What is the flashbulb?

**Comment by lordfriend** [comment]
It's an upgrade for the Heavy Plate Shield which can produce a blind flash (the attack can see that if a player attacks the shield he will have a white screen for a while.
(reference:
https://github.com/BluSunrize/ImmersiveEngineering/blob/5425830a8b33c36a2b342a1b3f1556f822404892/src/main/resources/assets/immersiveengineering/lang/en_us.lang#L812)

**Comment by BobMowzie** [comment]
Does it do anything to mobs? Maybe, prevents them from targeting a player they just attacked?

**Comment by lordfriend** [comment]
After looked up the code. It seems that it turns the player entity backward. but the method `hitShield` is called when the entity is a player.
https://github.com/BluSunrize/ImmersiveEngineering/blob/e3e8cf65dadb2762cb343cc5f31d9bf9a29f2188/src/main/java/blusunrize/immersiveengineering/common/items/ItemIEShield.java#L158

**Comment by BobMowzie** [comment]
`if(t instanceof EntityLiving)
						((EntityLiving)t).setAttackTarget(null);`
This is the problem line. It sets the attack target to "null", but attack target needs to be a non-null value in the vanilla melee attack behavior.
The only thing I don't understand is why it only causes a problem with the Barakoana. Based on my understanding, this issue should affect all mobs using the melee attack behavior.
