### ISSUE TITLE
Foliaath don't drop seed

### ISSUE THREAD

**Issue by BlueWither** [BobMowzie/MowziesMobs#138]
I killed over 50 Foliaaths, but they didn't drop any seeds...

**Comment by BobMowzie** [comment]
Do you have any other mods installed?

**Comment by BlueWither** [comment]
LiteLoader1.12.2
Forge1.12.2-14.23.5.2796
AutoRegLib-1.3-24
BetterFps-1.4.8
DynamicSurroundings-1.12.2-3.4.10.5
foamfix-0.10.3-1.12.2
jei_1.12.2-4.8.0.108
llibrary-1.7.17-1.12.2
MorePlayerModels_1.12.2(18jan18)
mowziesmobs-1.5.3
OptiFine_1.12.2_HD_U_E3
Quark-r1.5-144
torohealth-1.12.2-11
UnicodeFontExtension-1.12.2-2.7
VanillaFix-1.0.10-98

**Comment by adalada** [comment]
I also killed 50 foliaath and didn't get a seed. This is the only mod I have in my mod folder, but I have a lot of other configs if that makes any difference.
