### ISSUE TITLE
[Request] Option to remove overworld spawn restriction

### ISSUE THREAD

**Issue by Mike-U5** [BobMowzie/MowziesMobs#139]
So I'm not asking for some advanced mob-spawning configs. There's other mods such as BiomeTweaker that can handle that.  
  
However, the mobs in this mod appear to be hardcoded to only ever spawn in the overworld. This means that you can't use mods like BiomeTweaker to get them to spawn elsewhere.

So if possible, I'd like a config option to toggle this behavior.

**Comment by BobMowzie** [comment]
Yeah, that makes sense. Be warned, I prevent the spawning due to uncontrollable and rampant modded dimension spawns. But yeah, players should have the option.

**Comment by BobMowzie** [comment]
Yeah, that makes sense. Be warned, I prevent the spawning due to uncontrollable and rampant modded dimension spawns. But yeah, players should have the option.
