### ISSUE TITLE
A Language File(Simplified Chinese)

### ISSUE THREAD

**Issue by GingerMeow** [BobMowzie/MowziesMobs#141]
I know this mod have a language file in Simplified Chinese,but I think my language file is better.
Could you think about it?
By the way,can I help you translate it in Simplified Chinese?
Thanks a lot.
(I can't upload a file with ".lang" here,please open it with notepad++)
[zh_cn.txt](https://github.com/BobMowzie/MowziesMobs/files/3050514/zh_cn.txt)

**Comment by BobMowzie** [comment]
Hm, I don't know any Chinese at all, so I really can't understand the difference. Would you mind explaining the changes you made?

**Comment by GingerMeow** [comment]
Thank you for waiting.
(I can't upload a file with ".lang" here,please open it with notepad++)
[Explain the Translated Names.txt](https://github.com/BobMowzie/MowziesMobs/files/3058852/Explain.the.Translated.Names.txt)

**Comment by BobMowzie** [comment]
Thank you! These seem like great improvements! I will implement these in the next patch.

**Comment by GingerMeow** [comment]
My pleasure.

**Comment by BobMowzie** [comment]
Hey, I just went to copy over the file, but there's an issue with all of the text:
http://prntscr.com/nccik4

I think you'll need to make a "Pull Request" to send me the changes correctly.

**Comment by GingerMeow** [comment]
I'm so sorry that I was too busy to read messages. Did you solve this problem?

**Comment by BobMowzie** [comment]
No, the issue is not something I can solve. You’ll need to create a pull request with the .lang file for this to work.

**Comment by BobMowzie** [comment]
Implemented
