### ISSUE TITLE
Ticking World

### ISSUE THREAD

**Issue by RodrigoTaipe93** [BobMowzie/MowziesMobs#146]
Hello, Mowzie!!!

I'm afraid to say that the "Ticking World" fix didn't work. I do have the same crash:

- https://paste.dimdev.org/quromaneto.mccrash

- https://paste.ee/p/o9zRj

(Multimob is included)

I tested the mods by groups and it's only when Mowzie's Mobs mod the game crashes....

**Comment by SoulofSectonia** [comment]
I'm getting a ticking world crash too. Though I don't know what Multimob is. Someone told me it was an optifine bug but I removed optifine and it kept happening untill I took out Mowzie's Mobs and llibrary .I think it might be related to setting the lantern's spawn chance to 0 in the config.  https://pastebin.com/6J5AyjW9

**Comment by BobMowzie** [comment]
Both of these seem to be different issues, and ones I've never seen before or have been able to recreate. Do either of you remember what kind of environment they were in or near when the crash happened?

**Comment by BobMowzie** [comment]
@RodrigoTaipe93 Your crash logs have disappeared. Could you please post them again?

**Comment by RodrigoTaipe93** [comment]
I lost it :(
I've been playing without Mozwie's mod for a while. My world is ok now.
I remember that the only issue I had was with the "Ferrous Wroughtnaut". Not with the mob itself, but rather with the dungeon structure were it spawns.
I was looking at the config file. I can reduce the spawns of every mob except the FW, or at least the dungeon :(
Sorry for any troubles due to the missing crash log :S

**Comment by BobMowzie** [comment]
Ah, damn. Well, I'll keep an eye out to see if it comes back.
Wait, why can't you reduce Wroughtnaut spawns? Is the entry missing?
