### ISSUE TITLE
Sun Chief Range Way Too Far

### ISSUE THREAD

**Issue by MokahTGS** [BobMowzie/MowziesMobs#147]
I'm having the Sun Chief attack me with the sun ray attack from over 500 blocks away.

https://www.dropbox.com/s/wrrlukpw2ibtbpj/2019-04-26_11.57.53.png?dl=0

If you look at the map image the Barakoa village is over by the slime island and the chief is attacking me while I'm over by the villagers.  I can't even see him and he is agroing on me.  Is there a way to turn down his range?

**Comment by BobMowzie** [comment]
That is strange. Are you sure there isn’t another one closer by attacking you?

Barako has a large attack range to prevent players from cheesing him with arrows. This looks like way too far, though.

**Comment by MokahTGS** [comment]
Yup, not any others around the village.  We checked.

**Comment by BobMowzie** [comment]
I think I fixed this.
