### ISSUE TITLE
Ferrous Wroughtnaut bugs and related

### ISSUE THREAD

**Issue by DemonfangArun** [BobMowzie/MowziesMobs#148]
Forge: x.2836
Mowzie: 1.5.4
LLIB: 1.7.19

Wroughtnaughts:
-Have a bit of a derpy hitbox which can result in them floating in a lot of situations where there is uneven terrain. When this happens they may not register/ignore the player
    -This also happens:
![2019-05-04_02 20 35](https://user-images.githubusercontent.com/17183816/57172730-dd5e4700-6df1-11e9-904d-8db998244759.png)

-Do not respond to the kill entities command "/kill @e[type=!player]" kills everything else, INCLUDING the draconic evolution chaos dragon.

-And while I'm here, the axe of a thousand metals swing is a bit derpy since you're still holding it in it's resting position during the animation

**Comment by dd957** [comment]
It seems this mob in particular is very broken. Has corrupted multiple times and ruined two worlds of mine.

**Comment by BobMowzie** [comment]
Your crashes are an interaction issue with Foamfix. Removing Foamfix should allow you to access your worlds.

**Comment by 71vl17** [comment]
So, what's the solution?

**Comment by BobMowzie** [comment]
The solution to which reported issue?

**Comment by DemonfangArun** [comment]
I would assume the op.

**Comment by BobMowzie** [comment]
The issues listed in the OP need to be addressed by me in a future patch. They are extremely tied to limitations of Minecraft’s engine, so I’m not sure I’ll be able to fix all of them. I have not witnessed issues 1 and 2, so these will be hardest to fix. 3 I can fix easily. 4 is unsolvable as far as I can tell; Minecraft will not allow me to hide or animate the items in players’ hands.

None of these issues seem severe enough to warrant disabling the Wroughtnaut entirely. What made you decide to do this?
