### ISSUE TITLE
Barakoa spawn config not working.

### ISSUE THREAD

**Issue by LodtheFraud** [BobMowzie/MowziesMobs#149]
I am hosting a 1.12.2 minecraft server for a few of my friends. While I don't mind them, a lot of them dislike the barakoa enemies, and I tried to disable their spawning using the config files. However, they keep on spawning. I have tried killing all currently alive Barakoa to see if it was just previously spawned entities that hadn't been killed.  Is there any fix to this, or am I do something incorrectly?

![Barakoa](https://user-images.githubusercontent.com/50425180/57405946-aef3b980-71ad-11e9-9e5f-65e446c1479f.png)

**Comment by BobMowzie** [comment]
Are you using any other mods that affect mob spawning?

**Comment by LodtheFraud** [comment]
I have "CustomMobSpawner," but that mainly deals with the Mo' Creatures mod IIRC. Besides that, not much that I can pinpoint specifically. The mods folder is pretty large though, and I can link an image of it.
![image](https://user-images.githubusercontent.com/50425180/57410225-38a88480-71b8-11e9-8b35-97a50d11831d.png)
Ty for the help/responding so quickly btw. Let me know if you need any other information about it

**Comment by LodtheFraud** [comment]
Forgot to mention, I did uninstall Mo' Creatures, and plan on uninstalling custom mob spawner - I just forgot to mention it to the other users at the time.

**Comment by BobMowzie** [comment]
With Custom Mob Spawner installed, you have to configure all mobs that would ordinarily spawn on vanilla systems using Custom Mob Spawner configs. This includes my Barakoana, Foliaath, Grottol, Lantern, and Naga mobs.

**Comment by LodtheFraud** [comment]
Thanks, that helps a lot.
