### ISSUE TITLE
EntityIceBall plays sound in constructor instead of Entity#onAddedToWorld()

### ISSUE THREAD

**Issue by jredfox** [BobMowzie/MowziesMobs#150]
The entity should always be added into the world before an entity starts playing a sound this is bad practice. What if a user just wanted to render the mob on client only side such as a vanilla mob spawner you just broke everything. **note when overriding Entity#onAddedToWorld() make sure to call super**.

**Comment by BobMowzie** [comment]
Thanks again. Will fix soon.
