### ISSUE TITLE
How To Stop Zombies And Skeletons From Attacking Barakoas

### ISSUE THREAD

**Issue by ShadowGeneral** [BobMowzie/MowziesMobs#151]
I have installed rough mobs 2, and it is working exceptionally well with Mowzies mobs, but due to the fact that the zombies and skeletons have such a large buff to health, they tend to really easily destroy barakoas. How can I prevent them from attacking barakoas?

**Comment by BobMowzie** [comment]
Hm, you can’t prevent them from fighting, but you CAN increase Barakoa health and attack power in the Mowzie’s Mobs configuration file.
