### ISSUE TITLE
Mod is looking for data field that doesn't exist

### ISSUE THREAD

**Issue by FallenEagle1** [BobMowzie/MowziesMobs#153]
Came across this issue when running the mods Enderman Evolution and Mowzie's Mobs. Talked to the dev of Enderman Evolution, and they suggested that the issue was that the mod is looking for a property that doesn't exist on the mob.

Forge: 2838
Mowzie: 1.5.4 and 1.5.3 (potentially others as well)
Enderman Evolution: 1.0.11-1.0.29 (potentially others as well)

Crash report: https://pastebin.com/Qr7yi18s

**Comment by BobMowzie** [comment]
This seems to be an issue with LLibrary, not Mowzie’s Mobs.

**Comment by FallenEagle1** [comment]
Fair. Do you want me to open one up over there then with the info? I wasn't seeing an issue that was the same problem.

**Comment by BobMowzie** [comment]
Sure, that’s probably the best approach until we know more.
