### ISSUE TITLE
ferrous_wroughtnaut becoming a Ticked Entity and crashing game

### ISSUE THREAD

**Issue by dd957** [BobMowzie/MowziesMobs#155]
This same mob has ruined two worlds of mine, leaving them unplayable.

Crash report here: [https://paste.dimdev.org/axomijigoz.mccrash](url)

**Comment by BobMowzie** [comment]
Compatibility issue with Foamfix. Will look into it. Try removing FF in the meantime.

**Comment by BobMowzie** [comment]
Alternatively, you can disable Wroughtnaut spawning in the configuration file.

**Comment by pau101** [comment]
This appears to be an issue in Camping, you can follow that issue for updates.
