### ISSUE TITLE
Foliaath spawns are too high!

### ISSUE THREAD

**Issue by Sunconure11** [BobMowzie/MowziesMobs#16]
While trying to investigate, and debug mob-related drops in FPS, I found something odd. It would seem the spawn rates for Foliaaths are too high. I am running a spongeforge server, and I did alter their spawn rates, but I'm pretty sure I set their spawns to be less, not more.

Using `/cofh killall folia` resulted in me removing 175 foliaaths.

I've also seen something similar to frostmaws to a lesser extent, in that they just... keep spawning out of control, albeit at a slower pace.

**Comment by BobMowzie** [comment]
I am content with the density of foliaath populations in jungle biomes. If you are not, you may change it.
Frostmaws are already using the minimum spawn density plus a check to make sure they can't spawn near each other. But perhaps they should spawn with world gen instead of monster spawning.

**Comment by Sunconure11** [comment]
I was able to fix the foliaath issue.
