### ISSUE TITLE
[request] add a toggle for sun's blessing or a keybinding to trigger it instead of on right click

### ISSUE THREAD

**Issue by majijn** [BobMowzie/MowziesMobs#165]

**Comment by BobMowzie** [comment]
You can toggle it off by holding any item. I'm keeping the ability constrained to the "interact" button.

**Comment by majijn** [comment]
unfortunately that actually causes problems with blocks that you interact with from the top face specifically, or any containers and stuff like that that you right click from above

i havent seen any time where suns blessing prevents you from interacting but it can cause mobs you didnt mean to hurt to take damage or even die, given how finnicky it is

**Comment by BobMowzie** [comment]
You can easily equip a block or item and interact with blocks and entities normally.

**Comment by majijn** [comment]
not if the blocks require an empty hand for the action im trying to do.

**Comment by BobMowzie** [comment]
Which action might that be?
