### ISSUE TITLE
Slight Server Lag

### ISSUE THREAD

**Issue by mxnmnm** [BobMowzie/MowziesMobs#167]
So I loaded up a new world and I was getting about 45-50 ms which is right on the border of being server lag.  Normally new worlds are 15-25 ms so I decided to use spark sampler to figure out the cause and apparently it has to do with the wroughtnaut's doing bad things.

here are the results so you can take a closer look: https://sparkprofiler.github.io/#QLJHwYjqHZ

**Comment by BobMowzie** [comment]
That breakdown is extremely helpful. I think I'll be able to alleviate this.

**Comment by BobMowzie** [comment]
The results you shared have disappeared. Can you please post them again?

**Comment by mxnmnm** [comment]
I haven't had any real issues since and idk how to recreate the situation that caused it because now my tps is what you would normally expect in a heavily modded environment. Sorry

**Comment by mxnmnm** [comment]
Let's hope the issue can't be recreated and if it can be I'll be sure to report the issue
