### ISSUE TITLE
Glottal should spawn when players are nearby

### ISSUE THREAD

**Issue by kihgy** [BobMowzie/MowziesMobs#171]
This is to reduce any lag from Glottals, since they can spawn underground and stay there. Naturally spawning condition for Glottals should be, they can only spawn around a certan block near the player, which allow them to only spawn when you go underground, and you would only encounter them when go into the underground anyway, and stop them fron spawning all over the place.

**Comment by BobMowzie** [comment]
You mean grottols? I have had no reports of them causing lag or “spawning all over the place”. Note that grottols are able to despawn naturally, and so they do not simply “stay there”.
Other underground mobs do not wait for players to come nearby to spawn. Why should grottols spawn any differently,
