### ISSUE TITLE
green blob bois spawning in base

### ISSUE THREAD

**Issue by Zeinoth** [BobMowzie/MowziesMobs#174]
my base is located in a magic forest from thaumcraft, and the green blobs are spawning there. I'm thinking this is unintended?

**Comment by BobMowzie** [comment]
Which part, them spawning in the forest or inside your base?

**Comment by Zeinoth** [comment]
spawning inside my base
![2019-09-27_18 14 32](https://user-images.githubusercontent.com/55437557/65753637-bca4de00-e152-11e9-95f4-5f6ee4517f01.png)

**Comment by Zeinoth** [comment]
sorry i worded that pretty badly

**Comment by BobMowzie** [comment]
There’s no direct way to prevent this. I can do a light-level check but that’s about it. Doesn’t look like it’ll help much.

**Comment by Golrith** [comment]
There is also an issue with crazy amount of Lanterns spawning. One suggestion that would help with the above, limit the lanterns to only spawn on grass blocks?

**Comment by BobMowzie** [comment]
The quantity of lantern spawns is unrelated and is actually a compatibility issue with a different mod.
Grass block spawns could work.
