### ISSUE TITLE
Mass Lantern Spawning in roofed forest (with RTG installed)

### ISSUE THREAD

**Issue by StyxSouls** [BobMowzie/MowziesMobs#175]
I decided to put the latest version of RTG 1.12.2-6.1.0.0-snapshot.1 in my pack. I do understand that RTG 1.12.2 is in beta at the moment and was just testing it out when I noticed that a few hundred entities were lagging my game. I found a roofed forest what looked like hundreds of lanterns everywhere. Using commands I killed them all but they quickly began to spawn back. When looking for potential solutions I came across another very similar report to a different mod here: https://github.com/maideniles/Maiden-s-Marvelous-Materials/issues/23

**Comment by Mario90900** [comment]
This was also happening to me as well, but they were mass-spawning in Thaumcraft's Magical Forest biome. If I left the game idling for long, it quickly accumulated well over 400 of them. I believe this is an issue with Mowsie's instead of any other mod.

**Comment by Golrith** [comment]
I've also encountered this issue. In a skyblock environment that is the roofed forest biome, the lanterns spawn like crazy. One of my modpack players reported over 3000 of them, and has setup a command block to keep killing them.

Also, setting their spawn rate to zero in the config has no effect.

I think the potential issue is that they are spawning as part of hostile mobs, but are actually passive mobs, so minecraft is trying to fill the hostile mob cap but it's never increasing.

**Comment by BobMowzie** [comment]
This issue only seems to happen in conjunction with other mods. By itself, Mowzie’s Mobs spawns lanterns normally and at the rate specified by the config file. It happens to be the case that lanterns are classified as “ambient” mobs like bats. As such, I must conclude that another mod is overriding ambient mob spawns and overloading worlds with lanterns.

The only thing I can do is change lanterns to hostile spawns, in which case they will reduce the number of other hostile mobs in roofed forests.

**Comment by BobMowzie** [comment]
What is RTG?

**Comment by StyxSouls** [comment]
Realistic Terrain Generation.

**Comment by Velocihater** [comment]
Same, I’ve been having this problem as well. They just blow up in the forest areas, and tried reducing the spawn rate for them. I didn’t know RTG had anything to do with spawn rates

**Comment by BobMowzie** [comment]
Fixed
