### ISSUE TITLE
Barakoa crashing clients

### ISSUE THREAD

**Issue by Pixel3000nerd** [BobMowzie/MowziesMobs#178]
I currently run a server with a modpack that me and some friends of mine gathered up. We ran multiple tests and made sure all the mods work correctly and are properly configured to avoid conflicts of any sorts.
However recently, we got surprised by a crash.
Whenever someone gets close to a Barakoa, enough for it to load on screen and such, it just crashes people's games. The server is still fine, but the client itself just gives up and exits the multiplayer game. And no matter how many times you rejoin, as long as the mob is in render distance range and ready to load, it still crashes.

According to VanillaFix's crash report, is a Ticking Entity exception with the mob. We tried various things to see if it was a specific structure or location that was causing it but no matter where the mob spawned, it just makes games give up. And the only way to get out of the constant crashing, is for someone else to tp them back to a safe location where is not near the mob. Is there a workaround or fix for this? Or is there another mod that could be causing it that you're aware of?

Here I include the crash report:
https://paste.dimdev.org/arozuwokis.mccrash

**Comment by ChukiStrike** [comment]
I have the same error :/

**Comment by BobMowzie** [comment]
Seems to be an interaction issue. You have two options. Disable Barako spawning (not Barakoana, it’s only the villager ones causing problems). Or go through one by one and figure out which other mod is causing problems. The crash mentions a problem with dye, so a mod that adds new dye or overhauls the dye system is likely the problem.
