### ISSUE TITLE
Overspawning of Lanterns from Mowzie Mobs in Forest Biomes 

### ISSUE THREAD

**Issue by V-Boy** [BobMowzie/MowziesMobs#184]
When you enter one of the roofed forests like Lothlorien from Tolkientweaks Mob Edition, Mowzie Mobs Lanterns spawn like crazy. Not sure if it's that mod or Mowzies.

![image](https://user-images.githubusercontent.com/40730042/76692065-280a3b80-661f-11ea-989d-0ab79dbb3ec7.png)
![image](https://user-images.githubusercontent.com/40730042/76692066-2a6c9580-661f-11ea-983d-bd72599fe580.png)

**Comment by BobMowzie** [comment]
My guess is the ambient mob cap for that biome is not set. Disable lantern spawning in config as temporary fix.
