### ISSUE TITLE
Ferrous Wroughtnaut

### ISSUE THREAD

**Issue by TH3Frag** [BobMowzie/MowziesMobs#185]
It seems that Ferrous Wroughtnaut is causing a lot of lag for me. The mod LagGoggles is showing it to be running around 200-300, not sure what the symbol means next to the number it shows, but it is in red. Once I kill him, the lag disappears until another one generates. 

Mod version: 1.5.4
Forge: 14.23.5.2847
Minecraft 1.12.2

**Comment by BobMowzie** [comment]
Should have been fixed.
