### ISSUE TITLE
Installed Mowzie w/o Llibrary

### ISSUE THREAD

**Issue by Melshia** [BobMowzie/MowziesMobs#188]
I accidentally started my MC server without adding Llibrary so none of the mobs from Mowzie spawned. I went back in and added the mod and restarted the server, but it still doesn't look any any of the new mobs spawned. Do I need to regenerate the world or is there something else that is wrong?

**Comment by BobMowzie** [comment]
Some of my mobs spawn with world generation. These will not appear in the chunks you have already generated. The other mobs will.

**Comment by BobMowzie** [comment]
You will have to regenerate the world, or just explore some new chunks.

**Comment by Melshia** [comment]
So I regenerated the world, but it doesn't seem to be working. I'm still not seeing any mobs outside the vanilla ones.

**Comment by BobMowzie** [comment]
What biome are you in? Certain mobs only spawn at dark light levels to prevent them from flooding player bases.

I’m also surprised the game let you start with MM installed and no LLibrary. It has always crashed when that happens before. This leads me to suspect that your installation might be incorrect. Are you able to spawn in the mobs in creative mode on the server?

**Comment by Melshia** [comment]
The biomes I checked were mountains, plains, swamp, and oak forest during day and night. I can spawn the mobs in creative mode.

**Comment by BobMowzie** [comment]
None of these biomes have any new content added by Mowzie's Mobs.

**Comment by Melshia** [comment]
Ah. My mistake. Thank you for helping. :)
