### ISSUE TITLE
Tagged Naga despawning

### ISSUE THREAD

**Issue by Ramses215181** [BobMowzie/MowziesMobs#189]
Tagged nagas despawn, despite any method used to prevent it (also tried using commands such as /summon mowziesmobs:naga ~ ~ ~ {PersistanceRequired:1b} this also didn't work), this does not happen with foliaath, grottols, lanterns and frostmaws, wich remain if tagged.

**Comment by BobMowzie** [comment]
Will fix. No idea what could be causing this, though...
