### ISSUE TITLE
Wroughtnaut pathfinding uses a large amount of cpu, even when not active

### ISSUE THREAD

**Issue by wolfw3** [BobMowzie/MowziesMobs#197]
running a debug profiler on my server, the wroughtnaut uses about 10% of server resources just for pathfinding, even though we haven't even seen it yet

**Comment by BobMowzie** [comment]
Oof. This is high priority.

**Comment by MechanosG** [comment]
I've noticed this too.  Bug testing a modpack, if I generate a new world then run lag goggles, Wroughtnauts are pretty much always at the top despite only 2 or 3 of them being listed.

**Comment by BobMowzie** [comment]
Does this still occur with ONLY Mowzie’s Mobs and lag goggles installed?

**Comment by MechanosG** [comment]
More or less.  Probably less.  Just for kicks, I created a clean 1.12.2 pack with only mowzies and lag goggles, then created a new world.  I was only able to find a single Ferrous Wroughtnaut after walking around for a few minutes (normally I have 3 or 4 in my list), but the single one stayed on top of the entity list, with a number 3-4 times bigger than most other mobs.  Not enough to cause lag on it's own or anything, but I'm on the surface on top of a random tree.
![2020-05-24_19 11 44](https://user-images.githubusercontent.com/4360512/82772220-62e4d880-9df3-11ea-814b-1f3c2341a676.png)

I then added AI Improvements, just to see if it would change anything.  Oddly things got universally worse?  Another Wroughtnaut showed up though.
![2020-05-24_19 24 23](https://user-images.githubusercontent.com/4360512/82772615-8a887080-9df4-11ea-888e-cd207bf73e12.png)

So one last thing to test, I removed AI Improvements, added Performant, then retested.  Other than a zombie that spotted me and started pathfinding towards me, fairly similar results to the first test.
![2020-05-24_19 29 41](https://user-images.githubusercontent.com/4360512/82772856-56617f80-9df5-11ea-9c28-5667da737254.png)

**Comment by BobMowzie** [comment]
Okay I think I found something bad I did in the Wroughtnaut's update method. I don't have lag goggles in my dev workspace and can't seem to add it, but I would bet that I just fixed this. Will wait for confirmation upon fix release.

**Comment by MechanosG** [comment]
Cool.  Btw, on the off chance your lag goggles problem happens to be the one that prevents starting MC giving you a strange error related to mixins, I'm told it's due to some mods not updating their mixin version.  You can sometimes get around it by renaming one of the conflicting mods so that it loads earlier or later.  When I was getting those screenshots earlier, I had to rename the 'performant' jar to '_performant', and it magically started loading properly.

**Comment by BobMowzie** [comment]
Could you please check with the latest patch and see if this issue has gone away?

**Comment by BobMowzie** [comment]
Should be fixed. Comment if not.
