### ISSUE TITLE
Crash from Naga poison projectiles.

### ISSUE THREAD

**Issue by EnderBro123** [BobMowzie/MowziesMobs#198]
[crash-2020-04-14_16.25.40-client.txt](https://github.com/BobMowzie/MowziesMobs/files/4478266/crash-2020-04-14_16.25.40-client.txt)

Mods included in the report file.

There's not much to really say besides to just get hit by its projectiles.

**Comment by BobMowzie** [comment]
No indication in this log that this crash was caused by a naga projectile. Issue is not replicatable in dev environment.
This could be caused by one of the many mods you have installed. I recommend removing them and readding them in batches until you identify which one causes this crash.
