### ISSUE TITLE
Crash upon generating a village in SMP

### ISSUE THREAD

**Issue by Sunconure11** [BobMowzie/MowziesMobs#2]
https://pastebin.com/p4WSiRgh

**Comment by Sunconure11** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1461

**Comment by pau101** [comment]
This is an issue in the 1.10.2 versions of sponge, you'll have to play in 1.11 in order for Mowzie's Mobs to be compatible.

**Comment by pau101** [comment]
A patch will be released soon.
