### ISSUE TITLE
Requesting Axe overhead slam change for NoDamI balance benefit.

### ISSUE THREAD

**Issue by Darkmega18** [BobMowzie/MowziesMobs#205]
G'day bob. There is a mod called NoDamI in 1.12.2 (and beyond), that removed damage immunity frames from players and mobs. But myself and possibly others have noticed that the overhead slam of the Axe of a thousand metals causes damage constantly in it's area of effect which results in total evaporation of enemy targets. :v 

I was wondering if you could rework the slam to be perhaps just two damage ticks? one for the immediate impact of the axe coming down, and one to represent the wave as it goes out possibly during the half life of the slam to apply great knockback so to provide balance? Although naturally you wouldn't notice this crazy damage and ideally I would fix it through NoDamI configurations if it was a possibility to nerf particular items directly from it, but unfortunately it's not something you can do with it right now. :< 

Most other things except for this one move aren't really impacted that negatively by NoDamI since honestly the sun laser is made actually decent by removal of I-frames which makes both yours and barako's version that much more scary. ;)

**Comment by BobMowzie** [comment]
Sorry, the proper fix for this is really involved. I'd recommend that you tune the axe's damage in the config file to get it to a more reasonable place.

**Comment by Darkmega18** [comment]
Yeah, a friend forked noDamI and allowed blacklisting items to cause i-frames. so it works now, it just can't be spammed, but with the area attack it's a trade off. and with your recent fix to allow it to deal damage with enchantments it'll be even better.
