### ISSUE TITLE
Frostmaw FPS drop after hit with proyectile.

### ISSUE THREAD

**Issue by xevilredx** [BobMowzie/MowziesMobs#206]
When I fight the frostmaw, It gets extremely laggy if he gets hit by an arrow. The lag doesn't stops after that. When I fight with no enemy nearby (That shoots arrows, they are the ones shooting and accidentally hitting the frostmaw, though the bug happens also if I shoot the arrow) It doesn't get lag.

**Comment by BobMowzie** [comment]
Tested myself, cannot recreate this issue.

Are you playing with any other mods installed? Are you using a relatively lower-end PC?
