### ISSUE TITLE
Crash when grottol spawnrate set to 0 with NetherEx mod

### ISSUE THREAD

**Issue by armenfeno** [BobMowzie/MowziesMobs#210]
We have a multiplayer server perfectly working, with an entire diamond economy system. It turns that Grottol diamond spawn breaks our economy too hard. Turning off Grottol spawn on cfg file, crashes our world with a ticking world crash :(
Is there a possibility to turn off diamond spawn on killing Grottol? Maybe exploring the .jar file, and making some modification on it... Please, we need help!
Thanks!

**Comment by BobMowzie** [comment]
There is no way to modify the drops currently. Loottables are coming in a future update.
You should be able to disable spawning. Can you please post the crash that you get?

**Comment by armenfeno** [comment]
[crash-2020-05-06_23.06.17-server.txt](https://github.com/BobMowzie/MowziesMobs/files/4594447/crash-2020-05-06_23.06.17-server.txt)
Here is, hope you can help us. Thanks for your quick response!

**Comment by BobMowzie** [comment]
And all you do to get this crash is set the grottol spawn rate to 0? Make sure you aren't setting it to a negative number.

It could very well be an interaction issue with another mod. If you really want to help me find the issue, you could remove other mods from the pack temporarily in batches until the crash stops, then add them back until the crash returns. This way, we can identify which other mod is causing the conflict.

**Comment by armenfeno** [comment]
ok, i will try to do that, thanks again!

**Comment by armenfeno** [comment]
Found it! With NetherEx-1.12.2-2.1.5.jar disabled, the map don't crashes any more, with Grottol spawn set to 0. Fortunately, the Nether is banned for a few more weeks. Hope this helps you.

**Comment by BobMowzie** [comment]
Great! That's really strange, though. I suppose I'll reach out to the developers.

**Comment by BobMowzie** [comment]
Not closed. The bug hasn't been fixed!
