### ISSUE TITLE
Ferrous Wroughtnaut falling forever, causing a lot of lag.

### ISSUE THREAD

**Issue by inb4mad** [BobMowzie/MowziesMobs#218]
Ferrous Wroughnauts dropped in the void won't take void damage, hence they will fall forever, progressive slowing down the chunk until its unplayable.

How to replicate:

1 - Go to the end.
2 - Place a Ferrous Wroughtnaut on a block above the void.
3 - Break that Block.
4 - Chunkload the area.
5 - Profit.

Note: I only started noticing the lag after a week of playing in the map, and only while the chunk was rendered. Issue happened not in the end but in a dimension called "dungeon_pockets" from dimensional doors.

Suggestions on how to fix it:

-Make Ferrous Wroughtnauts vulnerable to /kill @e.
-Make Ferrous Wroughtnauts despawn/die after falling a certain distance in the void.

Great mod btw man, despite the issues the wroughtnauts are by far my favorite pets :D

**Comment by BobMowzie** [comment]
This has been fixed for upcoming patch.
