### ISSUE TITLE
Lantern mob Spam in Forests

### ISSUE THREAD

**Issue by MechanosG** [BobMowzie/MowziesMobs#220]
Heya.  So I know this has been posted before (and closed).  But I wanted to share that I found the cause, at least for me.

I was debugging my modpack when another mod (Better Animals Plus) was having problems with mass spawning of certain fish mobs.  I suspected "In Control" and temp removed it.  The problem went away.  In Control can control mob spawning, so I re-added it then made a rule to specifically cap the mobs being spammed, to keep their numbers in check (I'm a bit worried this will come at some overhead, but this will allow me to keep using In Control).  To my surprise, another mod started spamming a different entity fish (Future MC).  So I made a rule for that mod too (which worked), but then I remembered the spam problem some people have with Mowzies Mobs and the lanterns.  So I went ahead and tested it..  sure enough, with In Control present, the lanterns spawn like crazy, but removing In Control, they go back to normal spawning behavior.

I have no idea why In Control is doing this, and I'm pretty sure I don't have any specific rules that could cause this.  But yeah, hopefully this will help someone.  Remove In Control or make a rule with it to cap the amount of lanterns, and problem fixed.

MC 1.12.2
mowziesmobs-1.5.4.jar
incontrol-1.12-3.9.16.jar

**Comment by BobMowzie** [comment]
Nah, not quite it. Good sleuthing, though.
Very simply, lanterns were set to ambient spawns but weren’t counted as ambient mobs. This meant they ignored spawn caps. A simple mistake on my part.

**Comment by MechanosG** [comment]
I see.  Why does it only happen when In Control was in effect then, out of curiosity?  Is In Control somehow making the spawn algorithm check the cap faster?  With my current setup I can still remove In Control (or remove In Control's rule file) and it'll stop the rapid spawning.  But adding it back, the lanterns go crazy again.

**Comment by BobMowzie** [comment]
It's very possible that's it. But I've seen the mass spawning happen with no mods installed.
