### ISSUE TITLE
Mobs Ignore Difficulty

### ISSUE THREAD

**Issue by thelapisfox** [BobMowzie/MowziesMobs#221]
I was in a test world (1.12.2 mod version 1.5.4) that is set to peaceful and the mobs in this mod spawn and attack regardless. I noticed this because I was being attacked by a Naga. While it couldn't damage me, it was still annoying to have this hostile mob in my face spitting green stuff at me. Hostile mobs should never spawn in peaceful.

**Comment by BobMowzie** [comment]
Already fixed for upcoming patch
