### ISSUE TITLE
fang knife isnt considered a weapon, but a tool, cannot be enchanted with weapon enchants

### ISSUE THREAD

**Issue by majijn** [BobMowzie/MowziesMobs#228]
also i think their attack speed and damage are swapped

**Comment by BobMowzie** [comment]
It does 3 damage on a normal hit, no? Not including poison.
On a backstab, that's 6. Plus 3 poison damage that goes through armor. That's better than a diamond sword.
Attack speed should be 5. Switching this with damage would make the dagger way too strong.

**Comment by majijn** [comment]
ah, then 5.5 speed is too high. youd want it lower even if you dont bump up the base attack value due to its current dps and max dps

 id like to add that the knife is very cool conceptually and im enjoying the update so far :)
is there anything the knife is especially proficient at mining by the way?

**Comment by BobMowzie** [comment]
Thanks!
Nah. What did you have in mind? Plants?

**Comment by majijn** [comment]
i didnt really have any blocks in mind i was asking because it could be enchanted with efficiency!

**Comment by BobMowzie** [comment]
Gotcha. No longer!

**Comment by majijn** [comment]
https://github.com/MysticMods/MysticalWorld/issues/114 just managed to find this , its relevant to your knife's attack speed/damage

**Comment by BobMowzie** [comment]
No I fixed it already. I literally just typed the wrong number by mistake.
