### ISSUE TITLE
[1.12.2] Special axe attacks don't prevent the axe from being rendered on the side of the screen

### ISSUE THREAD

**Issue by the-realest-stu** [BobMowzie/MowziesMobs#23]
When doing a sweep attack or ground slam with the Axe of a Thousand Metals, the axe will be rendered in the usual spot on the side of the screen as well as in front of the player for the special attack animation.

Mod versions:
- Mowsies Mobs 1.4.1 for 1.12.2
- LLibrary 1.7.12
- Forge 14.23.4.2707

I also have Optifine installed, though I haven't tested to see if removing it changes anything.

**Comment by BobMowzie** [comment]
Not a bug. I'm simply unable to stop the original axe from rendering.
Will keep searching for a fix.

**Comment by the-realest-stu** [comment]
Hm... This might be a strange way to go about this, but how about using model overrides, like vanilla bows?

Something like this:
```java
this.addPropertyOverride(new ResourceLocation("pulling"), new IItemPropertyGetter() {
    @SideOnly(Side.CLIENT)
    public float apply(ItemStack stack, @Nullable World world, @Nullable EntityLivingBase entity) {
        return <boolean expression for whether the axe is being swung> ? 1F : 0F;
    }
});
```
And then use an empty model when that's 1.

**Comment by BobMowzie** [comment]
Doesn't work, I'm afraid.
Not sure if the approach is wrong or I'm just not implementing it right...
