### ISSUE TITLE
server side crash

### ISSUE THREAD

**Issue by Mofo50C** [BobMowzie/MowziesMobs#230]
i got this crash while flying around the nether for some reason but the crash report says something about your mod and spartan weaponry ill report it to them as well

[crash-2020-06-07_21.50.16-server.txt](https://github.com/BobMowzie/MowziesMobs/files/4742946/crash-2020-06-07_21.50.16-server.txt)

im on the latest version 1.12.2 - 1.5.5

**Comment by BobMowzie** [comment]
Duplicate #229
