### ISSUE TITLE
barakoas spawning in the nether

### ISSUE THREAD

**Issue by Mofo50C** [BobMowzie/MowziesMobs#231]
the barakoa village and the mobs are literally spawning in the nether. i dont know how this is possible the dimension whitelist of mowzie's mobs are all 0 so they should spawn in the overworld.

im on latest 1.12.2 version

**Comment by BobMowzie** [comment]
I just spent 10 minutes flying around the nether looking for them and didn't see any. Are you using any other mods?

**Comment by Mofo50C** [comment]
sorry for the late reply ye for some reason it just stopped doing it now i reset the modpack from curseforge launcher like deleted the worlds and stuff and started over in a new instance and it didnt do it. Interestingly they were only spawning in the netherex biomes of the nether.

**Comment by BobMowzie** [comment]
Well, they can only generate in biomes tagged as “savannas”. NetherEx must tag some of its biomes as savannas for some reason. You can temporarily fix this in the config by adding !NETHER to the biome type list.
I found the source of the problem and will publish the fix soon.

**Comment by Mofo50C** [comment]
ah ok so it is an actual issue i just thought it was an issue with too many mods and stuff in the modpack ok thank you.
