### ISSUE TITLE
Loot level event crash

### ISSUE THREAD

**Issue by DoYouLikeToEatBee** [BobMowzie/MowziesMobs#232]
[crash-2020-06-07_23.57.54-server.txt](https://github.com/BobMowzie/MowziesMobs/files/4743780/crash-2020-06-07_23.57.54-server.txt)

**Comment by BobMowzie** [comment]
This is the Switchbow crash again. Please report this to the Switchbow developers.

**Comment by DoYouLikeToEatBee** [comment]
What specifically is the issue in Switchbow that is causing it to crash the game? Asking so I can let the developer know. He's fairly inactive though and almost never responds to messages.

**Comment by DoYouLikeToEatBee** [comment]
If there are only specific parts of his mod that are conflicting with Mowzies Mobs or a specific thing in Mowzies Mobs that is causing it to crash due to switchbow, please let me know. I'm trying to develop a good personal modpack for my server for my friends and I and I need to get it working ASAP. So if I can just cut out or disable parts of the mods (eg. specific items in the mod that when used crash the game), please let me know which parts I should disable. I'm going to use both mods since they are necessary for the server balancing. If it's just use of the blowdart that triggers the crash, I can disable that until the Switchbow developer pushes out a fix for it.

**Comment by BobMowzie** [comment]
Okay wait, I've made a mistake. This appears to be on me.

**Comment by BobMowzie** [comment]
Alright, I think I fixed it.
