### ISSUE TITLE
Packets

### ISSUE THREAD

**Issue by DemonfangArun** [BobMowzie/MowziesMobs#237]
v. 1.5.6
Forge x.2854 (1.12)

While looking into another issue with redshark I noticed a bunch of these being sent to the server from the client. At one byte it's certainly not hampering anything but since I'm already looking at things figured why not mention it.

Recieved a packet from mowziesmobs. It has 1 bytes of data. Type is class com.bobmowzie.mowziesmobs.server.message.mouse.MessageLeftMouseUp.

These are sent at regular intervals so they don't seem to correspond to any actual action (I'm just sitting with the client in background while looking at stuff).

**Comment by BobMowzie** [comment]
They’re sent when the player releases the left mouse button. Are they being sent incorrectly?

**Comment by DemonfangArun** [comment]
They're being sent constantly at regular intervals when the window is not in focus, many more times per second than I am capable of doing without cheaty scripts.

**Comment by BobMowzie** [comment]
Good to know. Thanks.
