### ISSUE TITLE
Server starting issue

### ISSUE THREAD

**Issue by TMVega** [BobMowzie/MowziesMobs#239]

**Comment by BobMowzie** [comment]
What’s the message?

**Comment by TMVega** [comment]
Sorry, i'm not used to this site so i kinda screwed up this post. I made a modpack with this mod but when starting the server at one point the console loops with this message:
"[Server] Server thread/INFO [STDOUT]: [com.bobmowzie.mowziesmobs.server.spawn.SpawnHandler:getBiomesFromConfig:164]: Reflection failed".
I then found out the server eventually starts anyway because it ignores this issue but it takes a really long time

**Comment by TMVega** [comment]
The problem was that i wasn't using the latest version of the mod (again). Sorry for bothering you.

**Comment by BobMowzie** [comment]
Oh, just update to the new patch - 1.5.6

**Comment by BobMowzie** [comment]
Ah, you figured it out! No problem! Enjoy!
