### ISSUE TITLE
Mobs no Spawn with eggs

### ISSUE THREAD

**Issue by zeven001** [BobMowzie/MowziesMobs#241]
Create a server with the mod and its latest version 1.5.6 to create custom dungeons, I built the dungeon to decorate it etc but when putting any egg from the mobs nothing came out and it was changed to a blank egg that it said to generate -
nothing else i can do? the server depends a lot on this mod since it is essential!

**Comment by BobMowzie** [comment]
I suspect this is an issue with Forge versions. Use the “recommended” build, not the “latest” one.
