### ISSUE TITLE
Mowzie's Mobs Potion Effects registering under Bewitchment ModID

### ISSUE THREAD

**Issue by anabsolutesloth** [BobMowzie/MowziesMobs#243]
Snippet from a Tellme dump:
| mowziesmobs:long_poison_resist        |  74 | PotionEffect:{Potion:[reg:bewitchment:poison_resist,name:potion.poisonResist,isBad:false,isBeneficial:false],amplifier:0,duration:9600,isSplashPotion:false,isAmbient:false}
| mowziesmobs:poison_resist             |  73 | PotionEffect:{Potion:[reg:bewitchment:poison_resist,name:potion.poisonResist,isBad:false,isBeneficial:false],amplifier:0,duration:3600,isSplashPotion:false,isAmbient:false}

Custom Modpack, Modlist: https://hastebin.com/ekolimapup

![image](https://user-images.githubusercontent.com/63694982/87208057-69a3ae00-c2c2-11ea-8653-518a104d131e.png)

**Comment by pau101** [comment]
Thanks for reporting!

You should report this to Bewitchment as well, as they should be specifying themselves `after:mowziesmobs` along with every other mod they provide integration for. We will however make MM more defensive against cross-mod classloading to resolve this issue, but until Bewitchment is changed there may be log spam about "Potentially Dangerous alternative prefix."

**Comment by Sunconure11** [comment]
Can I get away with not specifying the version, in something like this?

`	public static final String DEPENDENCIES = "required-after:baubles;required-after:patchouli;after:dynamictrees@[1.12.2-0.9.1e,);after:thaumcraft@[6.1.BETA26,);after:mowziesmobs";`

**Comment by Sunconure11** [comment]
Requesting some more help from @pau101 to fix it on my end.

**Comment by Sunconure11** [comment]
Gonna post in here, but after attempting to stumble around with a debugger, I have no clue what is going on here. I tried another solution someone suggested to me, which is to register this stuff under the modid for your stuff, but it did not do anything, in this case. I managed to fix load order, but that's about it.

If anyone is willing to submit a PR or is able to shed new light, let me know.
