### ISSUE TITLE
Some mobs tend to fall into the ground after attacks

### ISSUE THREAD

**Issue by DWX12** [BobMowzie/MowziesMobs#25]
This usually happens from Frostmaw attacks and usually can be experienced when it attacks the Wrought knight and the Sun Chief. The Knight takes no damage until a player interacts with it and the Sun Chief heals hp, so they don't die from suffocation. No blocks break either ( or at least with mob griefing turned off).

**Comment by BobMowzie** [comment]
I am not observing this issue.
Do you have any mods installed? How did you get the frostmaw to attack Barako or a wroughtnaut?

**Comment by DWX12** [comment]
Similar to the issue with the frostmaw attacking nothing, this was during that current test session. All my observations occurred while I was in creative. I believe, for some of the times, that I would hit the frostmaw to wake it up, which could have something to do with its targeting. If I remember, the frostmaw tends to go after most mobs when provoked (even if they hadn't attacked it).

From what I remember, place a frostmaw, either chief or knight, hit frostmaw, frostmaw should target either that you put down and will attack them, which will more or less just push them around. You might even try placing them around a one block edge, which might also result in the above behavior.

When I have the time I'll do more testing. Thanks again
