### ISSUE TITLE
Wrong parameters for indirect damage types.

### ISSUE THREAD

**Issue by Quarris** [BobMowzie/MowziesMobs#250]
https://github.com/BobMowzie/MowziesMobs/blob/b89b2e3967084a660c9b72e4337233e3d07e48d2/src/main/java/com/bobmowzie/mowziesmobs/server/entity/effects/EntityPoisonBall.java#L70

Hey, I'm making a mod which relies on damage types for projectiles to reflect the immediate and true sources correctly.
The Indirect Damages have 2 sources, the immediate source and the true source.
the call `DamageSource.causeIndirectMagicDamage(immediateSource, trueSource)` has the immediate source (i.e. the projectile) as the first parameter and the true source (i.e. the caster) as the second parameter, but in this case you have the immediate source set as the caster and the true source set as null.

Would it be possible to update this (and possibly other damage sources if exist)?

Thanks in advance!

**Comment by BobMowzie** [comment]
My mistake! Hope the fix help.s
