### ISSUE TITLE
Barakoa spawning issues

### ISSUE THREAD

**Issue by Mofo50C** [BobMowzie/MowziesMobs#252]
Version: 1.5.6-1.12.2
Description: barakoas and their village are spawning everywhere idk if its a compatibility issue with Biomes O Plenty but theyre spawning in biomes where they shouldn't.

**Comment by BobMowzie** [comment]
Check your config file and make sure the biome settings are correct.
It is also possible that Biomes O Plenty tagged things as savannas a bit too generously. You’ll have to blacklist or whitelist biomes in my config to get the desired spawning behavior.
