### ISSUE TITLE
Apply mob effects only when the target is actually hit

### ISSUE THREAD

**Issue by Quarris** [BobMowzie/MowziesMobs#253]
I have made a PR #251 which takes account of the result of the attackEntity method, and apply certain effects only when that method returns true, i.e. the entity has been attacked. This allows other mods to cancel the attack if they want to and not have those effects applied to them. This would partially solve the issue request #249 as other mods will be able to cancel the specific damage types caused by the effects.

**Comment by BobMowzie** [comment]
Thanks! Will merge soon.

**Comment by Quarris** [comment]
Poke. I made a new PR #255 which addresses an issue about freezing using Ice Breath
