### ISSUE TITLE
[Suggestion] Foliaath's Spawning in Jungle Temples

### ISSUE THREAD

**Issue by 000TheEldritchOne000** [BobMowzie/MowziesMobs#254]
I may say I haven't scene a Foliaath spawn in a jungle temple at all. So I think it would be cool to see them spawn in them. I just want to clarify that not lot will spawn in these. Probably 3 or less would. Foliaath's that have grown in them now wait patiently for a curious animal or explorer like yourself to wonder in unprepared thinking it will be the same arrow trap and puzzle

**Comment by BobMowzie** [comment]
I'd like to add a different, new mob to jungle temples to make them even more distinct from the surrounding area. You can easily allow foliaaths to spawn in them though by adding regular/mossy cobblestone to their allowed spawn blocks in the config.

**Comment by 000TheEldritchOne000** [comment]
Lol I am surprised this is in gmail. But I didn't want to suggest a new mob
to say because I mainly did not want to say a bad idea lol. I also did not
want to fill up the discord chat or any chat with like oh I got an idea add
this you know. But just so I can keep in mind. Where might I post a
suggestion

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by BobMowzie** [comment]
Please post your mob ideas on the Curseforge or MC Forum pages!

**Comment by 000TheEldritchOne000** [comment]
Alright! Sadly I cannot attach the art I made of this swamp bug creature
which would make it look much better

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by BobMowzie** [comment]
You can upload your art to the Curseforge page, not here.

**Comment by 000TheEldritchOne000** [comment]
Ah okay. Thanks!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
