### ISSUE TITLE
Barako's projectile crashes client

### ISSUE THREAD

**Issue by upanikbr** [BobMowzie/MowziesMobs#259]
I have a multiplayer server, when someone fight with barako, his projectile crashes the client of who is nearby him.

**Comment by BobMowzie** [comment]
I need to see the crash report.

**Comment by upanikbr** [comment]
[crash-2020-08-19_17.35.53-client.txt](https://github.com/BobMowzie/MowziesMobs/files/5099235/crash-2020-08-19_17.35.53-client.txt)

**Comment by upanikbr** [comment]
I can confirm that on the same modpack, on the single player, Barako spawning the Barakoas is working fine. This crash only happens on the server.

**Comment by BobMowzie** [comment]
Issue is not present in my dev space. It must be an interaction issue.
If you are able to, you can help me identify the problem by disabling mods in chunks until the crash stops, then adding them back until the crash returns, narrowing down which other mod might be the problem.

**Comment by DipstickGrim** [comment]
Yeah I'm suffering from a similar situation here's the crash report

[crash-2020-09-02_15.29.50-server.txt](https://github.com/BobMowzie/MowziesMobs/files/5164945/crash-2020-09-02_15.29.50-server.txt)

**Comment by BobMowzie** [comment]
That appears to be a different crash. Try updating Java.

**Comment by DipstickGrim** [comment]
Just did and it says it's up to date.

**Comment by SandwichHorror** [comment]
I also received the ticking Entity crash for sun projectile dealing Mixed damage. Is the known solution to update Java?

**Comment by pau101** [comment]
No, this issue is now fixed in latest version: [Mowzie's Mobs 1.5.8](https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs/files/3048685)

**Comment by SandwichHorror** [comment]
I received this crash in 1.5.8 :frowning_face:

**Comment by SandwichHorror** [comment]
[crash-2020-09-28_02.16.11-server.txt](https://github.com/BobMowzie/MowziesMobs/files/5292741/crash-2020-09-28_02.16.11-server.txt)

**Comment by BobMowzie** [comment]
There was a hotfix for 1.5.8 that didn’t increment the version number. Just redownload the mod.

**Comment by SandwichHorror** [comment]
Got it, thank you.
