### ISSUE TITLE
Wroughtnaut, Barako, and Foliaath position desync

### ISSUE THREAD

**Issue by Chumbanotz** [BobMowzie/MowziesMobs#262]
The Ferrous Wroughtnaut (when it's not active), the Barako, and the Foliaath can have some serious issues with their position in the world when their motion or position is forcibly set. For the Barako it is much easier to cause. I was able to cause it for both by having them fight mobs that set their target's motion and ignore the knockback resistance attribute. I suspect the issue starts with these two lines.
https://github.com/BobMowzie/MowziesMobs/blob/fde5f3c553fb592b32661322bef0c6ec2509e2fb/src/main/java/com/bobmowzie/mowziesmobs/server/entity/wroughtnaut/EntityWroughtnaut.java#L251
https://github.com/BobMowzie/MowziesMobs/blob/fde5f3c553fb592b32661322bef0c6ec2509e2fb/src/main/java/com/bobmowzie/mowziesmobs/server/entity/barakoa/EntityBarako.java#L265
https://github.com/BobMowzie/MowziesMobs/blob/fde5f3c553fb592b32661322bef0c6ec2509e2fb/src/main/java/com/bobmowzie/mowziesmobs/server/entity/foliaath/EntityFoliaath.java#L113
For both mobs, the posX and posZ are set every tick to the previous value of each which I think causes these issues. Instead, setting the motionX and motionZ to zero should fix these desync issues while also preventing them from being moved. Notice in the second picture, the Barako's hitbox appears where it's supposed to, but the Mutant Enderman can walk through it and can't hit it.
![2020-08-20_16 42 33](https://user-images.githubusercontent.com/53630561/90935149-a3db9180-e3d0-11ea-8f72-c5703c4c28a1.png)
![2020-08-21_17 02 10](https://user-images.githubusercontent.com/53630561/90935241-cec5e580-e3d0-11ea-9757-864a6fe8b517.png)
![2020-08-21_17 03 15](https://user-images.githubusercontent.com/53630561/90935247-d2f20300-e3d0-11ea-99b1-ef7ce7c3d948.png)

**Comment by Chumbanotz** [comment]
Thank you for addressing this, but I think that the lines `posX = prevPosX` and `posZ = prevPosZ` need to be removed as well for each, as I was able to recreate the position issue with version 1.5.8.
![2020-09-02_12 14 24](https://user-images.githubusercontent.com/53630561/92009262-3f94c800-ed16-11ea-9b55-2ab0e4b243d7.png)

**Comment by BobMowzie** [comment]
Published a hotfix for 1.5.8! Sorry about all the confusion surrounding this issue!
