### ISSUE TITLE
[Suggestion] Choosing the Direction Barako faces when spawned in Creative

### ISSUE THREAD

**Issue by aarter180** [BobMowzie/MowziesMobs#264]
As of now, Barako the Sun Chief spawns facing a seemingly random direction when using a spawn egg and afterwards cannot change orientation.  The only way around this is replacing it with another Barako until it faces the right way, which can be tedious if you are unlucky.  An ideal change I think would be to have Barako face whichever cardinal direction the player is closest to facing when using it's spawn egg since he always faces exactly North, South, West, or East.

**Comment by pau101** [comment]
We'll implement this in the 1.14+ versions. For the time being you can use the summon command to create a Barako facing the desired direction:

North: `/summon mowziesmobs:barako ~ ~ ~ {Rotation:[-180.0f]}`
South: `/summon mowziesmobs:barako ~ ~ ~ {Rotation:[0.0f]}`
East: `/summon mowziesmobs:barako ~ ~ ~ {Rotation:[-90.0f]}`
West: `/summon mowziesmobs:barako ~ ~ ~ {Rotation:[90.0f]}`
