### ISSUE TITLE
Frostmaw frozen by Crystal

### ISSUE THREAD

**Issue by Superstrdier06** [BobMowzie/MowziesMobs#267]
If you freeze Frostmaw with his own Crystal, and unfreezes, then he will be stuck permanently as a statue of sorts and will be unable to do anything. He still makes idle noises as if no one was there.

**Comment by BobMowzie** [comment]
Update to the latest version of the mod. This has been fixed, and the frostmaw is now immune to ice magic by default.

**Comment by Superstrdier06** [comment]
Also cool, thanks!
