### ISSUE TITLE
Idea: Frostmaw Detects player using sound

### ISSUE THREAD

**Issue by AtomicWaffle14** [BobMowzie/MowziesMobs#268]
Currently the only way to sneak up on the Frostmaw to steal it's ice crystal is with an Invisibility potion, which feels silly given that its eyes are closed. Can you try to make an option so it is sound based? That way if you sneak or use another mod's feature to make yourself quiet, you can at least get a bit closer before it detects you.

**Comment by BobMowzie** [comment]
The invisibility potion is temporary until the mob that gives the real method is added.

But I stand by the invis potion. For gameplay reasons, players know that the invisibility potion stops mobs from targeting you and using this mechanic to sneak up on the frostmaw is consistent with what players know about invisibility potions. It also gates obtaining the crystal behind brewing, making the item only available late-game.
Besides, it’s perfectly plausible that the invisibility potion also masks the user’s smell. If the frostmaw can’t smell you, it won’t wake up.

**Comment by V-Boy** [comment]
Perhaps a sound method could come out when 1.17 comes out, since sound mechanics are being implemented there
