### ISSUE TITLE
Naga spawn error

### ISSUE THREAD

**Issue by disastercube** [BobMowzie/MowziesMobs#269]
I'm not entirely sure if this is this mods fault but I think this mod has the same "Naga's id spawn" as from 
twilight forest "Naga boss" and makes the boss spawn in the overworld instead of the MowziesMobs Naga.
![2020-10-04_17 55 16](https://user-images.githubusercontent.com/62697421/95663555-6da0cf80-0b40-11eb-832d-e550eb983ed5.png)

**Comment by BobMowzie** [comment]
That’s strange. I don’t think it’s possible for Minecraft to confuse two mobs just because they have the same name; mob registry IDs are stored with the mod name too, like “mowziesmobs:naga”. I’m also doubtful of this since my naga mobs don’t spawn in the environment shown in that screenshot.

Do you have any other mods installed? Could you please provide a list? Are you able to find Mowzie’s Mobs nagas in the overworld? What happens if you remove Mowzie’s Mobs?

**Comment by disastercube** [comment]
So, I think I found the issue and it might be either OTG or some world generation mod related with OTG (like BiomeBundle).
Specific biomes have specific entities spawns and one of such is **_EntityNaga from Mowzie’s_** and _**EntityTFNaga from TwilightForest**_. For some reason biome/biomes call for EntityTFNaga instead of EntityNaga and by so spawning the boss instead of Mowzie's Naga. Is there a way to fix this from your end (renaming it and such) ?

**Comment by BobMowzie** [comment]
They’re already named differently! Check your configuration files.

**Comment by pau101** [comment]
Where does your suspicion of Twilight Forest come from? I don't see any indication of error from that screenshot, there should be a Mowzie's Naga near by.

**Comment by disastercube** [comment]
Its simple. To track it I created a OTG world and went into a biome where Mowzie's Naga spawn (Stone Beaches), you can easily locate it with **_"Nature's compass mod"_**. There I used a command **"/otg biome -m"** that allows you to see registered mobs.

_**As you can see "EntityTFNaga" is one of them but not EntityNaga:**_
![1](https://user-images.githubusercontent.com/62697421/95672741-a32ad480-0ba3-11eb-866b-c4b443e75c4f.png)


Then to get confirmation I removed **Twilight Forest** and went back to check, and **"EntityTFNaga"** got replaced with **"EntityNaga"** **but not vice versa**. After removing Twilight the entities switched to normal, but re-adding Twilight didn't replace entities to its original broken state (meaning removing Twilight and re-adding it kinda self fixed it) :

![2](https://user-images.githubusercontent.com/62697421/95672746-aaea7900-0ba3-11eb-9ed3-e8f4415c2891.png)

But doing so it removed other EntityTF as well such as squirrels and dears (this added to the nature aspect but it could also been seen as issue, depends from a person). Of course the last one Mowzie's mobs have no influence on, I just wanted to point it out.

**Comment by pau101** [comment]
Thank you for that information. I looked into issue and found OTG has already fixed it in dev: https://github.com/PG85/OpenTerrainGenerator/commit/044e3e49f56a9fc91fb60cc3089594337249969c
