### ISSUE TITLE
Tribes structures and/or mobs causing issues for Waterfall proxy

### ISSUE THREAD

**Issue by notspaceuwu** [BobMowzie/MowziesMobs#271]
Ohayo, i'm reporting an active issue with Mowzies Mobs and the Waterfall proxy.
Whenever a player comes into contact with the structures for the tribes persons, it will hard crash them. This essentially chunk-bans them.

We use a proxy so we can link modded servers together into one big network. So you can see that we are unable to remove the proxy service. (we also tried using Waterfall on a test server with similar results)

Anyway, if you're interested in the juicy details, you can approach the tribes structure before it kicks you for the error message that there is no fallback server, basically meaning the server you were on went down- but it didn't.
Below is a log providing the error message on the proxy.
https://controlc.com/06d35d62

Now, yes, I understand that bungeecord does not support modded NBT types, I am also aware of the disable_entity_metadata_rewrite option. This, however, breaks the use of End Portals and doesn't allow dimensions to work correctly.

AFAIK, this only occurs with the tribes area. Not any other mob- including the wrought and Manticores/Wyverns etc from another mod called MoCreatures.

Is there any possible way we can work together to get this fixed?

**Comment by BobMowzie** [comment]
Did you report this to waterfall proxy as well?

**Comment by pau101** [comment]
It looks like Waterfall/BungeeCord does not support a standard usage of the game's entity sync which mods utilize. There is no error on our part, just a limitation on bungee.

**Comment by notspaceuwu** [comment]
Damn fast response.

@BobMowzie I have seen others report this to Waterfall, which they recommend the usage of `disable_entity_metadata_rewrite` - as mentioned which also reported breaks End Portals and so on.

@pau101 I am aware of the limitation on bungee, I mainly made this issue to see if there is anyway to work around it, as other mods don't seem to have any other issues (this excludes the Wroughtnaut and Foliaaths weirdly enough)

**Comment by pau101** [comment]
The limitation is unrelated to boss bars, nbt types, and the class you last referenced. The limitation is mods often register custom entity metadata data types (integer, string, boolean, etc) and bungee packet rewriting is not aware of those types and unfortunately provides no mechanism to configure support for them. The type we register is to represent the Barakoa trade.

It is not necessary that we use a custom metadata types for some of our entities, however it was the natural implementation at the time and given 1.12 is no longer being supported it will be kept as is.

It is possible Waterfall could introduce a way to configure custom meta types beyond its current simple outright disabling, but other than that you're out of luck sadly for 1.12.

**Comment by notspaceuwu** [comment]
Thank you for the message back; I appreciate it in such detail.

I’ll forward this to Waterfall and see if there is some form of way to do
this.

You are welcome to close this issue ^
