### ISSUE TITLE
freeze_blacklist config option Questions

### ISSUE THREAD

**Issue by Daejangnamu** [BobMowzie/MowziesMobs#273]
I am using other mod [ice and fire, twilightforest]

How do I write to blacklist all monsters?
I tried like below but it doesn't work.

```
general {
    # Add a mob's full name here to prevent it from being frozen or taking damage from ice magic.
    S:freeze_blacklist <
        iceandfire:*
	twilightforest:*
     >
}
```

**Comment by BobMowzie** [comment]
Unfortunately the config is not set up for functionality like that. You’d have to add every mob name separately.
You really don’t want the ice crystal to work on ANY of those mod’s mobs?

**Comment by Daejangnamu** [comment]
> 불행히도 구성은 이와 같은 기능을 위해 설정되지 않았습니다. 모든 몹 이름을 별도로 추가해야합니다.
> 그 모드의 몹들에게 얼음 결정이 작동하는 것을 정말로 원하지 않습니까? 얼음 결정을 제거하는 것이 더 나을 수도 있습니다.

Thank you
