### ISSUE TITLE
Mobs don't spawn in survival

### ISSUE THREAD

**Issue by Glennius05** [BobMowzie/MowziesMobs#276]
Idk why the mobs don't spawn in survival, but in creative when I use the spawn eggs, they appear, this problem is in the latest versions for 1.12.2(1.5.8 and 1.5.7, I just proved with those), I think it's because I have other mods. Do u have any solution for this?

Just to clarify, I remember that I used this mod before with other mods, and I didn't have any problem, the mobs appeared in survival.
Thx in advance!
EDIT:
This is my list of mods that (I think) don't allow Mowzie's mobs to spawn. However, this list hasn't been completed yet because I'll upload more mods. 
![image](https://user-images.githubusercontent.com/74890656/100168956-57e92e80-2e90-11eb-82bf-b38864bf04c4.png)

Just in case, I'm not playing in a server. I say this because I found that other players had the same problem that I have but the solution was to update SpongeForge.

**Comment by BobMowzie** [comment]
I’d need to know what other mods you’re using. Also make sure you’re looking in the right places and after a night has passed.

**Comment by Glennius05** [comment]
> I’d need to know what other mods you’re using. Also, make sure you’re looking in the right places and after a night has passed.

Thx for your help. I edited my comment. I searched everywhere and a night passed, also. Mowzies mod doesn't appear because I put it in another file, just to know that it doesn't work with the other mods.

**Comment by BobMowzie** [comment]
Oh, Custom Mob Spawner overhauls the entire spawn system. You have to add my mobs to its config to get them to spawn.
The other mods listed there are fine.
