### ISSUE TITLE
Crash With Galacticraft

### ISSUE THREAD

**Issue by kenijey** [BobMowzie/MowziesMobs#30]
[crash-2018-06-07_15.48.18-client.txt](https://github.com/BobMowzie/MowziesMobs/files/2080511/crash-2018-06-07_15.48.18-client.txt)
@micdoodle8

**Comment by Mike-U5** [comment]
I'm using Galacticraft and not getting a crash. What exactly were you doing when this crash happened?

**Comment by kenijey** [comment]
nothing... playing in overworld

**Comment by BobMowzie** [comment]
Resolved
