### ISSUE TITLE
Mobs not recognized by other mods

### ISSUE THREAD

**Issue by roccscout** [BobMowzie/MowziesMobs#307]
Hi there,

Mowzies Mobs are not recognized by a few different mods, including ActualMusic 5.

Would this have something to do with how they are categorized or coded? Is there any way for them to register more similarly to Vanilla mobs?

**Comment by BobMowzie** [comment]
My mobs are registered, categorized, and coded just like any other mobs. I don’t know much about ActualMusic, so a bit more info might help. What exactly were you trying to do, and what behavior did you observe instead?

**Comment by BobMowzie** [comment]
This seems more like an issue with ActualMusic.
