### ISSUE TITLE
 [com.bobmowzie.mowziesmobs.server.spawn.SpawnHandler:getBiomesFromConfig:164]: Reflection failed

### ISSUE THREAD

**Issue by Strijder513** [BobMowzie/MowziesMobs#310]
Greetings, i am fairly new to reporting errors on a minecraft server as such so i may not get it done correctly, but when i drag the mods in and run the server (the server runs) but i get this spammed through the console. 

"[05:18:41] [Server thread/INFO] [STDOUT]: [com.bobmowzie.mowziesmobs.server.spawn.SpawnHandler:getBiomesFromConfig:164]: Reflection failed
"
I think it's because i have to many mods and they're not compatible but that'll mean the server wouldn't start up at all.

i also get this problem

" [com.bobmowzie.mowziesmobs.server.spawn.SpawnHandler:getBiomesFromConfig:183]: Mowzie's Mobs config warning: No biome with name 'Roofed Forest'. Unable to whitelist."

any help would be appreciated because I'm at a lost cause here. If anything else needs to be provided just let me know 

e.g (what mods i have)

**Comment by Strijder513** [comment]
De een en alleen gangster#0733

in case you need to shoot my a dm

**Comment by BobMowzie** [comment]
What version of the mod are you using?

**Comment by Strijder513** [comment]
version 1.5.5
minecraft version 1.12.2

**Comment by BobMowzie** [comment]
You are using an outdated version of the mod. Please update to 1.5.8: https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs/files/3048685
