### ISSUE TITLE
Frostmaw not spawning with ice crystal from /summon mowziesmobs:frostmaw

### ISSUE THREAD

**Issue by zanderjome** [BobMowzie/MowziesMobs#312]
title pretty much; just spawns w/out an ice crystal in his hands

**Comment by BobMowzie** [comment]
Oh uh, why’d you close this? Did the issue stop?

**Comment by zanderjome** [comment]
because i just ended up using a spawn egg lol :) i think it is still an issue but didnt want to take up your time. thanks for the effort

**Comment by BobMowzie** [comment]
Oh, no no I need to fix this.
