### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by KhileRedline** [BobMowzie/MowziesMobs#316]
Hey, i got this "[com.bobmowzie.mowziesmobs.server.spawn.SpawnHandler:getBiomesFromConfig:146] Reflection failed" from my server every time it started and i know you have already respond to many of these problems but i CAN'T figure it out after few hours of searching. I tried with all version in 1.12.2 same with library but nothing works. Mobs won't spawn normally but will with an egg in creative and drop loot/xp. Plz Help Me...
My discord if you need further information
Khile#1433

**Comment by BobMowzie** [comment]
You tried with 1.5.8?
What other mods are you using?

**Comment by KhileRedline** [comment]
Yes i tried 1.5.8
And i think twilight is the issue but not sure...
Im using: 
aether, twilight forest, electroorb's wizardry, rogue like dj, wall jump, waystone, jei, switchbow and waila

Ps: ty for your fast answer

**Comment by KhileRedline** [comment]
I also tried generating multiple types of map, with biome of plenty and everything but couldn't manage to change anything...

**Comment by BobMowzie** [comment]
Hm...
What happens if you remove Twilight Forest? Aether? BoP? Please try one at a time if you get a chance.

**Comment by KhileRedline** [comment]
Sorry i was out for one day. I tried removing all the mods and couldn't even work with no mod install expect this one... Im starting to be desperate.

**Comment by BobMowzie** [comment]
Alright, I’ll see what I can do. Try updating Java and Forge in the meantime.

**Comment by KhileRedline** [comment]
Ok ty a lot, i'll do this ! I saw some users had  same errors but with a different biome (number) do you think it's related ?

**Comment by BobMowzie** [comment]
Which issues are you referring to?

**Comment by KhileRedline** [comment]
I saw some comments when i was searching for my issue, and a lot of players had the same "error message" as me but with a different biome id:  164 instead of 146, maybe it has some connection ? (Sorry for my english, im french btw)

**Comment by KhileRedline** [comment]
[com.bobmowzie.mowziesmobs.server.spawn.SpawnHandler:getBiomesFromConfig:146] Reflection failed

**Comment by BobMowzie** [comment]
146 and 164 are line numbers in the code, not biome IDs.
The issue I think you are referring to was closed because the player was using a dated version of the mod.
(Your English is very good! Don’t worry!)

**Comment by KhileRedline** [comment]
Oh ok, my bad, i don't know a thing, about java code ! Thanks you !

**Comment by KhileRedline** [comment]
Tell me if you need any further information.

**Comment by BobMowzie** [comment]
What version of Forge are you using?

**Comment by 0xebjc** [comment]
I'm having the same problem:

[Setup]
Minecraft:            1.12.2 Server
Forge:                  14.23.5.2847
Mowzies Mobs:    mowziesmobs-1.5.8.jar
Other Mods:         (Many)

[Error Message]
[Server thread/INFO] [STDOUT]: [com.bobmowzie.mowziesmobs.server.spawn.SpawnHandler:getBiomesFromConfig:146]: Reflection failed

The error message is repeated eight times, and looking at your code (decompiled in Recaf) I see that in
mowziesmobs-1.5.8.jar:classes.com.bobmowzie.mowziesmobs.server.spawn.SpawnHandler
64: public void registerSpawns() this calls the function "getBiomesFromConfig" eight times, so all calls failed.


[Problem Code]
```
    private Set<Biome> getBiomesFromConfig(ConfigHandler.BiomeData biomeData) {
        Field f = null;
        try {
            f = Biome.class.getDeclaredField("biomeName");
            f.setAccessible(true);
        }
        catch (Exception e) {
            System.out.println("Reflection failed");
        }
```

[Config]
https://pastebin.com/ssvViH70

Here's my config, I'm only select vanilla biomes, so not sure why this is failing, I don't think I have mods that add biomes either, just other content.

**Comment by BobMowzie** [comment]
I know what the problem is, I’ve just been too busy with the 1.16 version to fix the 1.12 version right now.

**Comment by 0xebjc** [comment]
Ok, cool, thanks for the fast reply, just wondering does this prevent mob spawning?  I see the barakroa still spawn in the savanna, I haven't looked for other mob spawn locations?  Thanks

**Comment by BobMowzie** [comment]
Nah, it should still work fine.
