### ISSUE TITLE
Wroughtnaut shockwave effect can break protected blocks on servers

### ISSUE THREAD

**Issue by ShayBox** [BobMowzie/MowziesMobs#323]
A config option to disable the boss and axe effect would be great, otherwise this mod can't be used in servers.

**Comment by BobMowzie** [comment]
I’m very confused by what you mean. I don’t know which boss you are referring to, nor what you mean by “axe effect”. All of my content works perfectly fine on multiplayer servers; if you have observed otherwise, then that is a bug.

With that said, you can already disable any mob in the config by setting its spawn/generation rate.

**Comment by ShayBox** [comment]
The shockwave effect that turns blocks into fallingblocks, on both the axe and boss, it can be very abused on servers to break protected blocks or obtain blocks

**Comment by BobMowzie** [comment]
Oh! Well then that’s the issue you should report, not the lack of a config option.

For the time being, you can disable the Ferrous Wroughtnaut in the mod’s config file. I will have a solution ready for the next release.

**Comment by ShayBox** [comment]
I guess that's the issue, but there's no way for you to fix breaking blocks in protected areas without linking to every possible mod that protects areas, either way I realized any update wouldn't change 1.12.2 so I'll just stick to disabling shift+rightclick on that weapon

**Comment by BobMowzie** [comment]
I was thinking of changing the effect to just be visual, and leave the actual blocks in place. But you’re right, I won’t be going back to change the 1.12 version.

You can disable the Wroughtnaut in the mod’s config on the 1.12 version of the mod. You can also keep the Wroughtnaut, and just remove the axe from the Wroughtnaut’s loot table to prevent it from dropping.
