### ISSUE TITLE
Barakoa Village Crash

### ISSUE THREAD

**Issue by Tyrius1** [BobMowzie/MowziesMobs#326]
Using the locate command to find a village and then attempting to TP to it I get this crash:
https://pastebin.com/6gK9g2S9

Minecraft 1.16.5
Forge 36.1.2
Mowzie's Mobs 1.5.14

**Comment by BobMowzie** [comment]
Very strange. I have not received this crash. Try updating Forge.

**Comment by Tyrius1** [comment]
after downgrading to 36.1.0 : https://pastebin.com/Pd7dW1cS crash log
full log: 
[latest.log](https://github.com/BobMowzie/MowziesMobs/files/6198867/latest.log)

**Comment by BobMowzie** [comment]
Thanks, alright. Will fix soon!
