### ISSUE TITLE
Crash with Terraforged

### ISSUE THREAD

**Issue by Matthysse** [BobMowzie/MowziesMobs#330]
Hello!
Here is crash when entering a Terraforged world with Mowzies'Mobs
Seems to come from the structures your mod try to place.

https://pastebin.com/3ysyHe3H

**Comment by BugmanBugman** [comment]
[crash-2021-03-24_15.40.19-client.txt](https://github.com/BobMowzie/MowziesMobs/files/6200370/crash-2021-03-24_15.40.19-client.txt)

Got this too

**Comment by BobMowzie** [comment]
Duplicate of #326
