### ISSUE TITLE
Crash with canSpawn optional - 1.16.5 & 1.5.14

### ISSUE THREAD

**Issue by Dunkmania101** [BobMowzie/MowziesMobs#331]
Hello! I just got a crash in the new 1.5.14 version for 1.16.5. I'll link the report below.
My guess as to what happened is that it tried to use the "get" method on an optional when it didn't have a value.
Maybe try checking if it has one and returning false if not (or true, whichever would suit the "canSpawn" method better)?
It looks like it's on line 107 of the class MowzieEntity.java.

Thanks!

[Crash Report](https://gist.github.com/Dunkmania101/d22c004fe97a3dcfff88553052e0164d)

**Comment by BobMowzie** [comment]
Good catch, but why are you in an unregistered dimension?

**Comment by Dunkmania101** [comment]
I was in a dimension from one of my own mods. Do I need to register it similar to an item or something? All the documentation I could find with something like that was for 1.15 and didn't apply to 1.16.

**Comment by BobMowzie** [comment]
I haven’t added any dimensions before, so I’m not clear on how registration works. But the line of code in question reads:
`ResourceLocation currDimensionName = mutableregistry.getOptionalKey(world.getDimensionType()).get().getLocation(); `
I need the dimension name to check if the mob’s spawn config includes it. Your dimension is not present in the dimension registry, and so even when I fix the crash there will still be no name and my mobs will not spawn there.

**Comment by TelepathicGrunt** [comment]
All dimensions should be registered as it would be impossible for the world it be made if the dimension didnt exist. At least I would think. Someone got that crash with my mod World Blender one and I use vanilla's json worldgen system to create my dimension so it is definitely registered
[crash-2021-03-24_21.08.47-server (1).txt](https://github.com/BobMowzie/MowziesMobs/files/6201375/crash-2021-03-24_21.08.47-server.1.txt)
meone

**Comment by TelepathicGrunt** [comment]
`MutableRegistry<DimensionType> mutableregistry = DynamicRegistries.func_239770_b_().getRegistry(Registry.DIMENSION_TYPE_KEY);`
I fairly certain this isnt safe to do. There's a world passed in which you should try and get the actual world registry being used. Especially as DimensionTypes are not worlds/dimension. DimensionTypes are just says if a bed explodes in the dimension and other small dimension settings. The actual dimension itself is now tied 1:1 with worlds so you'll want to use the world registry from MinecraftServer to blacklist dimension. In fact, this is why you have the crash. You are comparing the world's registrykey to the dimensiontype's registry which dont match.

Just getting the world's registry name should be enough without the need of going through registries. The world themselves already hold their names. This should work
`ResourceLocation currDimensionName = world.getDimensionKey().getLocation()`

I hope this helps!

**Comment by BobMowzie** [comment]
Ahh that's how you do it! Thanks so much, @TelepathicGrunt !
