### ISSUE TITLE
[1.5.14 - 1.16.5] Some Configs aren't working at all...

### ISSUE THREAD

**Issue by Jusey1** [BobMowzie/MowziesMobs#332]
Heyo, I was testing the mod and everything seems to be working just fine. However, when I adjusted some values in the config, nothing changed. For example, attack damage and speed aren't changing to the new values and health for the Wrothnaught wasn't change either.

So, was thinking maybe all number-values might just not be working right now within the config?

**Comment by BobMowzie** [comment]
Entity attributes like health and attack damage are saved as NBT. So, mobs that already exist in the world with those attribute values will always have them restored on load. Changing mob attack damage and health will only affect new instances of the mob created after adjustment.
