### ISSUE TITLE
[1.5.14 - 1.16.5] Some Configs aren't working at all...

### ISSUE THREAD

**Issue by Jusey1** [BobMowzie/MowziesMobs#336]
Heyo, I was testing the mod and everything seems to be working just fine. However, when I adjusted some values in the config, nothing changed. For example, attack damage and speed aren't changing to the new values and health for the Wrothnaught wasn't change either.

So, was thinking maybe all number-values might just not be working right now within the config?

And yes, I brought this back up again because it wouldn't let me re-open the old issue. The config changes aren't being registered on NEW SAVES at all. Everything is still default values no matter what I change in the config, thus the config is bugged and not being read or a conflict is causing it to not be read.

I know how NBT works, and I understand that sort of thing. This is why I ALWAYS test config changes with a brand new save to make sure that they are working, but they aren't in this case...

**Comment by Jusey1** [comment]
Oh, wow. I just figured out the issue and I'm an idiot for not checking this.

The config is regenerating itself upon start. Meaning, any changes made to the config is just being replaced with default values. I guess I can make a bandaid fix by forcing the config to be a read-only file but not sure if that will cause Minecraft to crash or not as the mod will still attempt to generate a new config file.

**Comment by BobMowzie** [comment]
Ohhh that’s strange. I’ll look into this.

**Comment by Jusey1** [comment]
Ye'h. I tried making it a read-only file and that does indeed soft-crash the game with the error that the mod failed to load properly. I do apologize for not checking on this before since this odd bug is super rare. I think I have only ran into it once before.

My best guess is that the script that generates the config file isn't set-up to check if the file is already there or not, thus it is just generating a new one every time, thusly replacing the previous one.

**Comment by BobMowzie** [comment]
Also, you can still comment on closed issues. In the future, just comment with the new info and I’ll reopen. Helps me keep my issues organized.
This one is fine though, since it turned out to be a different problem.

**Comment by Jusey1** [comment]
Oh, my bad. I thought I couldn't.

**Comment by BobMowzie** [comment]
Resolved
