### ISSUE TITLE
Crash at loading my world when added

### ISSUE THREAD

**Issue by bryan161** [BobMowzie/MowziesMobs#341]
https://gist.github.com/bryan161/9feae4568e32ccbbf77f1cfd27c78c90
First time it worked. But when I tried to enter in my world again. it just crashes. So weird cause everything was working fine the first time that I enter in my world after installed it
1.16.5

**Comment by QuerrixTU** [comment]
Try edit world and optimize (don't select delete data).

**Comment by bryan161** [comment]
I tried removing config files and it works now, idk why. But Ill try to change something in config file to see if its that

**Comment by Corvus20** [comment]
I am getting the same crash when creating completely new worlds, too. Something seems to be weird with the Grottol mob, from what I can tell from looking at the logs.

**Comment by bryan161** [comment]
Well, Ive change something in config files, specifically health adn damage multipliers and know I got this crash https://gist.github.com/bryan161/6a99480ba9c77af913adfc8649a413af

**Comment by BobMowzie** [comment]
@Bryan161 That crash is from something called Gobber, not Mowzie’s Mobs.

**Comment by BobMowzie** [comment]
Resovled
