### ISSUE TITLE
Extreme Lag in Nether and End

### ISSUE THREAD

**Issue by mdbgr** [BobMowzie/MowziesMobs#343]
I had a 1.16.5 server with it and other mods running and when entering the nether or end their was extreme lag. I tested in a single player world with only MowziesMobs installed and it caused lag when loading new chunks. I also found that the Ferrous Wroughtnaut was spawning in the Nether and End.

**Comment by QuerrixTU** [comment]
There was already issue open for those 2 issue bro...

**Comment by BobMowzie** [comment]
Duplicate issue
