### ISSUE TITLE
Make frostmaw able to swim

### ISSUE THREAD

**Issue by NEFFLEAFF** [BobMowzie/MowziesMobs#344]
It can't move on water and only swims very slow when there's no target

**Comment by BobMowzie** [comment]
It still can’t swim. Jumping out of water doesn’t count IMO.

**Comment by NEFFLEAFF** [comment]
Right, jump out of water isn't swim but it makes able to at least move. I don't know if it's possible to make frostmaw swim and don't look bad or weird.

**Comment by NEFFLEAFF** [comment]
One idea is to give frostmaw a effect similar to frost walker, but it would still the same without ice crystal, so don't consider it good.
