### ISSUE TITLE
[1.12.2] Barakoa Bugs

### ISSUE THREAD

**Issue by 63502** [BobMowzie/MowziesMobs#35]
These are a few small bugs I noticed during my travels through several savannas.
1. The Barakoana(the one with the strength mask, spear, and shield) does not spawn ever, either in roaming groups of barakoa, or when the sun chief starts lobbing masks.
2. Many of the normal barakoa trades end up selling or buying air blocks instead of the intended items.
3. When a player has heliomancy, sun strikes only seem to activate if they target the top of a completely unobstructed solid block. I noticed this due to tall grass and plants blocking my sun strikes from activating all the time when I was trying to fight mobs. They only started working dependably when I used a sickle to mow down all the grass in the area I was fighting in.

[Mod List](https://gist.github.com/63502/8cacf55a0b74a9c18f4bf18f77bca53a)

**Comment by 63502** [comment]
4. The Barakoa seem to spawn waaaaay too frequently, and in large groups of 10+. As far as I know, they are supposed to be a somewhat uncommon small group encounter, not a run-in with an army 1000 strong.
5. The Barakoa are not nearly aggressive enough to be a threat. If I attack/kill one, its comrades just look on completely unperturbed. They have no real group behavior, and do not attack without provocation even if I am standing in the middle of them without a mask on.

**Comment by BobMowzie** [comment]
So, the Barakoana never spawn, but the Barakoa spawn way too much?

**Comment by 63502** [comment]
It would appear so.

**Comment by BobMowzie** [comment]
Fixed 1, 4, and 5.

**Comment by BobMowzie** [comment]
I am not experiencing 3
