### ISSUE TITLE
electronwill.nightconfig.core?

### ISSUE THREAD

**Issue by Kroahma** [BobMowzie/MowziesMobs#355]
[crash-2021-03-27_22.52.51-fml.txt](https://github.com/BobMowzie/MowziesMobs/files/6216788/crash-2021-03-27_22.52.51-fml.txt)

I can't seem to figure out whats crashing me, can anyone help?

**Comment by BobMowzie** [comment]
Wait why did you close this? Did the issue go away?

**Comment by Kroahma** [comment]
I removed some mods like Better nether and Better end and i think that's what made it go away

**Comment by BobMowzie** [comment]
Oh, but I still have to fix it! I don’t want an incompatibility with those mods.

**Comment by Kroahma** [comment]
Oh uhm after looking into things, i think the problem is actually just from the mod Better end
I removed mowzies and all my other mods and tried to run Better end and Better nether it crashes everytime its being run.
I'm sorry if i was running you on this wild goose chase, Keep up the amazing work on the mod though!

**Comment by BobMowzie** [comment]
Oh okay then!
