### ISSUE TITLE
Spear

### ISSUE THREAD

**Issue by mser7** [BobMowzie/MowziesMobs#36]
So the spear which you obtained from the tribal people have a 1/3 chance to instantly kill an animal, namely pigs, sheeps, cows or gigantic 500 hp dragons from Ice and Fire mod.
https://cdn.discordapp.com/attachments/381304640383483905/454862185810886656/2018-06-09_11.07.43.png
Since they are classified as the same type as farm animals, the spear treats them as one, i hope they will be blacklisted in the future.

**Comment by BobMowzie** [comment]
Resolved
