### ISSUE TITLE
Barakoas deal passive damage

### ISSUE THREAD

**Issue by NEFFLEAFF** [BobMowzie/MowziesMobs#366]
When a barakoa targets something it can deal 4 passive damage, at zombie-like speed per hit.
They hurt by be close to them.

**Comment by BobMowzie** [comment]
I’m not observing this behavior. Are you using any other mods?

**Comment by NEFFLEAFF** [comment]
I think could be mobBattle mod, but I'm on survival. The mod list it's some long.

![image](https://user-images.githubusercontent.com/69360168/112910052-cb55b380-90af-11eb-9797-2b2e810795f1.png)
![image](https://user-images.githubusercontent.com/69360168/112910076-dad4fc80-90af-11eb-8d1a-5906967c280c.png)

**Comment by BobMowzie** [comment]
Did you use any of the wands on the Barakoa?

**Comment by BobMowzie** [comment]
Ah wait! I was wrong! They are doing this on their own! Good catch, thanks.
