### ISSUE TITLE
[1.16.5] wrought_chamber spawns in nether

### ISSUE THREAD

**Issue by ZeroDhita** [BobMowzie/MowziesMobs#369]
Mod version 1.5.15
wrought_chamber spawns in nether
Also the commad /locate wrought_chamber works in nether but when i teleport there ther's nothing
![2021-03-30_12 44 45](https://user-images.githubusercontent.com/81193584/112977046-e2e77780-9155-11eb-8e8b-b30a42e1d39d.png)

![2021-03-30_12 33 42](https://user-images.githubusercontent.com/81193584/112976103-ba12b280-9154-11eb-8f12-0f99b24430af.png)

**Comment by QuerrixTU** [comment]
What others mods did you use ?
