### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by mxnmnm** [BobMowzie/MowziesMobs#37]
I hadn't even spawned in any mobs in this creative test world and the crash report mentions this mod so here you go 
https://pastebin.com/mUbbyec5

**Comment by mser7** [comment]
Same, I have experienced this issue a lot, not sure if the mod Carry On is to blame as well, usually 20 mins it crashed.
https://pastebin.com/PERZSTPJ

**Comment by mser7** [comment]
Apparently it has to do with the PlayerTickEvent of this mod

**Comment by mser7** [comment]
Update: I think it is caused by the Frost Maw, eversince i disabled their spawning in my world I haven't experience any issue, but not sure about other mobs. The Wroughtnaut isn't the cause as well, I tested it by having one near my base.

**Comment by BobMowzie** [comment]
Resolved
