### ISSUE TITLE
Frostmaw + Barakoa combat crash

### ISSUE THREAD

**Issue by dr0mist** [BobMowzie/MowziesMobs#371]
I am not a developer and have no idea how content is created in mods, 
but i have a question. How difficult will it be to add cans for Laterns????
I would really like to have such a cute light bulb in a jar at my house (preferably with a preserved texture). As far as possible, thanks for the answer!))

**Comment by BobMowzie** [comment]
This platform is for reporting issues and bugs or suggesting minor tweaks and improvements. If you would like to request new features, please post to the Curseforge page or Minecraft Forum page in the future.

I’m afraid I’m having trouble understanding your suggestion. What is a “can for lanterns”? What is a “preserved texture”?

**Comment by dr0mist** [comment]
> This platform is for reporting issues and bugs or suggesting minor tweaks and improvements. If you would like to request new features, please post to the Curseforge page or Minecraft Forum page in the future.
> 
> I’m afraid I’m having trouble understanding your suggestion. What is a “can for lanterns”? What is a “preserved texture”?
Glowing can with a lantern as in twiling forset, and preserved texture means that the lantern in the can itself is animated.
And when it comes to mistakes, when I attack Frostmaw along with a bunch of
barakoa about half the hp Frostmaw game crashes!!!!

**Comment by BobMowzie** [comment]
Oh. No, I won’t be adding jars for lanterns. Feel free to build glass enclosures for them and using a lead to bring them inside.

Separate topics should be reported as separate issues in the future. I’ll change the name of this issue to match for now.
Please send the crash log in order for me to identify the problem.

**Comment by TheMinerBoy** [comment]
The crash happens with the Ferrous Wroughtnaut as well. Same method to reproduce.
