### ISSUE TITLE
Setting Frostmaw and Barakoa Village spawn to -1 breaks

### ISSUE THREAD

**Issue by ShootToKillSTK** [BobMowzie/MowziesMobs#374]
If you set the 'Max height' spawning to -1 which it says means it 'ignores' it, it will cause to not spawn or freeze game when you try /locate them.

- The Wrought one works though for some reason. I have a bunch of biome mods like BoP and Byg and others. Maybe caused by that, I simply set the value though to '225' and that worked fine.

**Comment by BobMowzie** [comment]
Ah, nope. My mistake. Fixing now!
