### ISSUE TITLE
Config for weapon and armor stats not working

### ISSUE THREAD

**Issue by Torben8** [BobMowzie/MowziesMobs#376]
I changed the attack speed and attack damage of the Wroughtnaut in the config but it seems to not change in the game.
Also the armor stats of the helmet does not change either when changed in the config.

**Comment by BobMowzie** [comment]
Nah it should affect them there too.
What version of the mod are you using?

**Comment by Torben8** [comment]
I'm using the latest version for 1.16.5, 1.5.15.
Checked again to make sure but the stats didn't changed even if I create a new world with the changed config.

**Comment by BobMowzie** [comment]
Okay. Did the new Wroughtnaut’s stats change with his config?

**Comment by Torben8** [comment]
But I noticed that the barakoa masks gained a point in armor toughness. The config still is at 0.0
Instead the Sol Visage should have 1 point in armor toughness.

Health and attack Damage changed according to the config I think, the health is at 50 with a config value of 1.25

**Comment by zangucci** [comment]
Having the same problem on 1.16.5.
None of the tool(weapons and armor) stats seem to be updating when I change their configs. 

On the other hand mob stat changes(health and attack multipliers) work perfectly.

Hope you find the solution soon.

**Comment by BobMowzie** [comment]
Found a solution. Working on the fix now.
