### ISSUE TITLE
modded spawn blocks don't work

### ISSUE THREAD

**Issue by Torben8** [BobMowzie/MowziesMobs#377]
I also added some spawn blocks from the biomes you'll go mod in the config to have fooliaths spawn in the crag gardens.
Seems like that didn't work as they are only spawning on the edge of the biome where there is grass and not on the "byg:mossy_stone" I added in the config.

**Comment by BobMowzie** [comment]
Foliaaths have some extra conditions on spawning to prevent them from spawning in trees. These might be overriding some custom block settings.
Do modded spawn blocks work with other mobs?

**Comment by Torben8** [comment]
I tested with the barakoa in the lush desert of biomesoplenty, there is mainly orange sand and orange sandstone and even with a spawnrate of 1000 there are no barakoas spawning in the biome. So I think modded blocks really doesn't work.

**Comment by BobMowzie** [comment]
Okay, thanks. That really helps.

**Comment by BobMowzie** [comment]
Figured out your problem. The block config is not set up to expect a mod ID before the block name. I will change this for the next patch. In the meantime, please test placing "mossy_stone" in the config instead.

**Comment by Torben8** [comment]
works for the orange_sand, so might as well work for all modded blocks
just wanted to let you know, thanks for the time and effort.

**Comment by BobMowzie** [comment]
You’re welcome! Don’t forget to change this back in 1.5.16!
