### ISSUE TITLE
Suggestion: Make Grottol's diamonds be compatible with Fortune enchantment on the pickaxe

### ISSUE THREAD

**Issue by warning-djkajslh** [BobMowzie/MowziesMobs#378]
You can't kill them via looting anyway.
The amount of diamonds should be based around diamond ore, non fortune only yield 1, and fortune 3 make quad diamonds common.
May not fit with the Grottol's lore and design tbh ;)

**Comment by BobMowzie** [comment]
This is already in the mod.
