### ISSUE TITLE
Sol Visage, Painted Acacia Planks, Slabs, and Luminous Jelly don't use Forge tags properly

### ISSUE THREAD

**Issue by Inonedn** [BobMowzie/MowziesMobs#382]

**Comment by BobMowzie** [comment]
Oh did I do it wrong? How should it be done?

**Comment by Chumbanotz** [comment]
The folder the forge tags should be in is `data/forge/tags`. Putting them in `data/mowziesmobs/tags` is creating the tags under your mod's namespace.

**Comment by BobMowzie** [comment]
Ah, thank you! My bad
