### ISSUE TITLE
Prevent Foliaths from spawning in certain areas

### ISSUE THREAD

**Issue by Ratmonster04** [BobMowzie/MowziesMobs#385]
I want to make it so that Foliaths still spawn in my world but not when there are torches placed on the ground. I am planning on building something in the jungle. But I don't want Foliaths to kill the mobs I put there.

**Comment by BobMowzie** [comment]
By default foliaaths can only spawn on grass and leaves. You can make them only spawn in darkness using the mod’s config file.
