### ISSUE TITLE
Game crashing when right click with blowgun

### ISSUE THREAD

**Issue by TochaFh** [BobMowzie/MowziesMobs#391]
![blowgun_crash](https://user-images.githubusercontent.com/62609161/113875540-404e7a80-978d-11eb-9424-f7ff42d262a7.png)
![blowgun_crash1](https://user-images.githubusercontent.com/62609161/113875730-72f87300-978d-11eb-93f3-c16ea0d0a305.png)
![blowgun_crash2](https://user-images.githubusercontent.com/62609161/113876028-b94dd200-978d-11eb-8346-570d11c08f62.png)

**1.16.5 with mods:**
Towers Of The Wild (by idrae_)
Just Enough Beacons (by tfarecnim)
Mana and Artifice (by AWildCanadianEh)
Just Enough Items (JEI) (by mezz)
Goblin Traders (by MrCrayfish)
BlockCarpentry (by PianoManu)
Culinary Construct (by TheIllusiveC4)
Create Crafts & Additions (by MRHminer)
Colds: Grappler & Ropes (Forge) (by Coldspell_Games)
Botania Additions (by ToMe250)
KubeJS Create (by LatvianModder)
Carry On (by Tschipp)
Ender Storage 1.8.+ (by covers1624)
Hunter illager (by catscrafters)
Savage & Ravage (by TeamAbnormals)
ReAuth (by TechnicianLP)
Storage Drawers (by Texelsaur)
AppleSkin (by squeek502)
Architectury API (Forge) (by shedaniel)
FTB GUI Library (by FTB)
Reliquary v1.3 (by P3pp3rF1y)
GraveStone Mod (by henkelmax)
Enchant With Mob (by catscrafters)
The One Probe (by McJty)
U Team Core (by HyCraftHD)
MythicBotany (by noeppinoeppi)
LibX (by noeppinoeppi)
Vanilla Hammers [Forge] (by MelanX)
Chisels & Bits (by AlgorithmX2)
AIOT Botania (by MelanX)
Trash Cans (by SuperMartijn642)
Citadel (by alex1the1666)
Mowzie's Mobs (by bobmowzie)
SwingThroughGrass (by exidex)
GeckoLib (by ThanosGecko)
FastFurnace (by Shadows_of_Fire)
Biomes O' Plenty (by Forstride)
Useful Backpacks (by HyCraftHD)
Outvoted (by HowBoutNo)
Crafting Tweaks (by BlayTheNinth)
ItemZoom Rekindled (by simplebunsen)
Create (by simibubi)
Just Enough Calculation (by towdium)
Hunter Mod (Forge) (by Xratedjunior)
WorldEdit (by sk89q)
Patchouli (by Vazkii)
Caelus API (Forge) (by TheIllusiveC4)
Save My Stronghold! (Forge) (by YUNGNICKYOUNG)
Babel (by thenatekirby)
JourneyMap (by techbrew)
Structure Gel API (by ModdingLegacy)
KubeJS (by LatvianModder)
Blood Magic (by WayofTime)
Refined Storage (by raoulvdberge)
Botania (by Vazkii)
CodeChicken Lib 1.8.+ (by covers1624)
Polymorph (Forge) (by TheIllusiveC4)
Akashic Tome (by Vazkii)
NetherPortalFix (by BlayTheNinth)
Just Enough Piglin Bartering (by thenatekirby)
AttributeFix (by DarkhaxDev)
Cooking for Blockheads (by BlayTheNinth)
Just Enough Resources (JER) (by way2muchnoise)
Cosmetic Armor Reworked (by LainMI)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Just Enough Professions (JEP) (by Mrbysco)
Clumps (by Jaredlll08)
Direbats (Forge) (by andantet)
The Twilight Forest (by Benimatic)
Better Advancements (by way2muchnoise)
FTB Quests (by FTB)
Nature's Compass (by Chaosyr)
MoreVanillaLib (by MelanX)
AutoRegLib (by Vazkii)
Abnormals Core (by TeamAbnormals)
Fast Leaf Decay (by olafskiii)
Additional Lights (by mgen256)
Rhino (by LatvianModder)
Vanilla Excavators [Forge] (by MelanX)
Curios API (Forge) (by TheIllusiveC4)
Dungeons Plus (by ModdingLegacy)
The Conjurer (by ModdingLegacy)
Ice and Fire: Dragons (by alex1the1666)
Mod Name Tooltip (by mezz)
FastWorkbench (by Shadows_of_Fire)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Inventory Hotswap (by Areuthreateningme)
Mouse Tweaks (by YaLTeR)
MmmMmmMmmMmm (by bonusboni)
Passthrough Signs (by Girafi)
Item Filters (by LatvianModder)
Controlling (by Jaredlll08)
Placebo (by Shadows_of_Fire)
Curious Elytra (Forge) (by TheIllusiveC4)
Eidolon (by elucent_)

**FILES:
Directory of C:\...\mods**
03/13/2021  11:43 AM           920,840 abnormals_core-1.16.5-3.1.1.jar
03/01/2021  05:58 PM           524,630 additional_lights-1.16.4-2.1.3.jar
04/05/2021  03:58 PM           221,115 aiotbotania-1.16.4-1.7.5.jar
03/01/2021  05:14 PM            41,258 AkashicTome-1.4-16.jar
03/01/2021  05:10 PM            29,113 AppleSkin-mc1.16.2-forge-1.0.14.jar
04/05/2021  05:49 PM           304,643 architectury-1.10.139-forge.jar
03/11/2021  11:46 AM             9,554 AttributeFix-1.16.5-10.1.2.jar
03/01/2021  05:10 PM            57,133 AutoRegLib-1.6-47.jar
03/01/2021  05:28 PM           169,895 Babel-1.0.5.jar
03/01/2021  05:12 PM            62,891 BetterAdvancements-1.16.5-0.1.0.105.jar
04/05/2021  03:54 PM           289,337 BetterMineshafts-Forge-1.16.4-2.0.3.jar
04/05/2021  04:26 PM         3,354,610 BiomesOPlenty-1.16.4-13.0.0.431-universal.jar
04/06/2021  05:46 PM           527,602 blockcarpentry-1.16-0.3.5b.jar
03/08/2021  11:37 AM         8,475,636 BloodMagic-1.16.3-3.0.6-11.jar
03/11/2021  11:46 AM        14,948,303 Botania-1.16.4-414.jar
03/01/2021  05:25 PM            57,594 BotaniaAdditionsMC1.16.4-1.0.4.jar
03/06/2021  11:56 AM            41,523 caelus-forge-1.16.5-2.1.3.0.jar
03/01/2021  05:13 PM           329,601 carryon-1.16.5-1.15.3.13.jar
03/11/2021  11:46 AM           855,387 chiselsandbits-0.3.4-RELEASE.jar
03/01/2021  05:13 PM           428,662 citadel-1.6.2.jar
03/01/2021  05:11 PM            15,997 Clumps-6.0.0.17.jar
03/01/2021  05:12 PM           611,435 CodeChickenLib-1.16.4-3.5.1.408-universal.jar
03/05/2021  11:19 PM            36,776 ColdsGrappler(Forge1.16.4)vrs1.0.2.jar
03/02/2021  12:06 AM            48,851 Controlling-7.0.0.14.jar
04/06/2021  03:11 PM           682,094 CookingForBlockheads_1.16.5-9.3.1.jar
03/02/2021  12:17 AM            86,379 CosmeticArmorReworked-1.16.5-v1b.jar
03/01/2021  05:13 PM           110,838 CraftingTweaks_1.16.3-12.2.0.jar
04/05/2021  03:58 PM         8,046,172 create-mc1.16.5_v0.3.1a.jar
04/05/2021  03:58 PM           345,914 createaddition-1.16.5-20210404a.jar
03/02/2021  12:24 AM           137,752 culinaryconstruct-forge-1.16.5-4.0.0.6.jar
03/08/2021  11:32 AM           243,659 curios-forge-1.16.5-4.0.5.0.jar
03/08/2021  11:31 AM            30,182 curiouselytra-forge-1.16.5-4.0.2.3.jar
04/05/2021  03:58 PM           126,410 direbats-1.1.1+1.16.5-forge.jar
04/05/2021  03:58 PM           381,232 dungeons_plus-1.16.5-1.1.4.jar
04/06/2021  11:29 AM         2,040,762 eidolon-0.2.7.jar
04/05/2021  03:58 PM           305,899 enchantwithmob-1.16.5-1.3.0.jar
03/01/2021  05:12 PM           214,900 EnderStorage-1.16.4-2.7.1.166-universal.jar
03/01/2021  05:13 PM            14,614 FastFurnace-1.16.4-4.4.0.jar
03/01/2021  05:11 PM            18,175 FastLeafDecay-v25.jar
04/05/2021  03:58 PM            33,772 FastWorkbench-1.16.4-4.5.1.jar
04/05/2021  05:49 PM           432,190 ftb-gui-library-1605.2.1.41-forge.jar
04/05/2021  05:49 PM           903,036 ftb-quests-1605.2.1-build.39-forge.jar
04/05/2021  03:58 PM         3,345,750 geckolib-forge-1.16.5-3.0.19.jar
04/05/2021  03:58 PM           416,380 goblintraders-1.3.1-1.16.3.jar
03/01/2021  05:19 PM           227,450 gravestone-1.16.5-1.0.1.jar
03/07/2021  02:06 PM           142,238 hunterillager-1.16.4-1.2.2.jar
03/07/2021  02:06 PM            59,417 HunterMod-1.16.3-1.1.2.jar
03/01/2021  05:13 PM        24,751,314 iceandfire-2.1.6-1.16.4.jar
03/05/2021  08:28 PM           199,160 inventoryhotswap-1.16-1.2.jar
04/05/2021  05:49 PM           107,481 item-filters-1605.2.4-build.30-forge.jar
03/05/2021  11:10 PM            23,373 itemzoom-1.16.x-2.2.1.jar
04/05/2021  03:59 PM           776,321 jei-1.16.5-7.6.1.75.jar
03/01/2021  05:28 PM            18,166 JEPB-1.0.0.jar
03/01/2021  05:10 PM         6,831,133 journeymap-1.16.5-5.7.1.jar
04/06/2021  11:54 AM            17,003 justenoughbeacons-3.1-1.16.3.jar
03/01/2021  05:28 PM           296,432 JustEnoughCalculation-1.16.5-3.6.4.jar
03/01/2021  05:28 PM            19,174 JustEnoughProfessions-1.16.5-1.2.1.jar
03/11/2021  11:46 AM           232,495 JustEnoughResources-1.16.4-0.12.0.109.jar
04/05/2021  05:49 PM           666,485 kubejs-1605.3.6-build.178-forge.jar
04/05/2021  05:49 PM             5,846 kubejs-create-1604.1.0.4.jar
04/06/2021  05:46 PM           252,222 LibX-1.16.3-1.0.30.jar
03/01/2021  05:24 PM        18,783,702 mana-and-artifice-1.3.0.2.jar
04/05/2021  03:59 PM            83,890 MmmMmmMmmMmm-1.16.5-1.1.0.jar
03/01/2021  05:34 PM            10,221 modnametooltip_1.16.2-1.15.0.jar
04/07/2021  10:27 AM                 0 mods.txt
03/13/2021  11:41 AM           105,282 morevanillalib-1.16.4-1.4.0.jar
03/01/2021  05:10 PM            58,249 MouseTweaks-2.14-mc1.16.2.jar
04/05/2021  10:14 PM         5,102,496 mowziesmobs-1.5.15.jar
04/05/2021  03:59 PM           412,299 MythicBotany-1.16.3-1.2.9.jar
03/01/2021  05:11 PM           200,372 NaturesCompass-1.16.5-1.8.6.jar
03/01/2021  05:14 PM           110,010 NetherPortalFix_1.16.3-7.2.1.jar
02/27/2021  02:45 PM         5,400,019 OptiFine_1.16.5_HD_U_G7_MOD.jar
04/05/2021  03:59 PM           466,300 outvoted-1.16.5-1.2.2.jar
03/01/2021  05:37 PM            10,676 PassthroughSigns-1.16.4-2.3.7.jar
03/01/2021  05:11 PM           579,252 Patchouli-1.16.4-50.jar
03/01/2021  05:11 PM           102,026 Placebo-1.16.4-4.4.1.jar
03/01/2021  11:28 PM           128,919 polymorph-forge-1.16.5-0.24.jar
04/06/2021  03:11 PM            38,126 ReAuth-1.16-Forge-3.9.3.jar
03/01/2021  05:45 PM         3,135,679 refinedstorage-1.9.12.jar
03/01/2021  05:15 PM         1,346,497 reliquary-1.16.3-1.3.4.1061.jar
04/05/2021  05:49 PM         1,108,077 rhino-1.7.13-build.14.jar
03/07/2021  12:42 PM           962,042 savageandravage-1.16.5-3.1.0.jar
03/07/2021  12:36 PM           182,118 SaveMyStronghold-1.16.4-1.0.jar
03/01/2021  05:10 PM           494,228 StorageDrawers-1.16.3-8.2.2.jar
04/05/2021  03:59 PM           263,089 structure_gel-1.16.5-1.7.6.jar
03/01/2021  05:11 PM            22,955 swingthroughgrass-1.16.4-1.5.3.jar
03/05/2021  11:06 PM           388,218 the-conjurer-1.16.4-1.0.13.jar
03/01/2021  05:14 PM           307,065 theoneprobe-1.16-3.0.7.jar
03/01/2021  05:55 PM           157,181 towers_of_the_wild-1.16.4-2.0.1.jar
03/01/2021  05:30 PM           145,166 trashcans-1.0.8-mc1.16.4.jar
04/06/2021  03:17 PM           171,972 useful_backpacks-1.16.5-1.12.0.88.jar
04/06/2021  03:17 PM           396,258 u_team_core-1.16.5-3.2.0.194.jar
03/13/2021  11:41 AM            67,107 vanillaexcavators-1.16.4-2.2.1.jar
03/01/2021  05:42 PM            68,362 vanillahammers-1.16.4-2.2.0.jar
03/13/2021  11:41 AM         5,467,043 worldedit-mod-7.2.4.jar
04/05/2021  03:54 PM            69,913 YungsApi-1.16.4-Forge-6.jar
              96 File(s)    131,249,015 bytes

**Comment by BobMowzie** [comment]
I need the crash log, please.

**Comment by TochaFh** [comment]
> I need the crash log, please.

Oops, I forgot the main part....

[crash-2021-04-07_10.36.14-server.txt](https://github.com/BobMowzie/MowziesMobs/files/6272259/crash-2021-04-07_10.36.14-server.txt)

**Comment by TochaFh** [comment]
> [crash-2021-04-07_10.36.14-server.txt](https://github.com/BobMowzie/MowziesMobs/files/6272259/crash-2021-04-07_10.36.14-server.txt)


It seems to be related to blood magic. I will try to reproduce the error with other item, maybe a bow.

**Comment by BobMowzie** [comment]
Yes, this is solely a Blood Magic issue. Please report this to them.

**Comment by TochaFh** [comment]
> Yes, this is solely a Blood Magic issue. Please report this to them.

I'm reporting to them!
But... I tried to reproduce the error with projectile items from vanilla/other mods and I didn't get any crash. So I think there's still a chance for the crash be related to something in blowgun.

**Comment by TochaFh** [comment]
I updated bloodmagic to the latest 1.16.5 version and now everything is working!

**Comment by BobMowzie** [comment]
Ah awesome!
