### ISSUE TITLE
Issue with BGcore

### ISSUE THREAD

**Issue by MimicGithub** [BobMowzie/MowziesMobs#395]
When using BGcore with mowzie's mobs, certain mobs are duplicated, specifically from what I've seen, all of the barakoa village mobs including the barako, and the frostmaw.

**Comment by BobMowzie** [comment]
By duplicated, you mean they are spawning twice?

**Comment by BobMowzie** [comment]
This seems like an issue with BGcore, not Mowzie's Mobs.

**Comment by MimicGithub** [comment]
Hmm, okay, I'll send this issue to them then.
