### ISSUE TITLE
Foliaths sink into the ground after attacking

### ISSUE THREAD

**Issue by mxnmnm** [BobMowzie/MowziesMobs#40]
forge 1.12.2-14.23.4.27055

The title says it all, if you would like all of the mods I'm using and/or a video of it let me know.

**Comment by BobMowzie** [comment]
I am not experiencing this issue. A video and mod list would be greatly appreciated.

**Comment by mxnmnm** [comment]
Vid- https://imgur.com/a/4Xnvx5r

Here are all of the mods/configs (fyi I disabled the foliaths in the config but spawning one in should be just fine) so I can save us both some time- https://drive.google.com/open?id=1dATFGX2hXVsr-8Qc0ZjlWogWlbGqeImN

**Comment by BobMowzie** [comment]
Does this happen every time it attacks? What mob was it attacking? Does it only happen on gravel blocks?

**Comment by mxnmnm** [comment]
No sometimes I'll give one several mobs and it acts normally then I give it one and it sinks.  It's completely random on when it sinks

I can't remember the specific mob it was attacking in the vid (probably some bird from exotic birds) but it does this with all mobs

It happens on all blocks and most importantly grass.

Another note is that it sinks if you spawn a mob near it the moment it starts the animation but if you spawn a mob a bit further away it has a chance of sinking when it attacks the mob (assuming the mob wanders near it).

**Comment by BobMowzie** [comment]
I'm sorry, I'm simply unable to recreate this issue.
