### ISSUE TITLE
Frostmaw got stuck when spawn

### ISSUE THREAD

**Issue by Hsinyao99** [BobMowzie/MowziesMobs#400]
Was checking other stuff on Tundra, and found this couple of times which they spawn in a location that suffocate them helplessly:

[https://ibb.co/k0qsQs9](url)
[https://ibb.co/cCdhsFQ](url)
[https://ibb.co/qy13HKx](url)
[https://ibb.co/rtQjx8f](url)

Maybe let them break certain blocks? I'm using the latest version of the mod and 1.16 minecraft. Love the mod!:)

**Comment by 71vl17** [comment]
Faced same "stuck spawn" too on 1.15.2 ([this modpack](https://www.curseforge.com/minecraft/modpacks/crafttoexiledissonance))
