### ISSUE TITLE
[Feature Request] Foliaath Seed Tags

### ISSUE THREAD

**Issue by DereC4** [BobMowzie/MowziesMobs#405]
Could the Foliaath seed be given the minecraft:seeds and forge seeds item tags so it can be composted as well as used in other mods like Mekanism with the Crusher, since it is a seed/plant type item?

**Comment by BobMowzie** [comment]
The foliaath seed is already tagged as a forge:seed. There is no minecraft:seed tag.
Is it not working for you?

**Comment by DereC4** [comment]
Ok that's weird because JEI and advanced tooltips arent showing it

**Comment by DereC4** [comment]
1.5.15

**Comment by BobMowzie** [comment]
What version of the mod are you using?

**Comment by BobMowzie** [comment]
Please update to version 1.5.16 of Mowzie’s Mobs.

**Comment by DereC4** [comment]
ok
