### ISSUE TITLE
[1.15.2] Crashes With and Without Mowzies

### ISSUE THREAD

**Issue by mahjerion** [BobMowzie/MowziesMobs#406]
Here's the crash log for after Mowzies is removed.

https://pastebin.com/9qt7YndX

Here is the crash with the chamber before it's removed.

https://pastebin.com/1jRc9WTx

Hope it helps.

**Comment by BobMowzie** [comment]
Update your Mowzie’s Mobs installation to 1.5.15.

**Comment by mahjerion** [comment]
This also happened on 1.5.15... I told you this :\

**Comment by BobMowzie** [comment]
Ah, I see. My mistake. But it’s only been two weeks.
