### ISSUE TITLE
Add config option for disabling potion effects on bosses

### ISSUE THREAD

**Issue by PlantBlockland** [BobMowzie/MowziesMobs#407]
Would have preferred to contact on Discord about this but could not find a Mowzies Mobs discord to DM you through.

(1.12.2) Bosses like the Frostmaw can be cheaply and easily killed by throwing potions at them from a distance (especially poison and harming potions). This could perhaps be stopped if the bosses had a config option to be rendered immune to potion effects/potion damage. 

Would be very helpful! Thanks!

**Comment by BobMowzie** [comment]
I think this is a bit beyond the scope of the mod’s config file, sorry. There is probably a separate mod you can find that will let you customize damage types and mob immunities.

Besides, if a player takes the time and resources to brew that many splash potions, they should be allowed to use them on bosses. I’d consider this a strategy, not cheese. If this makes fights too easy, what really should be changed is improving the boss’ responses to these types of strategies by giving them more approach/ranged options.
