### ISSUE TITLE
Barakoa Crash

### ISSUE THREAD

**Issue by WenXin20** [BobMowzie/MowziesMobs#408]
`Minecraft v1.16.5`
`Forge v36.1.4`
`Mowzie's Mobs v1.5.16`

I was testing the mod out in creative and had spawned a Foliaath next to a Barakoa. The crash occurred as the Foliaath bit the Barakoa.
[Crash Report](https://gist.github.com/WenXin20/61eee7e956084db4cff61e426c6baf37)
[Crash Report 2](https://gist.githubusercontent.com/natanfudge/45cbf4fb6b4b494cc354cff601c3ec96/raw/a32d70c4425a85f34b2c01b5aec03a252e32fb24/crash.txt)

**Comment by BobMowzie** [comment]
Fixed!

**Comment by WenXin20** [comment]
Thanks!
