### ISSUE TITLE
Thaumcraft Aspect Support

### ISSUE THREAD

**Issue by BobMowzie** [BobMowzie/MowziesMobs#41]
Foliaath:Herba,Vinculum
Foliaath Seed:Herba,Vinculum,Victus
Wroughtnaut:Humanus,Aversio,Praemunio,Potentia,Metallum
Axe of Thousand Metals:Metallum,Aversio,Potentia
WroughtHelm:Metallum,Praemunio
Barakoa Hunter:Humanus,Aversio
Barakoa Villager:Humanus,Permutatio
Barako:Humanus,Auram,Lux.Ignis
Barakoa Mask:Herba,Humanus
Spear:Aversio,Bestia
Blowgun:Aversio,Bestia,Volatus
Dart:Aversio,Mortuus
Sol Visage:Desiderium,Metallum,Praemunio,Victus
FrostMaw:Bestia,Gelum.Potentia
Ice Crystal:Gelum,Viterus,Desiderium,Praecantatio

**Comment by BlueWither** [comment]
Spear and Blowgun should have Herba, because they seem made from plants. Masks are same reason.

**Comment by BobMowzie** [comment]
Hm, the Barakoa aren't human, and I'm really not sure about the Wroughtnaut. Should they still have the Humanus aspect?

**Comment by BlueWither** [comment]
I don't know, but zombies have this aspect...
Perhaps they should not have it.
