### ISSUE TITLE
Possible Lava Kraken Abilities and Items

### ISSUE THREAD

**Issue by ChrisLTheNerd** [BobMowzie/MowziesMobs#410]
I know you might possibly be considering a lava kraken in the nether and I have a few ideas for it's abilities and items. First it could have a lava kraken ink projectile, it would basically throw a dark cloudy projectile that can set you on fire and gives you slowness. Instead of causing the effects on impact, it could turn into a lingering effect a few seconds after landing making it seem more like ink and maybe for better effect it could explode into a dark cloud kind of like a smoke bomb. Next it could have the ability to make a temporary shield around it that deflects arrows and reduces melee damage done to it. Maybe the shield could be pillars of fire around it but with small hitbox openings between the pillars to allow a player to still deal damage if they are precise enough. Finally it could also be able to hit you with it's tentacles and cause a ton of knockback and damage if you get too close to it, this would make melee attacks against it really risky especially since you are near lava. Also it could drop a lava kraken beak or maybe a lava kraken tentacle and you could craft the drop into a fiery wand. The wand would allow you to launch a lava kraken ink projectile, make a temporary kraken shield, and allow you to walk on lava like a strider. It also could be fire and lava proof like netherite items.

**Comment by BobMowzie** [comment]
These types of suggestions should be posted to the Curseforge page. This platform is for tracking bugs, crashes, and fixes.
