### ISSUE TITLE
Ice Crystal Not Working

### ISSUE THREAD

**Issue by ChrisLTheNerd** [BobMowzie/MowziesMobs#411]
The Frost Maw Ice Crystal  seems to not be working even though I'm on normal.
![ezgif com-gif-maker (10)](https://user-images.githubusercontent.com/50182206/115160778-14be7080-a068-11eb-938e-513ee45ddd30.gif)

**Comment by BobMowzie** [comment]
Which mod version?

**Comment by ChrisLTheNerd** [comment]
Here are the versions of everything I'm using.

Minecraft Version:1.16.5
Mod Version: 1.5.16
Forge Version: 36.0.13

**Comment by BobMowzie** [comment]
Any other mods installed?

**Comment by ChrisLTheNerd** [comment]
It seems to have started working again even with all the mods I used to record the gif. But I did use a fresh download of the mod so I think my mod file was just corrupted.

**Comment by BobMowzie** [comment]
Ah okay then
