### ISSUE TITLE
modded banner patterns break with Mowzie's installed

### ISSUE THREAD

**Issue by Late-Night** [BobMowzie/MowziesMobs#412]

**Comment by wilyank** [comment]
Can confirm, banner patterns by Ice and Fire and Alex's Mobs are affected. Additional Banners is not affected.

**Comment by Late-Night** [comment]
> 
> 
> Can confirm, banner patterns by Ice and Fire and Alex's Mobs are affected. Additional Banners is not affected.

additional banners broke too for me

**Comment by BobMowzie** [comment]
Duplicate of #348
