### ISSUE TITLE
Re: Ice Crystal Not Working

### ISSUE THREAD

**Issue by ChrisLTheNerd** [BobMowzie/MowziesMobs#413]
Sorry, I'm back again. I figured out what was going on after testing a few times and it seems that the Ice Crystal does not work if there are blocks above where you are using the crystal.
![ezgif com-gif-maker (13)](https://user-images.githubusercontent.com/50182206/115176923-0e49ec00-a09c-11eb-8053-47e2b2ce4d6a.gif)

**Comment by BobMowzie** [comment]
Oh woooow this helps a lot! Thank you.

**Comment by 71vl17** [comment]
I'd like to note it also doesn't extinguish fire (1.15.2 and 1.16.5)

**Comment by BobMowzie** [comment]
That’s intentional. I’d like to maintain a fire-beats-ice motif. You can actually light yourself on fire with a flint and steel to escape being frozen.
