### ISSUE TITLE
1.12.2 Sol Visage Crash - Update Pls. 

### ISSUE THREAD

**Issue by imkappa** [BobMowzie/MowziesMobs#418]
When i wear sol visage it crashes(every time) and theres no tab for mod's items, please update 1.12.2's mod

**Comment by BobMowzie** [comment]
Are you using any other mods?

**Comment by BobMowzie** [comment]
Can you please share the crash log?

**Comment by imkappa** [comment]
ok i understand the problem but, can i disable wearability of sol visage

**Comment by imkappa** [comment]
it was about me

**Comment by BobMowzie** [comment]
No, you can’t make the Sol Visage unwearable. You can remove it from Barako’s loot table using a data pack and it won’t drop.
But I can fix this issue! You just need to send me the crash log!

**Comment by BobMowzie** [comment]
Please send me the crash log! I'm working on fixing crashes in 1.12 and I'd like this one to make the cut.

**Comment by imkappa** [comment]
Ok bro sorry i didnt see imma send it, dont be angry :D

**Comment by imkappa** [comment]
Btw not just sol visage crashes every mask crashes

**Comment by imkappa** [comment]
no as i said it was about me imma close it, thanks for answering me
