### ISSUE TITLE
Sun Chief Village Gen

### ISSUE THREAD

**Issue by celsiusqc** [BobMowzie/MowziesMobs#428]
![image](https://user-images.githubusercontent.com/63996164/116312203-23004100-a77a-11eb-8bad-c494b0e92395.png)
Interesting generation. The seed is in the picture if youd like to take a look savanna next to dead sea from BYG

**Comment by celsiusqc** [comment]
![image](https://user-images.githubusercontent.com/63996164/116312326-4c20d180-a77a-11eb-9dc9-8d485bd9f24f.png)
coords

**Comment by BobMowzie** [comment]
But the campfire itself is in the savanna, right?
