### ISSUE TITLE
Summoned Barakoas bugs

### ISSUE THREAD

**Issue by mser7** [BobMowzie/MowziesMobs#43]
In Creative, wear a Sun Chief's mask, then right-click on a barakoas mark to spawn them repeatedly, after sometimes, you can no longer summon anymore of them, and to summon more, you need to at least to re-log, and yes, it does occur in survival.

Your summoned Barakoas will teleport to you while you are on air, either or not it is creative flying, they teleport to the air around you, and die from taking fall damage eventually.

**Comment by BobMowzie** [comment]
The spawn cap is intentional. It seems it resets on relogging.

**Comment by mser7** [comment]
May I suggest a config to disable that?

**Comment by BobMowzie** [comment]
The spawn cap or the resetting on relogging? The resetting is a bug.

**Comment by mser7** [comment]
The spawn cap please

**Comment by BobMowzie** [comment]
No. Infinite Barakoa followers would be overpowered and have the potential to cause a tremendous amount of lag and instability. Not to mention that there’s only so much space around the player. You can always spawn more when one of them dies.

Besides, aren’t you Nosoac on the forum? Weren’t you just complaining that your computer can’t handle Barako spawning more than 10 followers?

**Comment by mser7** [comment]
I see, indeed I am, but I only complain about the Barakoas that are spawned by the Chief, since they are spawned uncontrollably, and required regular check-ups. And I also see what your point is, its make sense, but I also notices that the cap doesn't free itself automatically if a Barakoa die.

**Comment by BobMowzie** [comment]
If you are playing on a server, you also wouldn't have control over this.
I can confirm otherwise. I'm testing it with no issues. And the spawn cap does NOT reset on reload.
Are you playing with other mods?

**Comment by mser7** [comment]
Hmmm.... Is that so, I understand, I will re-check it, perhap it is because the last time I tested the masks was in the 1.11.2 only version.

**Comment by mser7** [comment]
Okay, I tested it, and indeed the cap issue, that leave only the teleporting problem on air, which I will make a separated thread, sorry for wasting your time.

**Comment by BobMowzie** [comment]
It's alright. Test first in the future.
Thanks.
