### ISSUE TITLE
Darker Depths/BGCore makes it so 2 of the same boss spawn in a single structure.

### ISSUE THREAD

**Issue by Carro1001** [BobMowzie/MowziesMobs#434]
The mod Darker Depths (https://www.curseforge.com/minecraft/mc-mods/darker-depths) which adds cave biomes and such to the game, makes it so two of the same boss always spawn in a single structure, like two Frostmaws, two Sun chiefs, and so on, I also included BGCore since it's their dependency.

BGCore: https://www.curseforge.com/minecraft/mc-mods/bgcore

**Comment by BobMowzie** [comment]
Please report this to the darker depths mod issue tracker.

**Comment by Carro1001** [comment]
Will do!
