### ISSUE TITLE
Frostmaws in peaceful difficulty immediately get up

### ISSUE THREAD

**Issue by Chumbanotz** [BobMowzie/MowziesMobs#435]
When the game's difficulty is set to peaceful, hurting a resting frostmaw while in creative mode will make it appear to get up instantly, then lay down again. When you hurt it in survival while the difficulty is peaceful, it will get up and start attacking immediately.

https://user-images.githubusercontent.com/53630561/116753670-70c4b580-a9d5-11eb-98c3-1af4715bb66b.mp4

**Comment by BobMowzie** [comment]
Ooh interesting. Thanks for pointing this out.

**Comment by Chumbanotz** [comment]
Not related to the difficulty being peaceful, but sometimes when the frostmaw's activate animation starts its model appears sunk in the ground for a split-second. If you pause the video starting at the 9 second mark you see it clearly.

https://user-images.githubusercontent.com/53630561/116755021-c1d5a900-a9d7-11eb-9e4e-e4f1607c5710.mp4
