### ISSUE TITLE
MM ignores config .toml

### ISSUE THREAD

**Issue by ReeCodes** [BobMowzie/MowziesMobs#438]
The mod ignores the ...common.toml config.

I set a new height for grottol's to spawn (30); they kept spawning above 30.

I set Foliath's to only spawn in darkness, they kept spawning at any light level.

The dimension-whitelist also doesn't; default "minecraft:overworld". 
They still spawn inside the Undergarden for example.

**Comment by BobMowzie** [comment]
Update to Mowzie’s Mobs 1.5.16.
