### ISSUE TITLE
Spear does not instakill hoglins

### ISSUE THREAD

**Issue by Direbat** [BobMowzie/MowziesMobs#449]
Mowzies mobs version : 1.5.16

forge version : 36.1.9

Issue  : When using the spear against hoglins it will not instakill them not matter what their health is 

steps to replicate 
1 open minecraft with mowzies mobs
2 attack hoglin will spear

expected outcome : when hoglins are low on health they will have a chance to get instakilled

current outcome : hoglins will not be instakilled by spears no matter how low their health is or how many times you try

**Comment by BobMowzie** [comment]
The spear looks at the mob’s maximum health, not their current health. This is intentional.
