### ISSUE TITLE
Frostmaw spawning crashing?

### ISSUE THREAD

**Issue by mser7** [BobMowzie/MowziesMobs#45]
When I tried to live in a snowy biome, I receive crashes very often, I suspected the issue is related to the Frostmaw, and indeed, after I disable their spawning, the crashes stop completely. Here's one of the client and server crash.

https://pastebin.com/kjLbG0Yw
https://pastebin.com/s3jjYarA

**Comment by BobMowzie** [comment]
Duplicate of resolved issue #37. https://github.com/BobMowzie/MowziesMobs/issues/37
