### ISSUE TITLE
Feature Suggestion: Allow Barakoa to invade villages just like pillagers

### ISSUE THREAD

**Issue by Jinman269** [BobMowzie/MowziesMobs#470]
After killing tons of Barakoas or their sun chief, he will gain a status effect just like "Bad Omen" and when the player enters a village will result a raid.

**Comment by BobMowzie** [comment]
But this is a pillager feature, not a Barakoa feature. It wouldn’t make sense to see Barakoa raiding a snowy village.

I suppose you want Piglin raids, too?

**Comment by BobMowzie** [comment]
Pillager raids are already in the game. The Barakoa are different mobs and they do different things.
