### ISSUE TITLE
incompatibility with banners of ice and fire and alexs mobs

### ISSUE THREAD

**Issue by VelocIGamerBR** [BobMowzie/MowziesMobs#473]
when i put mowzie mobs with ice and fire and alexs mobs the banners of these mods get weird
![2021-05-23_17 52 47](https://user-images.githubusercontent.com/83925949/119276168-be58ca80-bbef-11eb-8767-9262b0e4a3ba.png)

**Comment by BobMowzie** [comment]
Duplicate #348
