### ISSUE TITLE
Frostmaw caused recent back to back crashes

### ISSUE THREAD

**Issue by budapesto** [BobMowzie/MowziesMobs#483]
One of my server members recently fought a frostmaw and caused the whole server to crash repeatedly. My server host support agent told me the following: "So, I've taken a look at the recent logs as well as the crash reports, from what I can see, the issue is being caused by a player joining and loading a corrupt/invalid entity from the mod mowziesmobs  It appears the entity is trying to load its EntityBlockSwapper function and causing a hang and subsequent crash."

**Comment by BobMowzie** [comment]
Already fixed for upcoming patch.
