### ISSUE TITLE
Punch II bows can push Barako

### ISSUE THREAD

**Issue by BobMowzie** [BobMowzie/MowziesMobs#486]

**Comment by Chumbanotz** [comment]
I think I figured out why Barako's horizontal motion can still be changed. Move this line:
https://github.com/BobMowzie/MowziesMobs/blob/fa760667693000b9b1701cb6bde38fb2a2bfc73b/src/main/java/com/bobmowzie/mowziesmobs/server/entity/barakoa/EntityBarako.java#L291 before the super call for tick: 
https://github.com/BobMowzie/MowziesMobs/blob/fa760667693000b9b1701cb6bde38fb2a2bfc73b/src/main/java/com/bobmowzie/mowziesmobs/server/entity/barakoa/EntityBarako.java#L282
like so:
```java
@Override
public void tick() {
	setMotion(0, getMotion().y, 0);
	super.tick();
```

**Comment by Chumbanotz** [comment]
This also applies to the Frostmaw, Wroughtnaut, Foliaath and baby Foliaath:
https://github.com/BobMowzie/MowziesMobs/blob/fa760667693000b9b1701cb6bde38fb2a2bfc73b/src/main/java/com/bobmowzie/mowziesmobs/server/entity/wroughtnaut/EntityWroughtnaut.java#L251 https://github.com/BobMowzie/MowziesMobs/blob/fa760667693000b9b1701cb6bde38fb2a2bfc73b/src/main/java/com/bobmowzie/mowziesmobs/server/entity/frostmaw/EntityFrostmaw.java#L499 https://github.com/BobMowzie/MowziesMobs/blob/fa760667693000b9b1701cb6bde38fb2a2bfc73b/src/main/java/com/bobmowzie/mowziesmobs/server/entity/foliaath/EntityBabyFoliaath.java#L77 https://github.com/BobMowzie/MowziesMobs/blob/fa760667693000b9b1701cb6bde38fb2a2bfc73b/src/main/java/com/bobmowzie/mowziesmobs/server/entity/foliaath/EntityFoliaath.java#L119
