### ISSUE TITLE
Barakoa Mask not dropping upon right-click (1.16.5)

### ISSUE THREAD

**Issue by Yellowbross** [BobMowzie/MowziesMobs#487]
i defeated barako in my survival world and got the sol visage, summoned some follower barakoa to test the item out, right-clicked them to return them into their mask forms, and no masks dropped from them after they disappeared. after trying to produce this bug again on a separate creative world, the bug did not happen again. minecraft forge 1.16.5, using mod version 1.5.17

**Comment by trepidotractatos** [comment]
This happened to me while testing the new features in creative.
