### ISSUE TITLE
Wandering Traders do not run away from Barako, Barakoa, Frostmaws, or Nagas, even though Villagers do

### ISSUE THREAD

**Issue by Yellowbross** [BobMowzie/MowziesMobs#496]
wandering traders seem to be completely chill with barako (the sun chief), barakoa, frostmaws, and nagas, even though they are technically villagers (in a logical sense), and normal villagers run away from these mobs for some reason (none of these mobs attack villagers, so villagers running away from these mobs is kind of confusing in and of itself)
![image](https://user-images.githubusercontent.com/85346124/121449649-3bae6a00-c968-11eb-9582-0a5380b93708.png)
![image](https://user-images.githubusercontent.com/85346124/121449668-436e0e80-c968-11eb-8e94-6f4cad079d07.png)
![image](https://user-images.githubusercontent.com/85346124/121449682-4963ef80-c968-11eb-9bdd-138b2138da7b.png)

**Comment by BobMowzie** [comment]
My mobs don’t attack villagers so that they don’t wipe out vanilla villages. Instead, I have villagers run from them so you don’t usually see them near each other.
I didn’t realize that wandering traders didn’t share villager classification. I’ll have to add their fleeing in separately.
