### ISSUE TITLE
Crashing on Startup in latest version

### ISSUE THREAD

**Issue by Zygus42** [BobMowzie/MowziesMobs#5]
1.10.2 - mowziesmobs-1.3.2
[crash-2017-05-10_18.24.06-client.txt](https://github.com/BobMowzie/MowziesMobs/files/989453/crash-2017-05-10_18.24.06-client.txt)

**Comment by BobMowzie** [comment]
You have not installed LLibrary, Mowzie's Mobs' only dependency.
