### ISSUE TITLE
Mobs drop unsync with the animation.

### ISSUE THREAD

**Issue by mser7** [BobMowzie/MowziesMobs#50]

**Comment by BobMowzie** [comment]
I don’t know what this means.

**Comment by mser7** [comment]
Like the sun chief, the wroughtnaut when killed, the drops dropped immediately and doesnt wait for the death animation to finish.

**Comment by mser7** [comment]
And the frostmaw and the foliaath as well.

**Comment by BobMowzie** [comment]
A simple test shows that this is not the case. Are you using an older version again?

**Comment by mser7** [comment]
Oops my bad again, sorry

**Comment by BobMowzie** [comment]
I’m not upset or out of patience or anything like that, but I must ask you once again to be a bit more careful about this. Issues are already stressful for me, and false alarms make things worse.

**Comment by mser7** [comment]
Okay I understand now.
