### ISSUE TITLE
Suggestion:Battleaxe of thousand metal vs shield

### ISSUE THREAD

**Issue by mser7** [BobMowzie/MowziesMobs#51]
Considering this is an "axe", when vs a shielded player, it should give the shield the cooldown, like when vs a vindicator. Right now it only reduce the durability of the shield, althought a lot, it is standard for all weapons.

This could also be used to kill the barakoana easier.

**Comment by BobMowzie** [comment]
The countdown? I’m unfamiliar with vanilla axe combat.

**Comment by mser7** [comment]
Not really axe combat, but shield when vs axe
https://minecraft.gamepedia.com/Shield

**Comment by mser7** [comment]
Sorry, it is a cooldown, not a countdown

**Comment by BobMowzie** [comment]
Ah, I see! Okay, this would be a good addition.

**Comment by mser7** [comment]
I want to suggest this as well, the Barakoana's shield is really resemble vanilla shields, so perhap any weapons that disable vanilla shield also disable their shield?
