### ISSUE TITLE
Create/Advent Of Ascension/Mowzie's Mobs 3-way conflict crash

### ISSUE THREAD

**Issue by videojamesmostlikely** [BobMowzie/MowziesMobs#510]
Mod Version
1.5 Mod Release - 1.16.5 minecraft release

Describe the bug
A game crash upon looking to the right of my portal after entering The Deeplands dimension added by AOA. May be somehow related by Create Ores; Copper and Zinc. My guess is something to do with chunk loading and/or the Ferrous Wroughtnaut.

To Reproduce
Steps to reproduce the behaviour:

Install Create
Install AOA
Install Mowzie's Mobs
Enter Deeplands
Load chunk (?)
Game Crash

Expected behavior
The game not crashing. I don't think it's supposed to do that

Log: https://paste.ee/p/2lbSR

NOTES
Create ores were linked to crash by the mod Blame. Was a experimental report. The following was what was sent by the mod in log:
****************** Blame Report 1.9.2 ******************

This is an experimental report. It is suppose to automatically read
the JSON of all the unregistered ConfiguredFeatures, ConfiguredStructures,
and ConfiguredCarvers. Then does its best to collect the terms that seem to
state whose mod the unregistered stuff belongs to.

Possible mods responsible for unregistered stuff:

create:copper_ore
create:zinc_ore

**Comment by BobMowzie** [comment]
You are using an outdated version of Mowzie’s Mobs. Please update.
