### ISSUE TITLE
Prevent wraughnut chambers from being torn up by other cave mods

### ISSUE THREAD

**Issue by xshen222** [BobMowzie/MowziesMobs#513]
Can you please make this happen? When I locate the wraughnut structure I often find nothing there, presumably because the entire thing is torn up by mods such as yung's better caves and quark, which is really disappointing.

**Comment by BobMowzie** [comment]
That’s not possible. Structures generate after caves.
The locate command doesn’t work on Wroughtnaut chambers. You have to find them manually.
