### ISSUE TITLE
[1.16.5] mowziesmobs:falling_block Client Crash

### ISSUE THREAD

**Issue by Daejangnamu** [BobMowzie/MowziesMobs#518]
Mowzie's Mobs - 1.5.19
forge-1.16.5-36.1.32

Log: 
[crash-2021-07-16_15.58.02-client.txt](https://github.com/BobMowzie/MowziesMobs/files/6832479/crash-2021-07-16_15.58.02-client.txt)

**Comment by BobMowzie** [comment]
This crash is due to Blue Skies. Please report it to them.
