### ISSUE TITLE
Some various "combat enjoyment"/"balance" issues

### ISSUE THREAD

**Issue by Darkmega18** [BobMowzie/MowziesMobs#522]
A few issues with the bosses:
MC: 1.16.5
Forge: 36.2.2
Mowzies: 1.5.19

1. Elenai dodge is meant to give I-frames, so you can pass through attacks etc. But as far as I can tell, barako and frostmaw can both attack and damage you through it. Will this require special compatibility for Elenai's dodge frames to recognize these special kinds of projectiles from different mods?
This is particularly nuts when trying to get away from frostmaw ice breathing while rotating on a dime, or trying to avoid iceballs that hard stun you and are rather very sizey. Or trying to not die to a surprise solar beam instagib.

2. Sometimes Frostmaw's hitbox or the ability to strike frostmaw just... fails for no apparent reason. I'm hitting him with a spartans weps halberd and +6ish range (eidolon prestigeous palm + meet your fight spectres grasp) so he's not wobbling me at the same time. But sometimes it feels like his hitbox will just switch off. Is this some kind of anti-cheese potentially misfiring or a bug?

**Comment by BobMowzie** [comment]
I don’t know how Elenai’s dodge works, but this sounds like an issue on their end.
Solar beam instagib? Solar beams shouldn’t be killing you in one hit if you’re using a shield or fire resistance.

Are you sure you aren’t just missing? It only happens on weapons with extended range? I use normal hitboxes. A video showing what you mean would help.

**Comment by Darkmega18** [comment]
instagib solar beams is probably a side artifact of better hurt timers, but often times it still engulfs you with shields and you get cooked and not sure if fire res was avoiding it though. but the point still stands that becoming apparently invulnerable to attacks doesn't let me dodge through it. although the dodge doesn't block fire and other environmental damages, so it could be likely that you use fire damage for solar attacks and such since fire res blocks them. :V

I'm swinging directly at his general bulk, and when he starts moving the hitbox comes back sometimes. I was in creative though to test it and often times he'd stop walking around and hang out and thats when the missing would start despite not having gone any further or closer. Sometimes also happens when right under him near a tree I'm using to block snowstorms. I swing and it doesn't actually connect unless I swing towards his upper body a bit more or something of the sort.

Oh, yeah, right, thats what 3 was.
3. Snowstorm isn't really feasibly dodgeable even with rapid movements like move plus or elenai dodge, much less sprinting in a general direction hoping to escape it, nor can you shield from it as an alternative. he's basically getting free damage and likely a stun :V Can it be made that he has a maximum rotation speed while breathing the snowstorm? Something like when barako's sweeping his laser in your general direction with a maximum turn radius while active so you can try to get around it rather than try to get away from it?

**Comment by BobMowzie** [comment]
Well yeah, if you mess with hurt timers my mobs’ attacks will deal damage differently. Solar beam applies damage every tick if possible, relying on hurt timers to space that out to reasonable amounts. Barako deals half physical, half fire damage. Frostmaw’s ice magic deals magic damage. Sounds like the dodge mod intentionally doesn’t let you dodge through these.

This sounds like server lag or a bad interaction with other mods. Sounds like you have a lot of combat mods that mess with hurt timers and attack ranges. Please answer my question from before - does this happen with vanilla weapons or only weapons with extended attack range? Also, like I said before, a video would better help me understand what is happening.

This is deliberate. You have to be more creative than just dodging to avoid it. Some players use ender pearls, and some use a flint and steel on themselves (fire damage prevents freezing). Most players just build a barrier with blocks to block it. This isn’t Dark Souls, it’s Minecraft; be creative in your approach to these boss fights.
The frostmaw already has a maximum turning speed when using it and at all other times.

**Comment by Darkmega18** [comment]
> This isn’t Dark Souls, it’s Minecraft; be creative in your approach to these boss fights.

_pardon?_ I thought you were against cheesing when you put in the super nova pull power half suggested by me ages back for barako so he can yoink those "creative approach" players out of their holes in the ground and annihilate them, and further now having him make shield magic bois to make you be active in the fight. :V Cause "placing blocks" is like giving me permission to box frostmaw in and kill his kneecaps, rather than actually fight him out in the tundra where you have him spawn.

> Some players use ender pearls

he's got unlimited breath, and one only has so many ender pearls.

> some use a flint and steel on themselves (fire damage prevents freezing)

didn't seem to be the case when he became an enkindling champion and lit me up with a flaming shulker bullet then iced me with an frostball. :V and thats more pain than it's worth considering you're constantly ticking damage and unable to move properly and having your vision obscured because you're perpetually being thrown into the ground by damage hits.

btw, you can "sorta" move by shifting to "get off" the ice effect and then kinda stiffly wiggle yourself away using move plus. but thats a me thing.

> Well yeah, if you mess with hurt timers my mobs’ attacks will deal damage differently. Solar beam applies damage every tick if possible, relying on hurt timers to space that out to reasonable amounts. Barako deals half physical, half fire damage. Frostmaw’s ice magic deals magic damage. Sounds like the dodge mod intentionally doesn’t let you dodge through these.

I knew this from like 3 previous packs. Since the axe shockwave also obliterates people where they stand when you shockwave, but atleast the player casted solar beam actually does respectable damage for the cost once this happens. :V and yeah, I gathered what frostmaw was doing, cause my armor was garbage against him. >_>' but didn't know barako also had a physical component. interesting.

> This sounds like server lag or a bad interaction with other mods. Sounds like you have a lot of combat mods that mess with hurt timers and attack ranges.

No to the first cause it's single player, probably to the second. absolutely to third cause hurt timers are both a boon and a pain and the reason I hate fighting using damage over time effects when not any such mods. :V

I have some footage I can squish together after I get some sleep. But it seems like Project War Dance's offhand can usually reliably hit him regardless of reach. But spartan's reach stuff from his weapons might just be a little wonky when it's present on a weapon, which was the case when I used a greatsword to squeeze a bit more reach off on him.
The ability to attack from afar based on "reach" which normally only works for weapons specifically made that way is a Project War Dance thing also.
Further, interestingly, your spear doesn't seem to add 3.5 reach. it's more like 1 or 2 extra over punching with my offhand when it's stacked with attribute based reach. Buuuut this seems like it might just be a design and coding thing for how you achieve your own reach.

**Comment by BobMowzie** [comment]
Creative strategies are different from cheese strategies, though it is a fine line. Cheesing strategies are inherently _not_ creative, reducing the amount of thought, effort, and planning to nothing. Digging your way under Barako to avoid his attacks was not a “creative strategy” in this sense, as it reduces the thought and effort needed to beat him. Utilizing your environment, building blocks, ender pearls, and fire damage to beat the Frostmaw does not. But this wasn’t even my point; I was suggesting you think outside of the box and not simply expect to be able to dodge everything with movement or the Dodge mod.

I can’t account for other mod’s tools when balancing my mod. But it sounds like those aren’t easy devices to make. So beating the frostmaw with them is not cheesing, since obtaining those tools took effort and applying them to the fight took thought.

I don’t know how this “build gadget” works, but with regular block placing mechanics, containing a frostmaw is very difficult to do. It moves away from pathing restrictions and will attack you the entire time.

For multiple reasons, I reject the idea that players should not use ender pearls during the frostmaw fight because they are limited in quantity. Ender pearls are a resource, just like a sword’s durability. You go into the fight with your resources, and expend them to win. That’s how the game works. Additionally, the frostmaw does not have unlimited frost breath; it is limited by the time it takes the player to kill it.

I’m unfamiliar with this “Enkindling Champion” mod. Like I said, I can’t speak to how other mods work. Players using the flint and steel strategy typically use a water bucket as well.

Since I suspect you still don’t believe me, here is a video of someone fighting a frostmaw using these tools: https://streamable.com/73m9fz

**Comment by BobMowzie** [comment]
You find the solar beam dealing damage every tick to be balanced? We seem to have different ideas of balancing, then. I’d encourage you to explore my config file and fine tune things to match your needs. But I’ll remind you that the solar beam can deal its damage to any number of mobs in a line in front of you, which is very powerful in vanilla Minecraft.

Single player Minecraft runs a “dedicated server” locally on your machine, which can experience server lag if your CPU is not strong enough or a mod you have installed is poorly optimized.

If a mob takes damage from a fire damage tick, but then during the hurt timer takes damage from a more damaging source like a player’s attack, the mob will take the difference between the damage amounts as additional damage. It may not flash red or be knocked back, though.

My spear is coded differently from Spartan weaponry’s reach and Project War Dance’s reach. I assure you, 3.5 blocks is accurate. I agree, it is likely an interaction of the two systems causing it to behave otherwise.

**Comment by Darkmega18** [comment]
> Creative strategies are different from cheese strategies, though it is a fine line. Cheesing strategies are inherently _not_ creative, reducing the amount of thought, effort, and planning to nothing. Digging your way under Barako to avoid his attacks was not a “creative strategy” in this sense, as it reduces the thought and effort needed to beat him. Utilizing your environment, building blocks, ender pearls, and fire damage to beat the Frostmaw does not. 

So shenanigans and preparation, but not to the point of negating all difficulty.

> But this wasn’t even my point; I was suggesting you think outside of the box and not simply expect to be able to dodge everything with movement or the Dodge mod.

![image](https://user-images.githubusercontent.com/8104689/128331848-748c8bef-8ad4-4adc-a034-d44e38c8b43d.png)
alrighty. Note to self. Don't shun the block building entirely in the block building game for fun action combat mechanics.

> I can’t account for other mod’s tools when balancing my mod. But it sounds like those aren’t easy devices to make. So beating the frostmaw with them is not cheesing, since obtaining those tools took effort and applying them to the fight took thought.
> 
> I don’t know how this “build gadget” works, but with regular block placing mechanics, containing a frostmaw is very difficult to do. It moves away from pathing restrictions and will attack you the entire time.

it's direwolf's signature RF run building tool that can place things at range and in different configurations and selectable sizes. with enough blocks and sneaking up on him while he's sleeping from above you could probably achieve it. The balloon is just a block from engineering that can be placed infront of the player in the air and can have cables run to it. but thats a little sketchy cause it's only one block. relatively cheapish otherwise. but anyways.

> For multiple reasons, I reject the idea that players should not use ender pearls during the frostmaw fight because they are limited in quantity. Ender pearls are a resource, just like a sword’s durability. You go into the fight with your resources, and expend them to win. That’s how the game works. Additionally, the frostmaw does not have unlimited frost breath; it is limited by the time it takes the player to kill it.

you got me. damn my always "it's too good to use" mentality.. Cyclic special reuseable pearls on the other hand I would probably get behind if I remember to...

> I’m unfamiliar with this “Enkindling Champion” mod. Like I said, I can’t speak to how other mods work. Players using the flint and steel strategy typically use a water bucket as well.

It's just the champions mod. Basically mobs spawn randomly or preset in different champion tiers, gaining some additional benefits/auto skills and statistical modifiers. I have him spawning tier 2 which makes him significantly rougher cause the modpack tends to get on the op side. So he needs to be able to take and hand out some significant beatings. and quite honestly, he was, as much as I raged. lol.

> Since I suspect you still don’t believe me, here is a video of someone fighting a frostmaw using these tools: https://streamable.com/73m9fz

![image](https://user-images.githubusercontent.com/8104689/128331707-1e5eb3e0-f0ef-4df9-9ee1-2e523ce27c54.png)
pretty standard vanilla style showcase combat set up, with the stacks of steak and neatly set out inventory that doesn't cause panic. :V 15 seconds in, lingering active hitboxes coming out from behind line of sight already causing some annoyance. Atleast you didn't make him shatter frozen people... :V

> You find the solar beam dealing damage every tick to be balanced? We seem to have different ideas of balancing, then. I’d encourage you to explore my config file and fine tune things to match your needs. But I’ll remind you that the solar beam can deal its damage to any number of mobs in a line in front of you, which is very powerful in vanilla Minecraft.

it's every few ticks, there is a very limited amount of I-frames towards things which are the same source, but effect is the same: yes. Since if it can't evaporate a zombie from full where he stands for something like that, I think you're likely doing it wrong and people will disregard it in larger modded set ups, cause lets be honest, I don't think anymore just puts in a mod or two just for that mod very much. they're usually running into these things in modpacks or atleast influenced by a couple other things. :V

and I have gone through the config, player used stuff is 50% stronger and most things got buffed to be relics cause I champion the bosses to be tougher.


> Single player Minecraft runs a “dedicated server” locally on your machine, which can experience server lag if your CPU is not strong enough or a mod you have installed is poorly optimized.

yeah, I know of this. I'm on a ryzen 7 3700x so, I would think it should be handling relatively well.

> If a mob takes damage from a fire damage tick, but then during the hurt timer takes damage from a more damaging source like a player’s attack, the mob will take the difference between the damage amounts as additional damage. It may not flash red or be knocked back, though.

the lack of reactionary knockback or stunning is usually what gets me lit up. :V 

> My spear is coded differently from Spartan weaponry’s reach and Project War Dance’s reach. I assure you, 3.5 blocks is accurate. I agree, it is likely an interaction of the two systems causing it to behave otherwise.

Alrighty, got that video put together and annotated. For moments in there as it goes where the hits just fail but come back or work in some situations but then work later or probable other issues.

**Comment by BobMowzie** [comment]
Watching the video, this does not appear to be a bug with the frostmaw's hitbox. It seems to be an issue or combination of issues from those weapon-adding mods extending your reach. I suggest you report this to them.

**Comment by Darkmega18** [comment]
Alrighty I figured. and I guess the other stuff like dodges are an elenai issue and the hitscanny anti-open combat snowstorm breathe gripes is just me not utilizing blocks and cover properly in a block game and trying to play the video game a semi-unintended way. :V
