### ISSUE TITLE
1.12.2 I can't connect to my friends server.

### ISSUE THREAD

**Issue by TheMelodicMinor** [BobMowzie/MowziesMobs#523]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  Controllable (controllable-0.11.2-mc1.12.2.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  HCASM (HammerLib-1.12.2-2.0.6.28.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.10.jar)
  Fermion ASM Service (Fermion-1.0.2+hotfix.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 8/3/21 8:42 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.mrcrayfish.controllable.client.RenderEvents.onClientTick(RenderEvents.java:129)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_653_RenderEvents_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.controllable.client.RenderEvents.onClientTick(RenderEvents.java:129)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_653_RenderEvents_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['TheMelodicMinor'/902, l='MpServer', x=-1106.49, y=92.00, z=126.27]]
	Chunk stats: MultiplayerChunkCache: 42, 42
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (68,64,256), Chunk: (at 4,4,0 in 4,16; contains blocks 64,0,256 to 79,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 13069085 game time, 1000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [GCEntityClientPlayerMP['TheMelodicMinor'/902, l='MpServer', x=-1106.49, y=92.00, z=126.27]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1568122928 bytes (1495 MB) / 4798283776 bytes (4576 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 90 mods loaded, 90 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version                  | Source                                             | Signature                                |
	|:------ |:--------------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                               | 9.42                     | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore                     |                          | minecraft.jar                                      | None                                     |
	| LCHIJA | controllable                      | 0.11.2                   | controllable-0.11.2-mc1.12.2.jar                   | None                                     |
	| LCHIJA | fermion.asm.service               | 1.0.2+hotfix             | minecraft.jar                                      | None                                     |
	| LCHIJA | fermion.asm                       | 1.0.2+hotfix             | minecraft.jar                                      | None                                     |
	| LCHIJA | fermion.asm.test                  | 1.0.2+hotfix             | minecraft.jar                                      | None                                     |
	| LCHIJA | bcrf.asm                          | 1.0.0                    | minecraft.jar                                      | None                                     |
	| LCHIJA | jei                               | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                          | None                                     |
	| LCHIJA | abyssalcraft                      | 2.0.0-ALPHA-3            | AbyssalCraft-1.12.2-2.0.0-ALPHA-3.jar              | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | quarryplus                        | 12.5.1                   | AdditionalEnchantedMiner-1.12.2-12.5.1.jar         | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LCHIJA | quarryplus_ct                     | 12.5.1                   | AdditionalEnchantedMiner-1.12.2-12.5.1.jar         | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LCHIJA | buildcraftlib                     | 7.99.24.8                | buildcraft-all-7.99.24.8 (1).jar                   | None                                     |
	| LCHIJA | buildcraftcore                    | 7.99.24.8                | buildcraft-all-7.99.24.8 (1).jar                   | None                                     |
	| LCHIJA | buildcraftfactory                 | 7.99.24.8                | buildcraft-all-7.99.24.8 (1).jar                   | None                                     |
	| LCHIJA | buildcrafttransport               | 7.99.24.8                | buildcraft-all-7.99.24.8 (1).jar                   | None                                     |
	| LCHIJA | buildcraftsilicon                 | 7.99.24.8                | buildcraft-all-7.99.24.8 (1).jar                   | None                                     |
	| LCHIJA | additionalpipes                   | 6.0.0.8                  | additionalpipes-6.0.0.8.jar                        | None                                     |
	| LCHIJA | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCHIJA | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.76            | EnderCore-1.12.2-0.5.76.jar                        | None                                     |
	| LCHIJA | redstoneflux                      | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCHIJA | cofhcore                          | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LCHIJA | cofhworld                         | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LCHIJA | thermalfoundation                 | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LCHIJA | enderio                           | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| LCHIJA | conarm                            | 1.2.5.10                 | conarm-1.12.2-1.2.5.10.jar                         | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHIJA | armoryexpansion                   | 1.4.2                    | armoryexpansion-1.4.2.jar                          | None                                     |
	| LCHIJA | armoryexpansion-custommaterials   | 1.4.2                    | armoryexpansion-1.4.2.jar                          | None                                     |
	| LCHIJA | armoryexpansion-iceandfire        | 1.4.2                    | armoryexpansion-1.4.2.jar                          | None                                     |
	| LCHIJA | armoryexpansion-matteroverdrive   | 1.4.2                    | armoryexpansion-1.4.2.jar                          | None                                     |
	| LCHIJA | astralsorcery                     | 1.10.27                  | astralsorcery-1.12.2-1.10.27.jar                   | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | autocrafter                       | 4.3                      | autocrafter-4.3.jar                                | None                                     |
	| LCHIJA | morphtool                         | 1.2-21                   | Morph-o-Tool-1.2-21.jar                            | None                                     |
	| LCHIJA | autoreglib                        | 1.3-32                   | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCHIJA | biomesoplenty                     | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar      | None                                     |
	| LCHIJA | guideapi                          | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
	| LCHIJA | bloodmagic                        | 1.12.2-2.4.3-105         | BloodMagic-1.12.2-2.4.3-105.jar                    | None                                     |
	| LCHIJA | bookshelf                         | 2.3.589                  | Bookshelf-1.12.2-2.3.589.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | botania                           | r1.10-363                | Botania+r1.10-363.jar                              | None                                     |
	| LCHIJA | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | brandonscore                      | 2.4.19                   | BrandonsCore-1.12.2-2.4.19.214-universal.jar       | None                                     |
	| LCHIJA | buildcraftbuilders                | 7.99.24.8                | buildcraft-all-7.99.24.8 (1).jar                   | None                                     |
	| LCHIJA | buildcraftcompat                  | 7.99.24.8                | buildcraft-all-7.99.24.8 (1).jar                   | None                                     |
	| LCHIJA | buildcraftenergy                  | 7.99.24.8                | buildcraft-all-7.99.24.8 (1).jar                   | None                                     |
	| LCHIJA | buildcraftrobotics                | 7.99.24.8                | buildcraft-all-7.99.24.8 (1).jar                   | None                                     |
	| LCHIJA | fermion                           | 1.0.2+hotfix             | Fermion-1.0.2+hotfix.jar                           | cc2bf3016f756771230cdc4fac0ec50efdf8d212 |
	| LCHIJA | bcrf                              | 1.5.4                    | buildcraft-rf-1.5.4.jar                            | None                                     |
	| LCHIJA | draconicevolution                 | 2.3.27                   | Draconic-Evolution-1.12.2-2.3.27.353-universal.jar | None                                     |
	| LCHIJA | enderiobase                       | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderioconduits                   | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | refinedstorage                    | 1.6.15                   | refinedstorage-1.6.15.jar                          | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderioinvpanel                   | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderiomachines                   | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderiopowertools                 | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | hammercore                        | 2.0.6.28                 | HammerLib-1.12.2-2.0.6.28.jar                      | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | projecte                          | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                        | None                                     |
	| LCHIJA | expequiv                          | 12.3.17                  | ExpandedEquivalence-1.12.2-12.3.17.jar             | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | galacticraftcore                  | 4.0.2.280                | GalacticraftCore-1.12.2-4.0.2.280.jar              | None                                     |
	| LCHIJA | galacticraftplanets               | 4.0.2.280                | Galacticraft-Planets-1.12.2-4.0.2.280.jar          | None                                     |
	| LCHIJA | mjrlegendslib                     | 1.12.2-1.2.1             | MJRLegendsLib-1.12.2-1.2.1.jar                     | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | extraplanets                      | 1.12.2-0.7.3             | ExtraPlanets-1.12.2-0.7.3.jar                      | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
	| LCHIJA | irontanks                         | 1.12.2-2.1.0-beta.18     | irontanks-1.12.2-2.1.0-beta.18.jar                 | None                                     |
	| LCHIJA | journeymap                        | 1.12.2-5.5.6b1           | journeymap-1.12.2-5.5.6b1.jar                      | None                                     |
	| LCHIJA | mekanism                          | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
	| LCHIJA | mekanismgenerators                | 1.12.2-9.8.3.390         | MekanismGenerators-1.12.2-9.8.3.390.jar            | None                                     |
	| LCHIJA | mekanismtools                     | 1.12.2-9.8.3.390         | MekanismTools-1.12.2-9.8.3.390.jar                 | None                                     |
	| LCHIJA | moartinkers                       | 0.6.0                    | moartinkers-0.6.0.jar                              | None                                     |
	| LCHIJA | stevekung's_lib                   | 1.1.10                   | SteveKunG's-Lib-1.12.2-1.1.10.jar                  | None                                     |
	| LCHIJA | moreplanets                       | 2.2.1                    | More-Planets-1.12.2-2.2.1-GC280.jar                | None                                     |
	| LCHIJA | poweradapters                     | 1.0.11                   | PowerAdapters-1.12.2-1.0.11.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | redstonearsenal                   | 2.6.6                    | RedstoneArsenal-1.12.2-2.6.6.1-universal.jar       | None                                     |
	| LCHIJA | taiga                             | 1.12.2-1.3.3             | taiga-1.12.2-1.3.4.jar                             | None                                     |
	| LCHIJA | tinker_io                         | rw2.8.3                  | tinker_io-1.12.2-rw2.8.3.jar                       | None                                     |
	| LCHIJA | tcomplement                       | 1.12.2-0.4.3             | TinkersComplement-1.12.2-0.4.3.jar                 | None                                     |
	| LCHIJA | tinkersjei                        | 1.2                      | tinkersjei-1.2.jar                                 | None                                     |
	| LCHIJA | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| LCHIJA | toolbelt                          | 1.9.13                   | ToolBelt-1.12.2-1.9.13.jar                         | None                                     |
	| LCHIJA | travellersbackpack                | 1.0.23.23                | TravellersBackpack-1.12.2-1.0.23.23.jar            | None                                     |
	| LCHIJA | armoryexpansion-conarm            | 1.4.2                    | armoryexpansion-1.4.2.jar                          | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
Controllable (controllable-0.11.2-mc1.12.2.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
HCASM (HammerLib-1.12.2-2.0.6.28.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.10.jar)
  
Fermion ASM Service (Fermion-1.0.2+hotfix.jar)
  net.thesilkminer.mc.fermion.asm.common.FermionTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 471.41' Renderer: 'NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2'
	Ender IO: No known problems detected.
	Authlib is : /C:/Users/gideo/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	HammerCore Debug Information: 
		Dependent Mods:
			-Expanded Equivalence (expequiv) @ 12.3.17

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- ToolLevelingPlugin (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.41, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 20x Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz

**Comment by BobMowzie** [comment]
This is a crash with Mrcrayfish’s mod.
