### ISSUE TITLE
Loot

### ISSUE THREAD

**Issue by DreamsInsanity** [BobMowzie/MowziesMobs#532]
This mod is a lot of fun. But I realized I wasn't getting any loot drops from regular hostile mobs, zombies, skeletons and creepers. Neutral mobs still dropped loot, I unloaded all my mods and began to load them back in a few at a time and when I got to this one, I realized it was causing the issue

**Comment by BobMowzie** [comment]
Which version are you using? Does it happen when Mowzie’s Mobs is installed by itself?

**Comment by BobMowzie** [comment]
Cannot reproduce.

**Comment by DreamsInsanity** [comment]
Hey, it has been a minute and I can't even remember what the problem was.
