### ISSUE TITLE
 Base value out of range: 256 [-10-128]

### ISSUE THREAD

**Issue by Likeabozz123** [BobMowzie/MowziesMobs#534]
This is basically a duplicate of #340 except on a server.

Error adding element: Base value out of range: 256 [-10-128]
Error adding element: Value 10 outside of range [0:7]
Error adding element: Base value out of range: 256 [-10-128]
Error adding element: Value 10 outside of range [0:7]
Error adding element: Base value out of range: 256 [-10-128]
Error adding element: Value 10 outside of range [0:7]
Error adding element: Base value out of range: 256 [-10-128]
Error adding element: Value 10 outside of range [0:7]
Error adding element: Base value out of range: 256 [-10-128]
Error adding element: Value 10 outside of range [0:7]
Error adding element: Base value out of range: 256 [-10-128]
Error adding element: Value 10 outside of range [0:7]
Error adding element: Base value out of range: 256 [-10-128]
Error adding element: Value 10 outside of range [0:7]
Error adding element: Base value out of range: 256 [-10-128]
Error adding element: Value 10 outside of range [0:7]

**Comment by BobMowzie** [comment]
Can you send the whole log please? What version are you on? The issue you referenced has already been resolved.

**Comment by Likeabozz123** [comment]
I am on the latest version (mowziesmobs-1.5.19). Yeah I saw that the issue has already been resolved but it seems that I still have the issue.

https://paste.ofcode.org/394Mp4ZxWBRsNEgjXbqNjby

**Comment by HadesDeadlyTom** [comment]
Hello, 
I have the same error on my server, i use mowziesmobs-1.5.19 too, with other mods.
Forge is 36.2.0.
It look like it is related to the world generation.
Heres the others mods i use that could interfere maybe : 
- Yungs better cave
- Yungs better dungeon
- Yungs better Mineshafts
- Yungs better strongholds
- Biomes o plenty
- endergetics
- better End Forge

here is the log :
[latest.log](https://github.com/BobMowzie/MowziesMobs/files/7078763/latest.log)

**Comment by HadesDeadlyTom** [comment]
> Hello,
> I have the same error on my server, i use mowziesmobs-1.5.19 too, with other mods.
> Forge is 36.2.0.
> It look like it is related to the world generation.
> Heres the others mods i use that could interfere maybe :
> 
> * Yungs better cave
> * Yungs better dungeon
> * Yungs better Mineshafts
> * Yungs better strongholds
> * Biomes o plenty
> * endergetics
> * better End Forge
> 
> here is the log :
> [latest.log](https://github.com/BobMowzie/MowziesMobs/files/7078763/latest.log)

Hello, i investigated my modlist and i found out your mod was not the cause of my error.
It was infernal expansion : https://github.com/infernalexp/Infernal-Expansion/issues/270

Have a great day !
