### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by FunMLG** [BobMowzie/MowziesMobs#535]
This happens when I launch the game.
![image](https://user-images.githubusercontent.com/44449087/130797254-7295c4ff-7381-40f8-aff0-1326d999fd8f.png)

Any ideas ?

**Comment by BobMowzie** [comment]
Can you send the full crash log, please? It should be in your .Minecraft folder.

**Comment by FunMLG** [comment]
Hey, nvm about the issue 😅
@SundownCam will take over, if he want

**Comment by BobMowzie** [comment]
Did you fix it?

**Comment by SundownCam** [comment]
> Did you fix it?

No, I still have no idea who/what 'fastutil' is

**Comment by BobMowzie** [comment]
I was asking @FunMLG.
FastUtil appears to be a mod you have installed.

**Comment by FunMLG** [comment]
> Did you fix it?

I gave up 😅
And I didn't have a "FastUtil" mod. I have FastFurnace but I don't think it's that.
Wait, I'll try again one more time and tell you if the problem solved itself
BRB

**Comment by FunMLG** [comment]
Well, the problem solved itself 🤷‍♂️
No more "_java.lang.ArrayIndexOutOfBoundsException: -1_" message

**Comment by BobMowzie** [comment]
Very strange

**Comment by SundownCam** [comment]
I just tried again as well and it worked, sorry to bother you.

**Comment by FunMLG** [comment]
> Very strange

I was on Archlinux when I wanted this mod but I didn't try to relaunch my game. I just deleted the mod right after that because I have too many mods and I didn't want to wait so long (again) but some "bugs" are solved by relaunch the game ;) (Like when I couldn't launch the game because my game version had only 2Go of RAM allocated and I tried with 4Go and everything was good)
Anyway, problem solved. Next time someone will have the same problem, just relaunch the game (maybe with more RAM allocated if it's below 8Go allocated) ^^
