### ISSUE TITLE
Ferrous Wroughtnaut Crashing Game

### ISSUE THREAD

**Issue by aaron12523** [BobMowzie/MowziesMobs#537]
any time I go to attack the Ferrous Wroughtnaut my game crashes, as long as I don't click on him it seems to run fine though.

**Comment by BobMowzie** [comment]
I can’t help you without the crash log. Please post it.

**Comment by aaron12523** [comment]
sorry here it is.
[crash-2021-08-30_14.45.15-client.txt](https://github.com/BobMowzie/MowziesMobs/files/7078950/crash-2021-08-30_14.45.15-client.txt)

**Comment by BobMowzie** [comment]
This is an issue with some mod called “bmorph”. Not Mowzie’s Mobs.
