### ISSUE TITLE
Can I make a book based on your fashion?

### ISSUE THREAD

**Issue by bandank555bloger** [BobMowzie/MowziesMobs#539]
Hello developers! I have a question for you. Can I write a book on your fashion? Now I'm just writing a book. (she hasn't come out yet). But I want to write games based on my favorite games. If you will, I will be eternally grateful. Perhaps I'll add the "Ice and Fire" mod to the book. Everything will depend on whether the developers will allow it. I hope you see my message. Initially, the book will be written in Russian, but some time after its release, I will translate it into English. Waiting for an answer. (Can you please answer me on Instagram. Here is my name bandunk08).Have a nice day!

**Comment by BobMowzie** [comment]
This platform is for reporting bugs. This kind of question is best posted in my discord or on Curseforge. Additionally, my Instagram account is private. I don’t use it to communicate with fans.

I’m not sure I understand your request. You’d like to write a fictional story book featuring Mowzie’s Mobs monsters? That’s fine as long as it doesn’t claim to be official. This would count as “fan fiction” I suppose.
