### ISSUE TITLE
Frostmaw vs bow users

### ISSUE THREAD

**Issue by BobMowzie** [BobMowzie/MowziesMobs#54]
Currently too easy to defeat with a bow. Make arrows do no damage? Give it a long range ice attack?

**Comment by mser7** [comment]
long range ice attack for both the mob and the crystal please

**Comment by BobMowzie** [comment]
Still debating this. I want to give the frostmaw a long ranged attack but not the player. I like how the crystal is balanced right now.

**Comment by PCAwesomeness** [comment]
How about making the Frostmaw leap towards targets that are far away from it? You can possibly even make that leap end in a fist slam.

**Comment by PCAwesomeness** [comment]
Alright.

How would just running quickly in order to close distance between it and the player be?

**Comment by BobMowzie** [comment]
Same idea. Would fit better for a different mob. The idea for the frostmaw is that it freezes its enemies and closes the distance using that time.

**Comment by PCAwesomeness** [comment]
Mmmhmmm.

How would using projectile ice work for this mod? I'd imagine it spewing out a large, concentrated cloud of ice that travels in a wide parabola and heavily impedes the player's movement if they are caught in the impact.

**Comment by BobMowzie** [comment]
I have something in mind.

**Comment by BobMowzie** [comment]
Went for the projectile. Players can't use it, though.
