### ISSUE TITLE
Grottols can dig everywhere

### ISSUE THREAD

**Issue by GatoLeyo** [BobMowzie/MowziesMobs#543]
I'm not totally sure if this is intended but I remember that the Grottol's behavior was different in previous versions.

The issue is that Grottols can dig to escape everywhere, wood, glass and even in the air (I used a lead in a fence that was floating). Please fix this or clarify if this is intended.

**Comment by BobMowzie** [comment]
I cannot reproduce this issue. Grottols can only dig on earthen materials in all of my testing.
