### ISSUE TITLE
Bringing to attention: Mod repost

### ISSUE THREAD

**Issue by IdrisQe** [BobMowzie/MowziesMobs#548]
https://www.curseforge.com/minecraft/mc-mods/mowziev0-4

This person (who only made their curseforge account 1 day go) appears to have reposted an old version of the mod for some reason, and makes no attempt to even link back to the original, which is _probably_ against whatever license is used. Unfortunately some poor saps have already downloaded it.

**Comment by BobMowzie** [comment]
Yeah I reported it. Not sure what else I can do.
Please report it as well.
