### ISSUE TITLE
Lag Spikes During Chunk Generation

### ISSUE THREAD

**Issue by viceversagames** [BobMowzie/MowziesMobs#552]
https://spark.lucko.me/s30JO2RbKw

**Comment by BobMowzie** [comment]
This is a conflict with Mowzie's Mobs and Terraforged that occurs when my mobs check nearby structures to avoid spawning near them. You have two options.

1. Remove Terraforged.
2. Remove all "avoid structure" entries from the Mowzie's Mobs spawn configs.
