### ISSUE TITLE
Mobspawning causes huge lag spikes.

### ISSUE THREAD

**Issue by YahiaTGF** [BobMowzie/MowziesMobs#554]
Hey!
I'm working on my own modpack and we're currently facing a few issues with lag spikes, this didn't happen in the 1.12.2 version but in the 1.16.5 it seems persistent, I've run a couple of spark profilers and most of them resulted in Mowzie's Mobs mod being the reason of the lag spikes. 

Terraforged world type: https://spark.lucko.me/TZspco55xN
Normal world type: https://spark.lucko.me/iNOnggiuD5

I do now know that Terraforged is also a huge problem when it comes to chunkloading [And have dealt with it] but, is there a way to avoid mobs from destroying frames/tps while loading chunks/running .spawnpredicate()? 

Worth mentioning, I've changed the config to make mobs spawn further away from each other but that didn't change much.

**Comment by BobMowzie** [comment]
Hey, taking a look at the profile you sent, the issue seems to be with Lithium's "getChunk" function, which replaces what I use to check nearby structures when mob spawning.

You have two options:
1. Remove Lithium.
2. Clear all "avoid structures" entries from the Mowzie's Mobs spawn configs.
