### ISSUE TITLE
[BUG] crash on server.

### ISSUE THREAD

**Issue by PixVoxel** [BobMowzie/MowziesMobs#566]
[crash-2022-01-23_11.07.51-fml.txt](https://github.com/BobMowzie/MowziesMobs/files/7919594/crash-2022-01-23_11.07.51-fml.txt)

crash on server.

**Comment by DeltaWolf7** [comment]
Hi,

Yeah have the same with the latest version, looks like a client only method is missing an attribute.

Can provide full logs if required.

Thanks

**Comment by TheMrCheeky** [comment]
Same, can't load mowzies on my server the latest 1.16.5 patch

**Comment by MrJorman** [comment]
yes, i can't load mowzie.. pls fix.

**Comment by BobMowzie** [comment]
Trying to fix this now. I can’t seem to make any headway with it yet…

**Comment by MrJorman** [comment]
ok.

**Comment by TheMrCheeky** [comment]
I am sure he will figure it out have patience, until then just use last version before this!

**Comment by BobMowzie** [comment]
Okay I think it's fixed thanks to Silk/Oblivion on the MMD Discord server! If you don't mind, please test out this quick build to make sure:
https://www.mediafire.com/file/xxb233dawcd391p/mowziesmobs-1.5.20-serverfix.jar/file

**Comment by TheMrCheeky** [comment]
Hmm maybe its something on my end, The server runs fine with that but as soon as i connect it crashes ill see if i can find crash log

**Comment by BobMowzie** [comment]
A log would be very helpful. It’s possible this is a new issue.

**Comment by TheMrCheeky** [comment]
[crash-reports_crash-2022-01-25_01.52.38-server.txt](https://github.com/BobMowzie/MowziesMobs/files/7932009/crash-reports_crash-2022-01-25_01.52.38-server.txt)

**Comment by BobMowzie** [comment]
Hm, nothing in there I can see directly implicates Mowzie’s Mobs. I’ll check it out more tomorrow.

**Comment by TheMrCheeky** [comment]
I mean I do have tons of other mods present but it was works fine with mowziesmobs-1.5.19

**Comment by DeltaWolf7** [comment]
> Okay I think it's fixed thanks to Silk/Oblivion on the MMD Discord server! If you don't mind, please test out this quick build to make sure: https://www.mediafire.com/file/xxb233dawcd391p/mowziesmobs-1.5.20-serverfix.jar/file

Hi, Yes this does fix the issue and allows the server to start as now.

**Comment by Theoretical-Enday** [comment]
Crash at player want to connect server with mowziesmobs-1.5.20-serverfix.jar
[crash-2022-01-25_20.41.24-server.txt](https://github.com/BobMowzie/MowziesMobs/files/7933255/crash-2022-01-25_20.41.24-server.txt)

**Comment by BobMowzie** [comment]
Alright yeah, separate crash. This one is fortunately easier to fix.

**Comment by MrJorman** [comment]
pls fix and drop.

**Comment by MrJorman** [comment]
<3

**Comment by BobMowzie** [comment]
https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs/files/3625268

Issue is fixed!

**Comment by awesomestpie** [comment]
Got a problem. Fight with Ferus starts. Game crashes when i hit him in his back. Singleplay has no problem

**Comment by BobMowzie** [comment]
> [crash-2022-11-23_22.59.52-client.txt](https://github.com/BobMowzie/MowziesMobs/files/10078874/crash-2022-11-23_22.59.52-client.txt)
> 
> 

This is caused by Budschie's Morph Mod. Please report this issue to them.

**Comment by awesomestpie** [comment]
THNKU VERY MUCH HOLY IT WORKED. Wasted  2 evenings to fix it

**Comment by BobMowzie** [comment]
> THNKU VERY MUCH HOLY IT WORKED. Wasted  2 evenings to fix it

No problem! You can actually just read the first few lines of the crash log, it will usually say which mod is responsible.
