### ISSUE TITLE
NoSuchFieldError: spinAmount on login to server

### ISSUE THREAD

**Issue by isaacgrimm** [BobMowzie/MowziesMobs#571]
While entering server I get a crash while using v1.15.20.
[crash-2022-01-25_10.43.28-server.txt](https://github.com/BobMowzie/MowziesMobs/files/7932972/crash-2022-01-25_10.43.28-server.txt)

I am not sure if it is a compatibility issue, or I need to change settings in some way or form.

**Comment by BobMowzie** [comment]
Fixed
