### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MrJorman** [BobMowzie/MowziesMobs#575]
Hi, can I set up the spawn of all bosses so that they spawn rarely around the world and already in loaded chunks, for example as zombies, spiders and the like, otherwise it turns out that new players cannot find bosses who were killed by old players a long time ago?

How to do it?

**Comment by BobMowzie** [comment]
Yep! You can do this with a separate mob spawn control mod like In Control: https://www.curseforge.com/minecraft/mc-mods/in-control

**Comment by MrJorman** [comment]
I'm sorry, but I can't understand how this mod works, is there any other way to implement it?

**Comment by BobMowzie** [comment]
There may be other mods like it, but none that I know of.
It’s not that hard to use In-Control. It’s well documented and the people on the Discord server are helpful. Take the little bit of time to learn how to use it and you will be glad you did.
