### ISSUE TITLE
Mowzie's Mobs has class loading errors. Minecraft 1.16.5

### ISSUE THREAD

**Issue by Ryderboi03** [BobMowzie/MowziesMobs#581]
Not sure as to why I am having this error, when I had first installed this, it had no problems, the 2nd time I installed it, this error message came. I tried what a layman could do, delete the file and install it again, but unfortunately the same error message pops up

![whateroristhis](https://user-images.githubusercontent.com/98026283/151711577-f4489a22-d37d-4864-a796-26093dd98cb1.png)

**Comment by BobMowzie** [comment]
You need to install Geckolib
