### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by XionioXMaster** [BobMowzie/MowziesMobs#589]
https://paste.loliidc.cn/?cda68550db5794f6#AbrPreiphwn8bikr1FKyWyPFn4HzrCD3dSQdASFCZrEA

Mowzie's Mobs - 1.5.22

**Comment by XionioXMaster** [comment]
https://github.com/BobMowzie/MowziesMobs/issues/586

This is last version!

**Comment by BobMowzie** [comment]
Don’t close the issue if you want me to fix it!

**Comment by XionioXMaster** [comment]
> Don’t close the issue if you want me to fix it!

the thing is i used the old version

**Comment by XionioXMaster** [comment]
But maybe it is on the latest version

**Comment by BobMowzie** [comment]
Ohhh okay, I see.
