### ISSUE TITLE
Ticking Entity Crashes

### ISSUE THREAD

**Issue by 3th3** [BobMowzie/MowziesMobs#590]
[crash-2022-02-10_10.21.28-server.txt](https://github.com/BobMowzie/MowziesMobs/files/8036810/crash-2022-02-10_10.21.28-server.txt)
This has happened with multiple different Mowzie mobs. I am unsure if it is a compatibility issue or not; more playtesting will be required and this message will be edited when I have time to test the environment.

**Comment by BobMowzie** [comment]
Nothing in this crash log implicates Mowzie’s Mobs. What makes you think it’s the cause?

**Comment by 3th3** [comment]
My bad, that was the wrong crash report. Sending the proper one no
[crash-2022-02-10_10.20.29-server.txt](https://github.com/BobMowzie/MowziesMobs/files/8038762/crash-2022-02-10_10.20.29-server.txt)
w

**Comment by BobMowzie** [comment]
This crash is caused by improvedmobs, not Mowzie’s Mobs.

**Comment by 3th3** [comment]
Ah. Alright. I just assumed since the frostmaw was the entity being ticked. But that makes sense
