### ISSUE TITLE
Server Crashing Bug

### ISSUE THREAD

**Issue by LivestreaminMe** [BobMowzie/MowziesMobs#593]
Hi, regarding to the bug. I am running the Better Minecraft 16.5 update. v.55.5f. The bug was noticed once defeating Barako and grabbing the quest loot. Accessing the wandering bag used as storage is what caused the server to crash. Just to make sure it was the definite issue I managed to replicate the bug a further 2 times in which both resulted in the same crash.

**Comment by BobMowzie** [comment]
I can't help at all without a crash log...

**Comment by LivestreaminMe** [comment]
[server167193 - 17 Feb 2022 0_34_13.zip](https://github.com/BobMowzie/MowziesMobs/files/8085947/server167193.-.17.Feb.2022.0_34_13.zip)
[server167193 - 17 Feb 2022 0_34_21.zip](https://github.com/BobMowzie/MowziesMobs/files/8085949/server167193.-.17.Feb.2022.0_34_21.zip)
[server167193 - 17 Feb 2022 0_34_26.zip](https://github.com/BobMowzie/MowziesMobs/files/8085950/server167193.-.17.Feb.2022.0_34_26.zip)

**Comment by BobMowzie** [comment]
According to these logs, this is not a Mowzie's Mobs. It seems to be a mixin conflict, but I'm not sure.

I don't make the quest system or wandering bag. Check with those mod authors.
