### ISSUE TITLE
[1.11.2-1.3.2] Issue when logging into Server!

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [BobMowzie/MowziesMobs#6]
Here is the Pastebin, this happens in out Kitchen Sink Modpack!

https://pastebin.com/LZhpQ0td

Basically, it wasn't letting me join the server, once I removed Mowzies I was able to join perfectly!

**Comment by leagris** [comment]
@BobMowzie Guess issue is lwjgl mouse input is getting called server-side = bad 🐛

**Comment by BobMowzie** [comment]
Yeah, oops...
