### ISSUE TITLE
Adding an exceptions config to Grottals

### ISSUE THREAD

**Issue by Mdbgamer** [BobMowzie/MowziesMobs#605]
So, you could add either a type of weapon, or a specific item such as the Caged Mobs Netherite Sampler. Would be a pretty cool thing to have.

**Comment by BobMowzie** [comment]
I’m sorry, I don’t understand what you mean. Exceptions to what?

**Comment by Mdbgamer** [comment]
Ok uh...
You know how they can only be damaged by pickaxes? Well, making a config that can include a list of weapons that are exceptions to this rule. So, if I were to say "Ok, only pickaxes can damage these, but also anything on this list can too", that means pickaxes and anything on that list can do damage to them.

**Comment by BobMowzie** [comment]
It’s not just pickaxes, it’s anything that can mine diamond ore. Can the netherrite sampler mine diamond?

**Comment by Mdbgamer** [comment]
It cannot, unfortunately. The sampler needs to do damage to take the sample, but I suppose since it can't mine diamonds, it can't take said sample... 
Really makes sense how that works now though. 🤔

**Comment by BobMowzie** [comment]
hm, I'll consider adding a tag you can add the sampler to.

**Comment by BobMowzie** [comment]
Okay, I created an item tag and included the samplers. Feel free to change the tag using a data pack once this patch releases.
