### ISSUE TITLE
[1.16.5][1.5.25] Wroughtnaut isn't spawning with TerraForge

### ISSUE THREAD

**Issue by BigBoiSub** [BobMowzie/MowziesMobs#623]
Wroughtnaut is not spawning with TerraForge. Everything else is spawning by the looks of it, besides Wrought

**Comment by BobMowzie** [comment]
Are you sure? The /locate command doesn’t work on Wrought chambers.

**Comment by BigBoiSub** [comment]
They do spawn, but very rarely. Why wouldn't /locate command work on it?

**Comment by BobMowzie** [comment]
Because the structure can’t generate if there’s no cave wall to attach to. But Minecraft still thinks it’s there.
