### ISSUE TITLE
NoAI no longer works

### ISSUE THREAD

**Issue by BlueWither** [BobMowzie/MowziesMobs#63]
For example, they are creepers witch summoned by this command.
/summon Creeper ~ ~ ~ {NoAI:1b}
Without this mod,
<img src="https://i.imgur.com/aivpKjs.png">
With this mod,
<img src="https://i.imgur.com/Q5jgMTU.png">
This trouble seems to be the reason why the stone statue moves.

**Comment by BobMowzie** [comment]
So Mowzie’s Mobs is adding AI to AI-less vanilla mobs?

**Comment by BlueWither** [comment]
I'm not sure, apparently it seems like that.
It is not myself that I found this problem.

**Comment by Alex-the-666** [comment]
@BobMowzie it appears mowzie's is overriding the isAiDisabled() method in entity living(base?).
