### ISSUE TITLE
[Suggestion]longer cooldown for the axe of thousand metals

### ISSUE THREAD

**Issue by mser7** [BobMowzie/MowziesMobs#64]
As of right now, the axe is kinda broken with the ability to spam it continuously, I suggest making it so there is a long cooldown after you swipe or swing to balance it, how long is the cool down, I will let it for you to decide based on the vanilla mechanic
https://minecraft.gamepedia.com/Damage#Attack_cooldown

**Comment by BobMowzie** [comment]
I agree, will change.
