### ISSUE TITLE
Crash when changing view while wearing Barakoa masks (1.12.2)

### ISSUE THREAD

**Issue by realpxlese** [BobMowzie/MowziesMobs#645]
Everytime I wear a Barakoa mask my friend crashes and I also crash if I change the view with F5 while wearing the mask.

Also for some reason when we are near the mod's mobs we get disconnect from the server with the message "A fatal error has occurred. This connection is terminated." and we need to log in again in the server.

Here is the last crash report if needed and a print with all the mods I'm using.

[crash-2022-07-21_17.52.07-client.txt](https://github.com/BobMowzie/MowziesMobs/files/9163089/crash-2022-07-21_17.52.07-client.txt)
"
![image](https://user-images.githubusercontent.com/109768695/180324224-46f4e20d-baee-44d0-a60d-e7dbb1bb64fc.png)

**Comment by BobMowzie** [comment]
You are using an outdated version of Mowzie's Mobs for 1.12. Also, the crash seems to be caused by Epic Fight Mod.

**Comment by realpxlese** [comment]
> You are using an outdated version of Mowzie's Mobs for 1.12. Also, the crash seems to be caused by Epic Fight Mod.

Yea, I was trying to use another version because I think it was a problem with it, I'll to remove the Epic Fight Mod and I'll let you know. Thanks for answering that fast, appreciate it!

**Comment by realpxlese** [comment]
![image](https://user-images.githubusercontent.com/109768695/180326158-48db2370-ccc9-402b-bb94-e9685aa3bb8d.png)
It worked! Thanks so much bro, luv ya!

Also do you know any good source where I can learn how to read the crash report file?

**Comment by BobMowzie** [comment]
No problem! Enjoy.

There's not much to learn, you just have to look at it. Near the very top it says
```

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/21/22 5:52 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at maninthehouse.epicfight.capabilities.item.ArmorCapability.getBipedArmorModel(ArmorCapability.java:83)

```

It says epicfight right there. Nothing else to it.
