### ISSUE TITLE
Release Mowzie's Mobs mod to Minecraft China

### ISSUE THREAD

**Issue by CCaiji233r** [BobMowzie/MowziesMobs#653]
@BobMowzie Hi! I think your Mowzie's Mobs mod is great, so I want to publish it on minecraft china, hope you can allow it

**Comment by BobMowzie** [comment]
Thank you! I’m not familiar with this platform. Could you please send me a link?

**Comment by CCaiji233r** [comment]
@BobMowzie https://mc.163.com/

**Comment by BobMowzie** [comment]
I see. I can’t allow you to redistribute my mod. Sorry.
