### ISSUE TITLE
mob in Mowzie Mobs

### ISSUE THREAD

**Issue by zacaca123** [BobMowzie/MowziesMobs#656]
in 1.16.5, l try to search these mob Frostmaw , Grottol. l only found mob is Foliaath, Ferrous Wroughtnaut,  Barakoa, Barako, the Sun Chief. l setting easy to hard but not found one of these Frostmaw , Grottol. l am not sure is my error because l using a lot of modded ,l don't know all my modded effect Mowzie's Mobs ? that is error mob not spawning in biome when selected easy to hard

**Comment by zacaca123** [comment]
l see thanks you, but l turn off command in minecraft :)) that mean you can't use command

**Comment by BobMowzie** [comment]
You can check in a new creative mode world to confirm that they are generating.
