### ISSUE TITLE
Ferrous Wroughtnaut structure crashes the server

### ISSUE THREAD

**Issue by Shirozero123** [BobMowzie/MowziesMobs#657]
[crash-2022-09-22_01.42.34-server.txt](https://github.com/BobMowzie/MowziesMobs/files/9621560/crash-2022-09-22_01.42.34-server.txt)

Every time a player goes near that certain area the server crashes is there a way to fix this?

**Comment by BobMowzie** [comment]
This has been fixed in later versions of the mod
