### ISSUE TITLE
Crash on 1.16.5 when opening inventory

### ISSUE THREAD

**Issue by BurgerBob886** [BobMowzie/MowziesMobs#660]
I opened my inventory while doing one of the special attacks from the Ferrous Wroughtnaut's axe. Instantly, I was kicked from the server I was playing on and my game subsequently crashed. This is in Forge 36.2.39, with mod version 1.5.25 (latest versions). Crash log is attached. 

[crash-2022-10-03_22.33.53-client.txt](https://github.com/BobMowzie/MowziesMobs/files/9703073/crash-2022-10-03_22.33.53-client.txt)

**Comment by TheWitherlord** [comment]
same error here, however I am playing on a server too, joined the game again and got the data mixed up/corrupted.
