### ISSUE TITLE
Crash when using heliomancy or gauntlet of earth (1.18.2)

### ISSUE THREAD

**Issue by Wraen** [BobMowzie/MowziesMobs#661]
The game completely crashes whenever the player tries to use a blessing of the sun ability, or when trying to use gauntlet of earth. Full crashlog is below

[crash-2022-10-04_17.20.32-client.txt](https://github.com/BobMowzie/MowziesMobs/files/9708872/crash-2022-10-04_17.20.32-client.txt)

**Comment by BobMowzie** [comment]
Downgrade to a previous version of Geckolib

**Comment by Wraen** [comment]
Thank you, I'll try that out!
