### ISSUE TITLE
Le crash

### ISSUE THREAD

**Issue by thelegitdolt** [BobMowzie/MowziesMobs#663]
happens when right clicking ground with the heliomacning effect thing

Crash report: https://gist.github.com/thelegitdolt/c4fc9071de293fba5c463ec6d7a1b9e5
Lates.logs: https://gist.github.com/thelegitdolt/52346688d8a351ab825d44c3d246fa74

**Comment by BobMowzie** [comment]
You are using an unsupported version of Geckolib. Please downgrade to 3.0.29.

**Comment by thelegitdolt** [comment]
alright
