### ISSUE TITLE
Ice Crystal Crash with F5: Forge 1.18.2

### ISSUE THREAD

**Issue by viiizee** [BobMowzie/MowziesMobs#665]
I think I found a bug. If you place the Ice Crystal in the offhand, use it and then try to click F5 the game freezes and then crashes. I've been able to re-create this issue on forge 1.18.2 - 40.1.73 with Mowzie's Mobs 1.5.29 and Geckolib 3.0.40.

[crash-2022-10-09_17.13.35-client.txt](https://github.com/BobMowzie/MowziesMobs/files/9742868/crash-2022-10-09_17.13.35-client.txt)

I do have other mods installed, including Shaders and Optifine; however, when I tried to reproduce this issue with only Mowzie's Mobs and Geckolib installed. I received a different crash without even pressing F5; just using the Ice Crystal in the offhand.

[crash-2022-10-09_17.28.33-client.txt](https://github.com/BobMowzie/MowziesMobs/files/9742867/crash-2022-10-09_17.28.33-client.txt)

**Comment by BobMowzie** [comment]
You are using an unsupported version of Geckolib. Please downgrade to 3.0.39
