### ISSUE TITLE
[1.18.2] Using any Mowzie's mob item with custom animations crashes game

### ISSUE THREAD

**Issue by Branjoman** [BobMowzie/MowziesMobs#667]
Having trouble with a custom personal pack I'm making where using any item from Mowzie's mobs that has custom animations (ferrous wroughtnaught axe, earthbore gauntlet, heliomancy laser blast etc.) causes an instant crash to desktop. This issue doesn't occur with Mowzie's mobs only, but I'm not sure which other mod could be causing the imcompatibility.

Log: [https://mclo.gs/PFD69U3](https://mclo.gs/PFD69U3)

**Comment by BobMowzie** [comment]
Update Mowzie’s Mobs
