### ISSUE TITLE
Crash when right click with Axe of a Thousand Metals or Ice Crystal

### ISSUE THREAD

**Issue by CatastropheChou** [BobMowzie/MowziesMobs#668]
CR:
https://pastebin.ubuntu.com/p/WfwrffJ9BD/

**Comment by CatastropheChou** [comment]
GeckoLib version: geckolib-forge-1.16.5-3.0.95.jar
Mowzie's Mobs version: mowziesmobs-1.5.25.jar
Minecraft Forge version: forge-1.16.5-36.2.39.jar

**Comment by BobMowzie** [comment]
1.16 requires Geckolib version 3.0.57 to run. Newer versions will cause a crash.
