### ISSUE TITLE
1.16.5 crash when right click with sun blessing

### ISSUE THREAD

**Issue by DogeKingChris** [BobMowzie/MowziesMobs#669]
it will kick me off my server, say "saving world" then crash my entire game.

[crash-2022-10-21_17.54.16-client.txt](https://github.com/BobMowzie/MowziesMobs/files/9842750/crash-2022-10-21_17.54.16-client.txt)

**Comment by BobMowzie** [comment]
You are using an unsupported version of Geckolib. Downgrade to 3.0.57.
