### ISSUE TITLE
Right-clicking causing crashes? 

### ISSUE THREAD

**Issue by Punkthulhu** [BobMowzie/MowziesMobs#671]
Crash log as requested:
[crash-2022-10-23_09.15.32-client.txt](https://github.com/BobMowzie/MowziesMobs/files/9847291/crash-2022-10-23_09.15.32-client.txt)

It's highly probable that this mod is not causing the issues that I initially thought, as there were crashes after the case which logs stated were something else entirely. It's possible that another mod is/was causing an issue between others; here's the log that was generated roughly 20 minutes later from the above log: 
[crash-2022-10-23_09.37.15-client.txt](https://github.com/BobMowzie/MowziesMobs/files/9847293/crash-2022-10-23_09.37.15-client.txt)

**Comment by BobMowzie** [comment]
Update Geckolib.
