### ISSUE TITLE
crash mowzies and new geckolib version 

### ISSUE THREAD

**Issue by 5stigma** [BobMowzie/MowziesMobs#673]
[crash-2022-10-25_20.46.03-client.txt](https://github.com/BobMowzie/MowziesMobs/files/9865307/crash-2022-10-25_20.46.03-client.txt)

**Comment by BobMowzie** [comment]
Downgrade to Geckolib 3.0.46

**Comment by Traptonian** [comment]
Im sorry but this made me LOL I just came from the geckolib github and looked for this issue saw that it was an issue with mowzie came here and saw the same guy raised the issue and you just said "downgrade" after i just downgraded lol

**Comment by DTX3** [comment]
> Downgrade to Geckolib 3.0.46

This doesn't work I'm afraid. Says mowziesmobs requires geckolib3 3.0.48 or above

![2022-10-26_12-51-49](https://user-images.githubusercontent.com/59918994/198019273-1002e219-33b7-40a0-bf29-382c8e87d82c.jpg)

**Comment by 5stigma** [comment]
it is already updated. you can try to used the new version of geckolib with Now mowzie's version
