### ISSUE TITLE
[1.18.2]some visual bugs when you use weapons

### ISSUE THREAD

**Issue by Rocketcat19** [BobMowzie/MowziesMobs#677]
vanilla armor
![2022-11-17_18 27 11](https://user-images.githubusercontent.com/113609599/202423140-6dc138c2-e94f-4386-b534-69611a63036f.png)

using the axe
![2022-11-17_18 27 13](https://user-images.githubusercontent.com/113609599/202423243-88393a18-4533-4003-bac1-63f98a71d3ce.png)

modded armor
![2022-11-17_18 27 33](https://user-images.githubusercontent.com/113609599/202423366-de45d1bd-6f9c-446a-a68e-7b326120dc08.png)

using the axe
![2022-11-17_18 27 34](https://user-images.githubusercontent.com/113609599/202423401-57c0dca7-28f8-4f04-ae29-3f5f228be1ad.png)

it seems that the second layer of the armor can't be rendered correctly.

**Comment by Rocketcat19** [comment]
By the way,will mowzies mod be compatible with immersive armors?
I would be thankful if that happened

**Comment by BobMowzie** [comment]
As far as I know, it is compatible.
Also this original issue is fixed in the latest release.
