### ISSUE TITLE
Any 1.16.5 update?

### ISSUE THREAD

**Issue by CatastropheChou** [BobMowzie/MowziesMobs#678]
I found that you fixed animations not playing in new geckolib versions [here](https://github.com/BobMowzie/MowziesMobs/commit/91fa10e7ddb97951280b9e66ca5903426eb24121) three days ago. However, the files on CurseForge don't have any update till now. Can you release a new one? I'm struggling with the GeckoLib version because [Dungeons Gear](https://www.curseforge.com/minecraft/mc-mods/dungeons-gear/files/4111923) & [Dungeons Mobs](https://www.curseforge.com/minecraft/mc-mods/dungeons-mobs/download/4111935) do require 103 or above GeckoLib version but MowziesMobs things will go wrong on this version. Thanks!

**Comment by BobMowzie** [comment]
The fix isn't ready yet. I still have to fix armor rendering.

**Comment by CatastropheChou** [comment]
got it.
Thank you.
