### ISSUE TITLE
[Suggestion] I have some suggestions for your mod

### ISSUE THREAD

**Issue by EEzackHShtin** [BobMowzie/MowziesMobs#681]
Hi! I love your mod. Very unique and fun.
Gameplay Suggestions:
1. My first suggestion involves the Barakoa and Barako. So Barako can use his sun powers during the night, which doesn’t make much sense. So how about he has to use his powers to turn the time of day to day, but he has to focus his powers leaving him vulnerable. The Barakoa know he is vulnerable so they form a protective ring around him. I think it would make things a little more tactical and fun. Another way they could do this is if up to 5 barakoaya work together to change the night to day. If there are four or fewer, they can't do this. 
New Mob Suggestions:
1. My first suggestion, still retaining to the Barakoa, involves outcasts. Barakoa outcasts can be found in groups of up to three, wandering around solemnly. They can be found in villages, savannas, and plains once in a while. They don't wear masks, as that is the reason they became outcasts; they rejected the masks. Barakoa, Barakoana, and Barakos are hostile to these outcasts, and the outcasts run away from them, and players wearing Barakoa and Barako masks. They are passive mobs. If a player arms them (gives them a weapon by right-clicking on them with a weapon), they will help the player fight Barako and Barakoa villages, but all they'll help out with.
2. Wyverns. I think wyverns would be a cool addition. I think you know what a wyvern is compared to a dragon, but just in case you don't, "a winged two-legged dragon with a barbed tail." You could also just look up photos. So, going back to my suggestion, their behavior would be similar to that of a bird. They make nests, lay eggs, and raise their hatchlings. An egg takes 30 Minecraft days to hatch. Their hatchlings come first above all. Each nest has a male and a female. They love the taste of sheep, though cows and pigs are fine too. When they kill a sheep, they either eat the meat right away or bring it back to their nest to feed their young. They have four attack options, the first being pecking their opponent. The second attack would be to swing its barbed tail at the attacker. The third, they fly up and then drop back down tail first and bounce back up when their tail hits the ground (this takes inspiration from Super Metroid's Ridley). The last is a screech, which makes each player within a five-block radius of the wyvern unable to move for three seconds. A wyvern would be extremely hostile towards everything, attacking even another wyvern. Their most prominent rival are the nagas, who prey on their hatchlings and eggs. Wyvern nests can be found in mountains, but wyverns are sometimes spotted anywhere cows, sheep, and pigs spawn searching for food to eat or feed their hatchlings with. A player can steal an egg, but they have to feed the hatchling constantly or it will starve to death. The other option would be to steal a slightly more mature hatchling that can kill on its own but is still dependent on a parent. It would be impossible to tame an adult wyvern. Once a tamed wyvern reaches adulthood, it can be saddled and ridden. A player can make it screech, use its tail attack, or peck. Earplugs can be made from two pieces of wool so the player doesn't get the no movement effect when riding the wyvern and it screeches.

**Comment by BobMowzie** [comment]
Hello! Sorry but this is not the correct place to submit suggestions. GitHub issues are for bugs, crashes, mod incompatibilities, etc. Please submit content suggestions on my Discord server. I’ll respond to these there.
