### ISSUE TITLE
player on server crash when rendering weapon attack

### ISSUE THREAD

**Issue by Trifyd** [BobMowzie/MowziesMobs#683]
hello, i have been running a server with my friend, on the ATM Spellbound modpack (1.16.5), mozzie mob is in the modpack so when we found a a Ferrous Wroughtnaut we were happy to fight and kill it, but the probleme arise when we tried to use the weapond, everyone who was looking at it or crash, so we tested all the weapon in singeplayer and there are working fine, only when we try on the server did we crash and that just if we are looking when weapon special ability are use, i think it came from the rendering beacuse when a use the naga dagger my friend still got all the effect (doubkle damge from behind + poison). so i'm leaving this here hopping you will fix it in the future. i included that crash log below

[crash-2022-12-27_01.03.23-client.txt](https://github.com/BobMowzie/MowziesMobs/files/10305050/crash-2022-12-27_01.03.23-client.txt)

**Comment by BobMowzie** [comment]
This is already fixed. Update Mowzie's Mobs and Geckolib.
