### ISSUE TITLE
Mowzie's Mobs support for 1.19 and newer versions.

### ISSUE THREAD

**Issue by Bencehhh** [BobMowzie/MowziesMobs#694]
Hello there!

I am Bencehhh and I've been wondering if this mod will be ported to newer minecraft versions, such as 1.19 and above.
I am making a modpack on 1.19.2 but as I noticed this mod (the mod would have a major impact on my modpack that I am making) is not ported to 1.19 yet.

When this mod is going to be ported to 1.19 and above?

I would be happy if someone started porting this mod to a newer version.

If you would like to see this mod on 1.19 aswell then feel free to drop a comment down here!

**Comment by BobMowzie** [comment]
This platform is for bug reports only. If you want to know what the plans are for a 1.19 update, you can read about it on my FAQ on the Curseforge page or Discord server.
