### ISSUE TITLE
[1.3.3] Battle of the Mods (vs Toroquest)

### ISSUE THREAD

**Issue by kreezxil** [BobMowzie/MowziesMobs#7]
Your mod is working great but there seems to be an odd peculiarity with it. I also use Toroquest to  provide Village lords that give quests to players. These lords also provide an area of protection to the villages to atleast a distance of about 300 blocks radius. When you are in these areas you see a reputation badge appear on your screen which defaults to 0. If you kill hostile mobs in the area the rep increases, if you kill passives or neutrals, the rep decreases. If the rep decreases too much the village lords guardsmen will seek you out for your crimes.

A player of mine accepted a quest from such a village lord. The village was either in a Savannah biome or near one enough that the village protection extended into the the Savannah biome. At any rate when my player returned to his lord to turn in his quest, he was beset upon my tribesmen with masks (ie your mobs) that the had to kill to defend himself. As he dispatched each one, his rep dropped to the point where he is now in bad standing with the village he swore allegiance too.

Based on observation alone it would appear that your mobs inherit from the Villager class thus making them appear to be neutral/passives to Toroquest. Which in turn means that killing them will drop your rep with that mod.

The initial bug report was filed with Toroquest at https://github.com/ToroCraft/ToroQuest/issues/157

**Comment by pau101** [comment]
Our barakoa do not inherit from the vanilla villager but they are passive mobs under some conditions.

**Comment by pau101** [comment]
It appears that the "animalsAffectRep" configuration is what would cause our entities to decrease rep.
