### ISSUE TITLE
Spawning conditions of Foliaaths?

### ISSUE THREAD

**Issue by migmolrod** [BobMowzie/MowziesMobs#70]
What are the exact conditions for Foliaaths to spawn? I would want to avoid their spawn in some places. For example, animal farms.

The only condition that seems to be required is: they spawn in grass blocks (regardless of light level and if the block is either directly under the sky or covered). But I can't stop using grass in some farms, for example sheeps (they would stop regrowing wool). I haven't tried to play with height yet. Do they need a certain height above the grass block?

The plants are cool and all that. The first hour of gameplay. After that they only become annoying just because they are apparently unavoidable and there are places where you just want to avoid them.

**Comment by BobMowzie** [comment]
They only spawn on grass or leaf blocks in jungles. I'll see if I can think of a way to keep them out of farms.

**Comment by BobMowzie** [comment]
Oh, what mod is it and what biome? I've heard of several biome mods tagging biomes as jungles arbitrarily.
That's exactly the plan! Won't be craftable though.

**Comment by migmolrod** [comment]
Actually I'm using a mod pack. The only mod I think is tinkering with the terrain generation in a biome scale is BiomeBundle (which uses Open Terrain Generator if I understood it well).

BTW, I've edited my previous message with another idea for an item.

**Comment by BobMowzie** [comment]
I see. I guess that's on them.

I can't really think of an item that would make sense for that, but I'll keep thinking.

**Comment by BobMowzie** [comment]
Decided to limit their spawning based on light level. They wont spawn around torchlit areas. Hope this helps!
