### ISSUE TITLE
Axe of a thousand metals special attack crash

### ISSUE THREAD

**Issue by asheryyy** [BobMowzie/MowziesMobs#703]
Hello, i am playing minecraft 1.18.2 using mowzie mobs and it seems fine, i noticed the axe of a thousand metals is crashing with the oculus mod, whenever i turn the shaders on and use the special attack the games crashes.

i don't really know if the issue is the axe or the shaders, but i tested a couple more shaders and even tried setting on the compatibility issue, but the special attack seems to only work with shaders off.

here is the crash log :
[2023-05-28-6.log](https://github.com/BobMowzie/MowziesMobs/files/11585135/2023-05-28-6.log)

everyone in my server that is using shaders crashes whenever i use the special attack, but it doesn't crashes when we fight the iron knight ( i forgot its name).

**Comment by BobMowzie** [comment]
Unfortunately my player animations are incompatible with More Player Models. You'll have to remove it or turn off my animations using the config file.

**Comment by asheryyy** [comment]
do i turn off mowzie mobs animations or more player models animations?

**Comment by BobMowzie** [comment]
Mowzie's mobs animations. Use my client config
