### ISSUE TITLE
question: when will biloko be added?

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [BobMowzie/MowziesMobs#705]
I wonder when the rival tribe of the barakoa will be added?

**Comment by BobMowzie** [comment]
This platform is for reporting bugs and crashes. Not asking questions. Please read my FAQ for an answer to your question.

**Comment by SonicTheHedgehog58987276** [comment]
doesn't say when biloko will be added exactly

**Comment by BobMowzie** [comment]
The FAQ very clearly says that we have no idea when the Biloko will be added.

**Comment by SonicTheHedgehog58987276** [comment]
oh.
