### ISSUE TITLE
Barako The Sun Chief, lava issue (NOT CLOSED)

### ISSUE THREAD

**Issue by BurgerTable** [BobMowzie/MowziesMobs#707]
We all know and love the famous "Barako". One of the most difficult bosses by far, having the laser beam, the cube orb and others make this boss lovable and really difficult. But theres an issue, by just wearing a "Barakoa" mask of any sorts and having a lava bucket its all it takes to take it down. Instead of getting full diamond protection 4 armor and still dying. By placing the lava behind Barako (while wearing a barakoa mask) does **MASSIVE**, constant damage, and he will get angry but for some seconds. After he has lost 3/4 of his health, grab your lava (make sure it has dissapeared) and start destroying him. He will drop the "Sol Visage" (barako mask). And thats the easiest, fastest and most broken way to defeat him. PLEASE FIX THIS!!

Lots of love to the development team.
BurgerTable

**Comment by BobMowzie** [comment]
Hmm, there are measures in place to prevent this. Are the Barakoaya healers not spawning in your game?

**Comment by BobMowzie** [comment]
Also Barako is not that hard with the proper equipment! He deals half fire damage which goes through armor, so protection 4 might not be the right move. Try fire resistance instead.

**Comment by BurgerTable** [comment]
> Hmm, there are measures in place to prevent this. Are the Barakoaya healers not spawning in your game?

Unfortunately, yeah. Like, look at this: 

https://github.com/BobMowzie/MowziesMobs/assets/138215970/11f2e317-bf75-4f7a-995b-7dea3f72736d

**Comment by BobMowzie** [comment]
Wait, what version of the mod are you using?

**Comment by BurgerTable** [comment]
1.5.8

**Comment by BobMowzie** [comment]
Oh! The Barakoaya healers were added later and address this cheese strategy. I won't be porting them back to 1.12.

**Comment by BurgerTable** [comment]
> Oh! The Barakoaya healers were added later and address this cheese strategy. I won't be porting them back to 1.12.

My bad 😬
