### ISSUE TITLE
[Suggestion]: Puppet Master

### ISSUE THREAD

**Issue by rougedarkdragon** [BobMowzie/MowziesMobs#715]
Is this the place to make suggestions now? I'm not sure, tell me if it's somewhere else. Anyway, here's the suggestion:

Puppet Master

A power-hungry lunatic who resides in a ruined theater, the puppet master wears a ragged jester's hat, a checkerboard cloak, and a mask with a demented face. His weapon is his glove, the Marionette's Hand, which fires dark strings that allow him to control undead monsters. 
His theater is mostly empty, with many chairs and a decrepit stage where he sits, waiting. Fallen skeletons line the edges of the stage. When the player walks up to the stage, the puppet master wakes, overjoyed that someone has come to see his twisted show, and activates the magic in his glove. It generates a shield that protects the puppet master from all attacks, and he teleports to a corner of the stage. He holds his hand in the air, revealing a terrifying eye that glows on the palm of his glove, and dark strings emerge from the eye, flying into the fallen skeletons. Their bones come together and they stand, drawing weapons. The player can defeat them, but when they run out, the puppet master will scream and cause more bones to fall from the ceiling. The player must attack the strings, and when enough are severed they will all break, stunning the puppet master and dropping his shield. The player can then attack until he comes to his senses and teleports away, reactivating his shield. This repeats until he reaches low health, where he teleports to the center of the stage and changes his attacks. His mask flies off his face, revealing another mask, and another, until a circle of masks flies above the puppet master. The last mask flies off his face, revealing a horrific eye like the one on the palm of the Marionette's Hand. He chuckles through his eye, which glows and fires a beam at the player. If the player doges, the beam is caught by one of the masks, which directs it back at the player. If the player gets the beam to fly back at the puppet master, it will stun him and the player can attack his eye. When his health runs out, he screeches and glows, and he is sucked inside of the Marionette's Hand, which floats to the ground for the player to claim. With this glove, the player can fire their own dark strings at zombies and skeletons, which will then attack hostile mobs around the player. This only lasts for a few moments, and then the spell breaks and the monsters become hostile again, and the glove must recharge. The glove can only enthrall one monster at first, but duplicate gloves from other puppet masters can be turned into maniacal essence, which can be combined with a glove to increase the number of monsters it can enthrall, up to five. 

I hope you like this suggestion! Did I finally come up with a compelling hook?

Edit: They wouldn't be vanilla skeletons, they'd be special, slower ones so the player isn't overwhelmed. Maybe the player could use bones from their inventory to fuel the glove, spawning skeletons that wouldn't turn hostile.

**Comment by BobMowzie** [comment]
Sorry, this platform is for bug reports. Please post suggestions in the Discord server!
