### ISSUE TITLE
Crash using Oculus?

### ISSUE THREAD

**Issue by OutrageouslyIcy** [BobMowzie/MowziesMobs#716]
While all of the bosses function using any of their items special abilities like the sun blessing attacks or the Axe of a thousand metals crashes the game.

attaching the latest log 
[latest.log](https://github.com/BobMowzie/MowziesMobs/files/14003123/latest.log)

**Comment by BobMowzie** [comment]
I need the crash report, please! Not the latest log.

**Comment by OutrageouslyIcy** [comment]
oops  sorry! here you go
[crash-2024-01-21_18.44.32-client.txt](https://github.com/BobMowzie/MowziesMobs/files/14003383/crash-2024-01-21_18.44.32-client.txt)

**Comment by BobMowzie** [comment]
Thanks. I'll see what I can do. In the meantime, please turn off custom player animations using the Mowzie's Mobs client config.

**Comment by nameedo** [comment]
lesss gooo first issue of the year

**Comment by BobMowzie** [comment]
Should be fixed
