### ISSUE TITLE
Sun's Blessing lasts forever

### ISSUE THREAD

**Issue by jagprog5** [BobMowzie/MowziesMobs#717]
Minecraft: 1.12.2
Forge: 14.23.5.2859
Mowzie's Mobs: 1.5.8 (no other mods are used, except JEI which is unrelated)

The sun's blessing effect lasts forever and displays as a status duration of "xx:xx". This is not correct, as it should show only 59:59 at most, as indicated by the in-game descriptions.

There are two ways of triggering this bug (one per attachment). The first way is to trade for it with the sun chief.

The second way is to use the item "Receive Sun's Blessing". At this point the duration for the status will be correct and ticking down as it should. However, if the sun-beam attack is used in this state then it triggers the bug and gives a duration of "xx:xx". It should have instead subtracted 2 minutes from the duration (as per the in-game description), and not extend the duration.

https://github.com/BobMowzie/MowziesMobs/assets/17582321/553bdf08-e00d-42de-9c0b-5c3f58642ed1

https://github.com/BobMowzie/MowziesMobs/assets/17582321/7c915077-5466-48a5-a912-ac42e7a5fd0a

**Comment by BobMowzie** [comment]
This is not a Mowzie's Mobs bug. This is vanilla Minecraft behavior when status effects are longer than 1639 seconds. Try it yourself with a command - it'll show the xx:xx

This doesn't mean the status effect is infinite. If you leave the game running, the effect will run out.
