### ISSUE TITLE
[1.18.2] Server Crash on Startup

### ISSUE THREAD

**Issue by Aarods** [BobMowzie/MowziesMobs#723]
When I put the new update (1.6.0) on the server-side and start it, the server crashes instantly.

Crash Report:
[crash-2024-02-23_04.11.10-fml (1).txt](https://github.com/BobMowzie/MowziesMobs/files/14381635/crash-2024-02-23_04.11.10-fml.1.txt)

Logs: 
[latest.log](https://github.com/BobMowzie/MowziesMobs/files/14381636/latest.log)

**Comment by BobMowzie** [comment]
Please send the full crash log

**Comment by Aarods** [comment]
Here: 
[crash-2024-02-23_04.11.10-fml.txt](https://github.com/BobMowzie/MowziesMobs/files/14382081/crash-2024-02-23_04.11.10-fml.txt)

**Comment by BobMowzie** [comment]
Thanks!

Hm, what happens if you remove all mods except Mowzie's Mobs and Geckolib?

**Comment by BobMowzie** [comment]
Fixed in 1.61 release
