### ISSUE TITLE
[1.18.2] Corrupt Advancement

### ISSUE THREAD

**Issue by Aarods** [BobMowzie/MowziesMobs#728]
It's not very important at all, but the achievement "Get the Sun Blessing" doesn't exist and in the logs shows that there are errors when generating it. ![image](https://github.com/BobMowzie/MowziesMobs/assets/110215990/7893db69-3f8e-4816-befd-fd7be713d96c)

![image](https://github.com/BobMowzie/MowziesMobs/assets/110215990/04042c84-4f1d-48f1-b615-e9da3649f045)

**Comment by BobMowzie** [comment]
Oh thank you! Must have missed that
