### ISSUE TITLE
[1.4.2] Can't find LLibrary class on startup

### ISSUE THREAD

**Issue by kreezxil** [BobMowzie/MowziesMobs#73]
client crash report on startup https://pastebin.com/19W1yD7v, we're using FORGE 1.12.2-14.23.4.2766

I'll crosspost to  Llibrary.

**Comment by BobMowzie** [comment]
Is this issue still present?

**Comment by kreezxil** [comment]
i wouldn't know without adding the mod back to the pack

**Comment by kreezxil** [comment]
i would just close it since no one has corroborated it in all this time.

**Comment by BobMowzie** [comment]
Alright, sounds good. Lmk if it comes back.
