### ISSUE TITLE
When I use WroughtAxe SHIFT+Right Click Mouse in the invisibility effect there is no animation at all

### ISSUE THREAD

**Issue by kitovoi111** [BobMowzie/MowziesMobs#731]
When I use SHIFT+Right Click Mouse in the invisibility effect there is no animation at all With armor equipped

**Comment by kitovoi111** [comment]
When I use the punch animation - if I'm under the invisibility effect, something strange and terrible happens.

**Comment by BobMowzie** [comment]
What punch animation?

**Comment by kitovoi111** [comment]
Sorry I'm using a translator

**Comment by kitovoi111** [comment]
Try drinking an invisibility potion and putting on armor, then take the WroughtAxe from your mod and use the hit animation.

**Comment by kitovoi111** [comment]
I don't know if this works in regular vanilla Minecraft, but I also have Embeddium installed.

**Comment by BobMowzie** [comment]
Okay cool I'll try it

**Comment by BobMowzie** [comment]
Alright, I know why this is happening. Unfortunately I can't fix it without completely rewriting my player animation system...

**Comment by kitovoi111** [comment]
Aren't you going to fix this?

**Comment by BobMowzie** [comment]
No, I can't right now. I can't think of a solution.

**Comment by kitovoi111** [comment]
> No, I can't right now. I can't think of a solution.

maybe off animation if player have effect invisibility ?

**Comment by BobMowzie** [comment]
But the animation already doesn't play...

**Comment by BobMowzie** [comment]
WAIT I have a new idea

**Comment by BobMowzie** [comment]
Fixed!
