### ISSUE TITLE
The enchantment effect is not visible in the hot bar

### ISSUE THREAD

**Issue by kitovoi111** [BobMowzie/MowziesMobs#734]
The enchantment effect is not visible in the hot bar
![image](https://github.com/BobMowzie/MowziesMobs/assets/147491823/0077feb9-33e5-47b5-af7c-e32110ca1ef9)

**Comment by kitovoi111** [comment]
if open inventory 
![image](https://github.com/BobMowzie/MowziesMobs/assets/147491823/5ce93020-7f16-4f5a-a0d3-9bcd8764e5ae)

**Comment by BobMowzie** [comment]
![enchant](https://github.com/BobMowzie/MowziesMobs/assets/7550579/17243ddc-8d76-4dad-8f7b-e8fb7cab64d5)
Works fine for me. That looks like a modded enchantment. This issue must be with the mod that adds the custom enchant.
