### ISSUE TITLE
[Question] What happened to Barako?

### ISSUE THREAD

**Issue by KamiSami** [BobMowzie/MowziesMobs#737]
Hi, just got curious seeing Barako was suddenly switched out (Not complaining, i think the new one looks really cool), so was wondering how come this happened? As he was a thing so long, and suddenly he was replaced?

**Comment by BobMowzie** [comment]
This platform is for reporting bugs. Check my twitter ir discord server.

**Comment by KamiSami** [comment]
Sorry, it's not always as obvious thing to do. Some do take questions in githubs, but i see some don't apparently. Well, could've at least appreciated a reply to my question if bothering to reply in first place, but alright then.. I did google around but couldn't find clear answer... Well, either way, good luck on developement.

**Comment by BobMowzie** [comment]
I can't answer your question here, as that would prompt a surge of other people asking questions here. It's happened before.
Please join my Discord server or check the pinned post on my twitter, like everyone else.
