### ISSUE TITLE
[1.18.2] Extreme Lag Spikes while fighitng Umvuthi

### ISSUE THREAD

**Issue by InteJason** [BobMowzie/MowziesMobs#738]
Forge: 40.2.17
Mowzies Mobs: 1.6.2
Geckolib: 1.18-3.0.57

World freezes for 10-15 seconds for every few ticks, spark profiler shows that the function EntitySunstrike.damageEntityLivingBaseNearby() is causing issues?

https://spark.lucko.me/QLPO9RACnG?hl=15182

**Comment by BobMowzie** [comment]
What other mods do you have?

**Comment by InteJason** [comment]
Over 200... I'll do a binary search to find the incompatible mod in the next few days. It did not happen with the previous versions (Baraoko Chief) though

**Comment by BobMowzie** [comment]
Do you have any Airships mods? Or Create?

**Comment by InteJason** [comment]
I have the Create mod installed, no airship mods

**Comment by InteJason** [comment]
I found the cause: Radium Reforged. After removing that mod the lag spikes are gone.

**Comment by BobMowzie** [comment]
Try turning off entity collision optimization

**Comment by InteJason** [comment]
mixin.entity.collisions
mixin.entity.stream_entity_collisions_lazily

I've disabled these two options, but the issue remains :/

**Comment by BobMowzie** [comment]
Alright I'll try patching it on my end
