### ISSUE TITLE
[Feature Request] Foliaath seeds should play a block placed sound effect when placed on the ground.

### ISSUE THREAD

**Issue by thelegitdolt** [BobMowzie/MowziesMobs#747]
https://github.com/BobMowzie/MowziesMobs/assets/50085439/aa87aedf-e8ae-454d-b62f-44e1347d06e6
They might currently already play some kind of placed sound, but it doesn't really match up with the sound they make when the seeds are broken

**Comment by BobMowzie** [comment]
Crops make different sounds when planted vs when broken. I think its fine that foliaath seeds are the same.

**Comment by thelegitdolt** [comment]
I don't feel like the the place/break sounds fit each other is the thing
