### ISSUE TITLE
[Suggestion] Make Painted Acacia craftable from slabs

### ISSUE THREAD

**Issue by Lykrast** [BobMowzie/MowziesMobs#75]
A nice qol change would be to have a recipe for Painted Acacia Wood made with 2 slabs, just like the Quark change.

**Comment by BobMowzie** [comment]
No, sorry. They are intentionally only obtainable by other means.
Quark change?

**Comment by Lykrast** [comment]
Quark adds for each vanilla slab a 2x slab -> 1x block recipe.

More specifically, the suggestion was to add a 2x Painted Acacia Wood Slab -> 1x Painted Acacia Wood recipe, to make it more convenient when you craft too many slabs to turn them back into full blocks.

This doesn't make the Painted wood itself more easily obtainable, as you still need Painted Wood to craft the slabs anyway so trading is still the only option.

**Comment by BobMowzie** [comment]
Oh oh, I see. I misread your suggestion. I'll consider it, sure.
