### ISSUE TITLE
A problem with Llibrary (the mod thats REQUIRED for MowziesMobs to run on 1.7.10)

### ISSUE THREAD

**Issue by branman5949** [BobMowzie/MowziesMobs#751]
out of the blue and just out of nowhere today was the day Llibrary just decided to stop running on my minecraft. keep in mind, i have only Llibrary. Mowzies mobs, Optifine, and AnimationAPI only running but i keep getting this crash:
[crash-2024-04-17_17.42.53-client.txt](https://github.com/BobMowzie/MowziesMobs/files/15017378/crash-2024-04-17_17.42.53-client.txt)

[latest.log](https://github.com/BobMowzie/MowziesMobs/files/15017381/latest.log)

[fml-client-latest.log](https://github.com/BobMowzie/MowziesMobs/files/15017382/fml-client-latest.log)

**Comment by BobMowzie** [comment]
What makes you think this is an llibrary issue?

**Comment by branman5949** [comment]
i took out mowzies mobs too while trying to run Llibrary and turns out it was Llibrary that was the cause.

**Comment by BobMowzie** [comment]
Okay then report this to LLibrary, not me.

**Comment by cj09bruno** [comment]
> Okay then report this to LLibrary, not me.

try the "fixed" file over on the issues page of LLibrary
https://github.com/iLexiconn/LLibrary/issues/200
