### ISSUE TITLE
Could you please update the mod to version 1 20 1

### ISSUE THREAD

**Issue by Silver00177** [BobMowzie/MowziesMobs#754]
Could you please update the mod to version 1 20 1

**Comment by Silver00177** [comment]
That's my problem that you didn't bother to upgrade to version 1 20 1

**Comment by Silver00177** [comment]
Therefore, be so kind

**Comment by BobMowzie** [comment]
Read my FAQ and please don't take all my hard work and effort for granted like this. It's very disrespectful.

**Comment by Silver00177** [comment]
Well, I'm sorry that I've been waiting for it for my version for a year

**Comment by Silver00177** [comment]
Believe me, your work will be appreciated, it's just that I'm already tired of waiting

**Comment by BobMowzie** [comment]
1.20.1 came out less than a year ago. Don't exaggerate.

I've been working incredibly hard on content updates and version ports nonstop for the past year. If you are out of patience, too bad. I cannot work faster, and reporting it as a bug won't change that.

Please change your attitude or leave me alone.

**Comment by Silver00177** [comment]
Okay, okay, that is, can we still assume the next update to version 1, 20, 1 and the release date of the mod for this version?

**Comment by BobMowzie** [comment]
You need to read my FAQ.

**Comment by Silver00177** [comment]
Okay, thank you and you will excuse me for my excessive rudeness

**Comment by Silver00177** [comment]
Hopefully there will be someone who ports it to fabric and qulit, and I understand how difficult that would be

**Comment by Silver00177** [comment]
By by
