### ISSUE TITLE
1.20.1 Server Crash

### ISSUE THREAD

**Issue by Cklarkus** [BobMowzie/MowziesMobs#755]
Log
[latest.log](https://github.com/BobMowzie/MowziesMobs/files/15445900/latest.log)

**Comment by BobMowzie** [comment]
I need to see the crash report please, not the latest log.

**Comment by Cklarkus** [comment]
> I need to see the crash report please, not the latest log.

sry server just not startup, without crash log. Only startup log

**Comment by BobMowzie** [comment]
Are you sure? Did you check the server folders?

**Comment by BobMowzie** [comment]
I think I see Ars Neauvou in there. What happens if you remove it?

**Comment by Cklarkus** [comment]
> Are you sure? Did you check the server folders?

yea i checking 2 times


> I think I see Ars Neauvou in there. What happens if you remove it?

i removed and server start
sad, its ars nouveau incompatibility :(

**Comment by BobMowzie** [comment]
Please try this test version instead! And let me know if the problem goes away.
https://legacy.curseforge.com/minecraft/mc-mods/mowzies-mobs/files/5380391

**Comment by BobMowzie** [comment]
The issue isn't resolved. That test version breaks other features, so it is not a real solution.
