### ISSUE TITLE
Rendering Overlay error

### ISSUE THREAD

**Issue by Dannyxv8** [BobMowzie/MowziesMobs#756]
Thanks so much for porting it to 1.20.1 but unfortunately it's currently unusable as it loads the mods right up until the title screen.

[crash-2024-05-25_23.49.43-client.txt](https://github.com/BobMowzie/MowziesMobs/files/15446473/crash-2024-05-25_23.49.43-client.txt)

**Comment by BobMowzie** [comment]
This is a crash related to something called dreadglare. Not Mowzie's mobs.
