### ISSUE TITLE
[1.20.1] Custom boss bar texture issues

### ISSUE THREAD

**Issue by polykatt** [BobMowzie/MowziesMobs#757]
A number of overlapping issues with the Enhanced Boss Bars texture pack, Jade HUD and Xaero's map icons. Custom boss bar textures display inside the Jade HUD - as well as the fact that I have "display bosses" turned off yet the HUD still shows and overlaps with the actual boss bar. Boss bar textures are also displayed as if icons on Xaero's Minimap & Worldmap. Without the Enhanced Boss Bars texture pack there is still the issue with the Jade HUD overlapping.

**Comment by BobMowzie** [comment]
Can you send a screenshot please?

**Comment by polykatt** [comment]
![2024-05-26_22 30 52](https://github.com/BobMowzie/MowziesMobs/assets/165610689/5582d078-8ef1-46e5-9b47-0ef9adcc0617)

**Comment by BobMowzie** [comment]
This seems like an issue with Enhanced Boss Bars texture pack, Jade HUD and Xaero's map.
I tried turning off custom boss bars in the Mowzie's Mobs client config and it worked fine.
