### ISSUE TITLE
1.20.1 - Possible incompatibility with "Bosses of Mass Destruction" and/or "Critters and Companions"

### ISSUE THREAD

**Issue by jg2002-j** [BobMowzie/MowziesMobs#760]
Have attached [latest.log](https://github.com/BobMowzie/MowziesMobs/files/15448561/latest.log) and [crash-2024-05-26_19.42.09-fml.txt](https://github.com/BobMowzie/MowziesMobs/files/15448562/crash-2024-05-26_19.42.09-fml.txt).

Can be reproduced by launching minecraft client-side with all three of these mods (and dependencies) installed.
Before reaching the title screen an error appears: `org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered`

Minecraft 1.20.1
Forge 47.2.20
mowziemobs-1.6.4.jar
[BOMD-Forge-1.20.1-1.1.1.jar](https://www.curseforge.com/minecraft/mc-mods/bosses-of-mass-destruction-forge)
[crittersandcompanions-1.20.1-2.1.6.jar](https://www.curseforge.com/minecraft/mc-mods/critters-and-companions)

**Comment by Dave3760** [comment]
It also happens with Ender Catalysm, I have a modpack with a bunch of mods, and it doesn't work when I try to run the modpack with mowzie's mobs

**Comment by BobMowzie** [comment]
Please try this test version instead! And let me know if the problem goes away.
https://legacy.curseforge.com/minecraft/mc-mods/mowzies-mobs/files/5380391

**Comment by jg2002-j** [comment]
Hi! Yes this seems to work, I could succesfully launch and load into game. I managed to summon the sunbird mobs succesfully, but baby foliaath and frostmaw didn't appear when I used `/summon`- this was probably where I was summoning them though, as I did it above ground in daytime idk?

Also awesome mod :))

**Comment by BobMowzie** [comment]
Try the spawn eggs instead!

**Comment by jg2002-j** [comment]
Sorry for the slow reply, it works with the spawn eggs :)
