### ISSUE TITLE
[Compatibility] Ears+ disappear during animations 1.20.1

### ISSUE THREAD

**Issue by AStrangeMouse** [BobMowzie/MowziesMobs#763]
**Minecraft:** 1.20.1
**NeoForge:** 47.1.106
**GeckoLib:** 4.4.4
**Ears+:** [1.4.6](https://www.curseforge.com/minecraft/mc-mods/ears/files/4452800)
**Mowzie's Mobs:** [1.6.4](https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs/files/5372378)

When animations from this mod are performed, any customization from [the Ears+ mod](https://www.curseforge.com/minecraft/mc-mods/ears) disappears until the animation ends.

**Comment by BobMowzie** [comment]
This is not possible to fix.
