### ISSUE TITLE
Error on Frostmaw's dodge cooldown

### ISSUE THREAD

**Issue by Lykrast** [BobMowzie/MowziesMobs#77]
https://github.com/BobMowzie/MowziesMobs/blob/1.12/src/main/java/com/bobmowzie/mowziesmobs/server/entity/frostmaw/EntityFrostmaw.java#L503

This looks like an oversight and may be why Frostmaws don't use their dodge animations (or at least why I haven't seen one do it).

**Comment by BobMowzie** [comment]
Good catch!
