### ISSUE TITLE
[suggestion] Better Barakoa AI

### ISSUE THREAD

**Issue by BlueWither** [BobMowzie/MowziesMobs#78]
I think they should not leave their village.

**Comment by BobMowzie** [comment]
Hunting packs of Barakoana spawn all over the Savanna. This is intentional, and allows players to obtain the masks without attacking the village or after they've killed Barako.

**Comment by BlueWither** [comment]
Instead, it is about the villager Barakoa.

**Comment by BlueWither** [comment]
Villager barakoas sometimes leave their village where chiefs are located after a while.
