### ISSUE TITLE
Using weapons and abilities while in 3rd person crashes game.

### ISSUE THREAD

**Issue by Bookninja234** [BobMowzie/MowziesMobs#780]
1.20.1

Mods: Ice and Fire, Mowzie's Mobs, Optifine, Geckolib, Dragon Survival, Citadel

Crash report:

The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: class com.bobmowzie.mowziesmobs.client.render.entity.layer.GeckoArmorLayer cannot be cast to class software.bernie.geckolib.renderer.layer.GeoRenderLayer (com.bobmowzie.mowziesmobs.client.render.entity.layer.GeckoArmorLayer is in module mowziesmobs@1.6.4 of loader 'TRANSFORMER' @6e60f18; software.bernie.geckolib.renderer.layer.GeoRenderLayer is in module geckolib@4.4.7 of loader 'TRANSFORMER' @6e60f18)

**Comment by BobMowzie** [comment]
Update Mowzie's Mobs
