### ISSUE TITLE
Broken Mask Texture

### ISSUE THREAD

**Issue by jmborlovan** [BobMowzie/MowziesMobs#784]
For 1.20.1 the mask texture is broken.
![Screenshot_12](https://github.com/BobMowzie/MowziesMobs/assets/9578796/d0c22414-c91c-4e79-b082-7089ed0fd319)

**Comment by BobMowzie** [comment]
Remove optifine, please!

**Comment by jmborlovan** [comment]
> Remove optifine, please!

Aww darn I had a few mods that use it! There's no way to bypass it? :(

**Comment by BobMowzie** [comment]
Sorry, unfortunately not...
