### ISSUE TITLE
Ice & Fire Gorgon's stone freezing is bugged due to Frostmaw

### ISSUE THREAD

**Issue by Xorbah** [BobMowzie/MowziesMobs#79]
I believe they both use the same 'freezing' code with the exception that the frostmaw freeze eventually undoes itself whereas the Gorgon's does not. However, when both are installed then the Gorgon method of freezing retains the stone like textures on the mobs and doesn't stay frozen (obviously)

Link to mod although you know of it already

https://minecraft.curseforge.com/projects/ice-and-fire-dragons?gameCategorySlug=mc-mods&projectID=264231

**Comment by BobMowzie** [comment]
I can't fix this.

**Comment by BobMowzie** [comment]
Actually, I'll keep it open in case that changes.

**Comment by BobMowzie** [comment]
This might be fixed now. Please try version 1.5.2 and let me know.

**Comment by naqaden** [comment]
This seems to be fixed. I have both mods installed and the Gorgon's victims stay 'frozen' in place.
