### ISSUE TITLE
Frostmaw Internal Server Error

### ISSUE THREAD

**Issue by EdoEquin0x** [BobMowzie/MowziesMobs#790]
Happen on 1.20.1, when the frostmaw use his frost breath or frost ball and it touch the player, chances are the player will have an internal server exception, kicking him from the server.

**Comment by BobMowzie** [comment]
Wait, why was this marked as completed? Sounds like an important issue to fix.

Do you have the full crash log?

**Comment by EdoEquin0x** [comment]
Hello! I closed the issue because after heavy investigation the Frostmaw was indeed triggering a ConcurrentModificationException but Mowziemobs was not the direct cause of it, simply the trigger (as any other mod using the specific problematic method could have been) . So no worries!

**Comment by EdoEquin0x** [comment]
To add more context : I had a mod with a very poorly coded entitytick method that was the cause of all this, fixed it myself

**Comment by BobMowzie** [comment]
Ah! Thanks for letting me know.
