### ISSUE TITLE
The Sunbird has hurt me immensely, deep in my soul.

### ISSUE THREAD

**Issue by TotallyTopaz** [BobMowzie/MowziesMobs#794]
The game crashed whilst rendering entity in world Error: java.lang.NullPointerException: Cannot invoke "com.bobmowzie.mowziesmobs.server.entity.umvuthana.EntityUmvuthi.updateRattleSound(float)" because "this.animatable" is null

I have added the crash report. I had fought a sunbird but didn't kill it and had my spawn set near by. Used a waystone and went home where I was killed by a pillager. Instead of respawning at my bed by the sunbird I crashed. We (my husband and I) aren't modders or anything. We basically know "download pack/hit play". Any advice is appreciated. We have even gone as far as deleting all my data to basically make me a new player (how he described what he did, I dunno) and I still crashed. 

[Crashssss.txt](https://github.com/user-attachments/files/16738373/Crashssss.txt)

**Comment by BobMowzie** [comment]
This is already fixed! Update Mowzie's Mobs.
