### ISSUE TITLE
Right Clicking Axe of Thousand Metals crashes game with exit code -1

### ISSUE THREAD

**Issue by RRezkin** [BobMowzie/MowziesMobs#797]
Anytime I try to right click the axe from ferrous, it crashes my game and doesn't use the move
[crash-2024-08-27_10.31.31-client.txt](https://github.com/user-attachments/files/16766642/crash-2024-08-27_10.31.31-client.txt)

**Comment by RRezkin** [comment]
This is on a server with the Crazy Craft Updated modpack from curse forge

**Comment by BobMowzie** [comment]
Update Mowzie's Mobs
