### ISSUE TITLE
Eclipse source error 

### ISSUE THREAD

**Issue by Pacito2** [BobMowzie/MowziesMobs#81]
I really need the source code of the mod for modify the health and damages of mobs.
I downloaded the forge Mdk 1.12.2, added the MowziesMobs source and import library llibrary-1.7.9-1.12.jar but i have some errors : http://www.noelshack.com/2018-44-6-1541206291-mowzies.png

Please help me. I really need it.
Thank you !

**Comment by BobMowzie** [comment]
I'm not going to encourage other people editing or copying the source code of my mod for their own means. Even so, I'm not sure what's wrong there.

Still, modifying health and attack damage is very simple and you do not need to open my whole project. In your entity file, just override the method:

`protected void applyEntityAttributes()
    {
        super.applyEntityAttributes();
        this.getEntityAttribute(SharedMonsterAttributes.MAX_HEALTH).setBaseValue(20.0D);
        this.getEntityAttribute(SharedMonsterAttributes.ATTACK_DAMAGE).setBaseValue(5.0D);
    }`

Replace 20.0 and 5.0 with whatever values you want. You can also set movement speed and other properties in this method.

**Comment by Pacito2** [comment]
Thank you,
Which entity file ? Sorry I don't have understand how I can Override the methode without the source code.
Can you explain more please ?
Thank you
