### ISSUE TITLE
Right click to summon Barakoas only swaps helmet slot/mask with tribal kind mask

### ISSUE THREAD

**Issue by gittycup** [BobMowzie/MowziesMobs#83]
Running compitum magia mod, and when trying to summon a tribal member by right clicking with a mask in hand only swaps masks with the chiefs mask. Mod perhaps needs a right click armor slot blocking addition? I found an old 2014 NoClickArmor.jar from the bukkit forums of long ago, but no idea how to install it, as it does not show up in the list of available mods in twitch.

**Comment by BobMowzie** [comment]
Does it work without the Compitum Magia Mod?
Make sure you are WEARING the chieftan's maks, and right click while holding a non-chieftan mask.

**Comment by gittycup** [comment]
I am running through twitch, since I can't seem to just add Mowzie's mod without installing a pack, I must create a custom profile, I intend to run 1.12.2 and install just LLibrary and Mowzie's mod to see but am unsure of what version of forge to choose. I am sure it probably behaves correctly if no one else is having a problem.

I have already disabled half of compitum magia mod pack because I don't care for that half of it, I really wish I knew how to put together my own pack to include Mowzie's Mobs.
I have already disabled more than half of this mod pack but still have not found the culprit, it would be nice to find so that you would know which mod is conflicting and could point it out as well. I hav also disabled what I thought would help in QUARK by disabling armor swap in the MISC tab, but this did not seem to be either what I thought it did or something is over riding that.

 The behavior is: if you are wearing the chief's mask and hold a tribal member mask of any flavor, right clicking with the mask in your hand just swaps the mask you are holding with the mask you are wearing.

**Comment by BobMowzie** [comment]
I see. Well, without knowing what mod is causing the conflict, this is something I cannot fix.

**Comment by gittycup** [comment]
After exhaustive testing I found found the culprit, it is a mod called:
Dungeon Tactics by Pegbeard, I was using DungeonTactics-1.12.2-0.15.6.jar and there was an update today(11/13/2018) 1.12.2-0.15.7.jar, both still create this conflict.
There is no config to turn this option off in the GUI for Dungeon Tactics(greyed out) so there is no way to turn off this feature in his mod. In fact, looking at his mod page, he does not even list armor hot swapping of this nature as a feature of his mod, so perhaps this is something carried over from something he is either not aware of, or I can't find it listed.

**Comment by BobMowzie** [comment]
Okay. I'll do the best I can to find a way around this.

**Comment by gittycup** [comment]
Yes, to be honest is more on his mod than yours as this would disable any mod's feature that wishes to put a secondary right click feature on a piece of equiptment, a work around to override the commands in that mod. A workaround would be greatly appreciated though! Not complaining :) Thank you for such quick responses!

**Comment by gittycup** [comment]
Dungeon Tactic Author response:
_This is a feature - it should be listed, though I may have forgotten to add it to the description.
This feature will not be removed. There is a config option to disable it - I have not bothered to implement the config GUI yet (looked into it, got bored), you can edit the config file in your Minecraft instance folder in AppData._

Since the mod author of Dungeon tactics can't be bothered and closed the issue when raised in his mod.
 I tracked down the fix in the .cfg of Dungeon Tactics by editing the line:
B:"C-Quick Change Armour"=true
to be:
 B:"C-Quick Change Armour"=false

as an aside this line in the line in his config might also cause other people anxiety if using invis potions or effects:
    # If 'true' armour will be unequipped and placed into the inventory of players with invisibility. [default: true]
    B:"C-Invisiblity Removes Armour"=true
    B:"C-Modded Material Weapons"=true

**Comment by BobMowzie** [comment]
Okay great! I’m going to consider this closed as well.

**Comment by Sunconure11** [comment]
Compitum Magia is my modpack. I am working on another update for it, though I'm busy slogging through an update to streamline some things a bit further, due to my transition from EnderZoo to EnderIO Zoo.

One of the mods I have updated in the next update is in fact, Dungeon Tactics.
