### ISSUE TITLE
Add in spawning condition for Barakoana's hunting party

### ISSUE THREAD

**Issue by mser7** [BobMowzie/MowziesMobs#84]
I built my animal farms in the savanna and one group spanwed in and kill the animals, so I raised the fence so that they cannot reach the inside, but then they just spawned inside one of the pence and kill the animals again. I suggest make it so that they check for block light level to spawn, if it is bigger than 7, due to a light source, than the party won't spawn there.

**Comment by BobMowzie** [comment]
Oh, hm. That's frustrating for sure and definitely not intended behavior.
Light level spawning doesn't feel right for the Barakoa. I could just directly prevent them from spawning near animals.
