### ISSUE TITLE
Update of ja_JP.lang

### ISSUE THREAD

**Issue by BlueWither** [BobMowzie/MowziesMobs#88]
entity.naga.name=ナーガ
item.earthTalisman.text.5=空中でダブルクリックしスニークすると回転が始まる
item.earthTalisman.text.6=採掘したいものに向かって方向を転換する
item.earthTalisman.text.7=地上でスニークして解除
item.nagaFang.name=ナーガの牙
item.nagaFang.text.0=毒耐性のポーションの材料
potion.poisonResist=毒耐性
potion.effect.poisonResist=耐毒のポーション

**Comment by BlueWither** [comment]
And if naga is Nimbus Drake...
Naga egg=ナーガの卵

**Comment by BobMowzie** [comment]
Thanks so much!
