### ISSUE TITLE
lang broken in latest version

### ISSUE THREAD

**Issue by lag42** [BobMowzie/MowziesMobs#89]
the lang is broken in 1.5.0

**Comment by BobMowzie** [comment]
What is wrong with it?

**Comment by lag42** [comment]
[this](https://imgur.com/a/RX6XaP4)

**Comment by BobMowzie** [comment]
That's strange. It works in my development space and I've never seen this happen before.

**Comment by LukewarmYeti** [comment]
Yeh it's broken for me as well, nothing in the mod has localisation as of 1.5.

**Comment by PCAwesomeness** [comment]
I can confirm that it doesn't work for me, either.

**Comment by BlueWither** [comment]
ja_JP is also breaking...

**Comment by PCAwesomeness** [comment]
This issue is now fixed.

Thank you so much, Mowzie!
