### ISSUE TITLE
Balancing suggestions

### ISSUE THREAD

**Issue by PCAwesomeness** [BobMowzie/MowziesMobs#93]
**Frostmaw:**
I know you wanted to make it so the Frostmaw is unable to be cheesed to death with arrows, but, IMO, having it be completely immune to arrows _may_ be a bit overkill. Its ice ball attack already punishes anyone who tries to go too far away from them, it attacks targets close to it quite relentlessly, and the alternate strategy of slashing it with your sword while running circles around it isn't guaranteed to bring it down very quickly, as it can jump away from you; as well as this, it feels pretty weird seeing your arrow bounce off a furry beast with a metallic banging sound. 

Obviously, it shouldn't take full damage from arrows so the arrow spam is not a viable strategy; however, perhaps taking reduced damage (like about 25% damage) from arrows would be a bit more realistic?

**Naga:**
Were the Nagas intended to be mini-bosses, or just regular baddies? Their massive size seems to suggest the former, while their low health and tendency to spawn in large flocks indicates the latter; when it comes to fighting them, you can just shoot them out of the sky and hit them with your sword a few times, and they're practically done for.

If they were intended to be the former, perhaps their base health can get a small boost to about 50 or 60 HP?

(Now, I'm aware that you can tweak the health in the config, but having the base health be changed is always nice.)

**Comment by BobMowzie** [comment]
Frostmaw really aren't supposed to be beatable. Maybe you're right, though.

Nah, they are minor enemies. Leather armor is enough for one if you're good. Iron for two or more. The reward for beating them isn't that great, so they're not that strong to match. Still a fun fight and a challenge in the early game.
If you'd like them to be more than that, feel free to turn down the spawn rate and turn up the stats.
