### ISSUE TITLE
Frostmaw don't hand crystal

### ISSUE THREAD

**Issue by BlueWither** [BobMowzie/MowziesMobs#99]
![](https://i.imgur.com/68SOOBn.png)

**Comment by BobMowzie** [comment]
Damn, I thought I fixed this.
If you approach the hand, you'll notice you can still pick up the crystal. It's just a visual bug.

**Comment by PCAwesomeness** [comment]
![2019-01-11_23 17 07](https://user-images.githubusercontent.com/8507148/51069550-0e263080-15f7-11e9-9899-2c1d7b10e9ec.png)
It seems to be working just fine for me; perhaps it could be a client-side issue?

**Comment by BobMowzie** [comment]
I'm getting it on some and not others. It's making this quite hard to debug.

**Comment by BlueWither** [comment]
Oh sometimes it worked correctly

**Comment by BobMowzie** [comment]
No longer seeing this issue.
